using System.Text;
using System.Text.RegularExpressions;

namespace MbConst;

internal static partial class Scan
{
    private static void WriteSummary(string dir, Graph g, List<(Graph.Member, string)> roots, List<Lit> lits, List<Table> tables, List<IdCheck> ids,
        List<AssetValue> assets, Life life, List<SysItem> systems, List<Lit> sample, Cross cross, List<KeyRef> keyRefs, Registry reg)
    {
        var sb = new StringBuilder();
        var game = lits.Where(l => l.Class == "gameplay").ToList();
        sb.AppendLine("# Pass 1 — self-discovery of gameplay numbers (§3)");
        sb.AppendLine();
        sb.AppendLine($"Generated by `Tools/export/mbconst scan` on {DateTime.Now:yyyy-MM-dd HH:mm}. Static only: Roslyn (the .NET SDK's) over Sim + Game with the Unity 6 DLLs; no Unity, no tests.");
        sb.AppendLine();
        sb.AppendLine("## 3.1 Reachability");
        sb.AppendLine();
        sb.AppendLine($"- Members (methods, constructors, properties, fields): {g.Members.Count}; reachable from the entry points: {g.Members.Values.Count(m => m.Reachable)}.");
        foreach (var grp in roots.GroupBy(r => r.Item2)) sb.AppendLine($"- Roots \"{grp.Key}\": {grp.Count()}");
        sb.AppendLine("- Edges: calls, reads, object creations, operators, method groups; a virtual / interface call reaches every override; a constructor reaches the instance field initializers.");
        sb.AppendLine();
        sb.AppendLine("## Candidates (every numeric literal in Sim/** and Game/**, SimTunables*.cs left out)");
        sb.AppendLine();
        sb.AppendLine($"Total {lits.Count}: gameplay {game.Count}, " + string.Join(", ", lits.GroupBy(l => l.Class).Where(x => x.Key != "gameplay").Select(x => $"{x.Key} {x.Count()}")) + $". Moved already (keys in tunables.json): {reg.Keys.Count}.");
        sb.AppendLine();
        sb.AppendLine("| class | reason | count |");
        sb.AppendLine("|---|---|---|");
        foreach (var x in lits.Where(l => l.Class != "gameplay").GroupBy(l => (l.Class, Regex.Replace(l.Reason, @"\(.*\)|written to \w+.*", m => m.Value.StartsWith("written") ? (m.Value.Contains("nothing") ? "written, never read" : "written, read only outside the simulation") : ""))).OrderBy(x => x.Key.Class).ThenByDescending(x => x.Count()))
            sb.AppendLine($"| {x.Key.Class} | {x.Key.Item2.Trim()} | {x.Count()} |");
        sb.AppendLine();
        sb.AppendLine("### Gameplay by pass-2 lane and move mode");
        sb.AppendLine();
        sb.AppendLine("| lane | domains | literals | keys | inline | const/static → property | local const | manual |");
        sb.AppendLine("|---|---|---|---|---|---|---|---|");
        foreach (var lane in Lanes)
        {
            var ls = game.Where(l => l.Lane == lane).ToList();
            sb.AppendLine($"| {lane} | {string.Join(", ", ls.Select(l => l.Domain).Distinct())} | {ls.Count} | {ls.Select(l => l.Key).Distinct().Count()} | {ls.Count(l => l.Mode == "inline")} | " +
                          $"{ls.Count(l => l.Mode is "const_to_property" or "static_to_property")} | {ls.Count(l => l.Mode == "local_const")} | {ls.Count(l => l.Mode.StartsWith("manual"))} |");
        }
        sb.AppendLine();
        sb.AppendLine("Manual reasons: " + string.Join("; ", game.Where(l => l.Mode.StartsWith("manual")).GroupBy(l => Regex.Replace(l.Mode, @" \(.*", "")).OrderByDescending(x => x.Count()).Select(x => $"{x.Key[7..]} {x.Count()}")));
        sb.AppendLine();
        sb.AppendLine("### Gameplay by group (lane B's scan groups)");
        sb.AppendLine();
        sb.AppendLine(string.Join(", ", game.GroupBy(l => l.Group).OrderByDescending(x => x.Count()).Select(x => $"{x.Key} {x.Count()}")));
        sb.AppendLine();
        sb.AppendLine("## 3.2 The six scans");
        sb.AppendLine();
        sb.AppendLine($"- (a) literals by syntax tree: {lits.Count} (reachable {lits.Count(l => l.Reachable)}).");
        sb.AppendLine($"- (b) hidden tables: {tables.Count} ({string.Join(", ", tables.GroupBy(t => t.Kind).Select(x => $"{x.Key} {x.Count()}"))}); reachable {tables.Count(t => t.Reachable)}, holding {tables.Sum(t => t.Lits.Count(l => l.Class == "gameplay"))} gameplay literals (`scan_b_tables.csv`).");
        sb.AppendLine($"- (c) hard-coded by id / name: {ids.Count} checks, {ids.Count(i => i.Reachable)} reachable from the simulation; one proposed data flag each (`scan_c_id_checks.csv`, committed list `Tools/export/pack2/id_hardcodes.csv`).");
        sb.AppendLine($"- (d) Unity assets: {assets.Count(a => a.Value != "")} serialised numbers on Sim / Game/Match scripts, {assets.Count(a => a.Decision.StartsWith("gameplay"))} read by the simulation; Unity components (collider, NavMeshAgent, Animator, physics) in reachable code: {assets.Count(a => a.Decision.StartsWith("CHECK"))} (`scan_d_assets.csv`). Sim has noEngineReferences: it cannot read a Unity component.");
        sb.AppendLine($"- (e) entity lifecycle: {lits.Count(l => l.FoundBy.Contains('e'))} reachable literals put on (entity, step) cells (`scan_e_lifecycle_matrix.csv`; cells with 0 are listed below).");
        sb.AppendLine($"- (f) per system class (*System, *Director, *Mode, *Session, *Ai): {systems.Count} items in {systems.Select(s => s.Class).Distinct().Count()} classes, {systems.Count(s => s.Decision.StartsWith("da_trong"))} already in data (`scan_f_systems.csv`).");
        sb.AppendLine();
        var onlyOne = game.Where(l => l.FoundBy.Count == 1).ToList();
        sb.AppendLine($"Agreement on gameplay literals: found by a only {onlyOne.Count}, by 2 scans {game.Count(l => l.FoundBy.Count == 2)}, by 3+ {game.Count(l => l.FoundBy.Count >= 3)}. The a-only ones are reachable literals outside any system class, lifecycle step or table: reviewed through the 150 sample and kept gameplay (\"doubt -> gameplay\").");
        sb.AppendLine();
        var steps = Steps.Select(s => s.step).ToList();
        var empty = Entities.Select(e => e.entity).SelectMany(e => steps.Where(s => life.Matrix.GetValueOrDefault((e, s)) == 0).Select(s => $"{e}/{s}")).ToList();
        sb.AppendLine($"Lifecycle cells with no literal ({empty.Count}): {string.Join(", ", empty)}. A 0 cell means the step has no number of its own for that entity (it uses a shared one or the data's), or the names do not say the entity.");
        sb.AppendLine();
        sb.AppendLine("## 3.3 Cross-checks");
        sb.AppendLine();
        sb.AppendLine($"- (a) Count: total {lits.Count} = gameplay remaining {game.Count} + excluded {lits.Count - game.Count} (each literal has exactly one class); moved {reg.Keys.Count} keys. No literal of b / c / e / f is outside a.");
        var zero = keyRefs.Where(k => k.Refs == 0).ToList();
        var unreach = keyRefs.Where(k => k.Refs > 0 && k.ReachableRefs == 0).ToList();
        sb.AppendLine($"- (b) Keys referenced by code: {keyRefs.Count - zero.Count}/{keyRefs.Count}; no reference: {zero.Count} ({string.Join(", ", zero.Select(k => k.Key).Take(30))}); referenced only by code outside the simulation: {unreach.Count} ({string.Join(", ", unreach.Select(k => k.Key + " [" + k.Example + "]").Take(30))}). A reference to a key that does not exist does not compile (the check's (d)).");
        sb.AppendLine($"- (c) Counter-sample: 150 of the {lits.Count(l => l.Class is "visual" or "infrastructure")} visual / infrastructure literals (seed 20261003): `sample150.csv`; reviewed by hand, result in Docs/export/CHANGES.md.");
        sb.AppendLine($"- (d) Pack: tunables keys not found in the pack's xlsx text: {cross.KeysNotInPack.Count} ({string.Join(", ", cross.KeysNotInPack.Take(20))}); JSON property names under Resources/Data that no C# string names: {cross.UnreadJson.Count} (`json_unread.txt`); numbers in code not in the pack = the gameplay candidates above.");
        sb.AppendLine("- (e) Python generator numbers are not scanned (C# only).");
        sb.AppendLine();
        sb.AppendLine("### §4 items and the numbers found for them");
        sb.AppendLine();
        sb.AppendLine("| §4 item | gameplay literals left | keys already in data |");
        sb.AppendLine("|---|---|---|");
        foreach (var (item, n, k) in cross.Section4) sb.AppendLine($"| {item} | {n} | {k} |");
        File.WriteAllText(Path.Combine(dir, "summary.md"), sb.ToString(), new UTF8Encoding(false));
        File.WriteAllLines(Path.Combine(dir, "json_unread.txt"), cross.UnreadJson);
        File.WriteAllLines(Path.Combine(dir, "only_scan_a.txt"), onlyOne.Select(l => $"{l.File}:{l.Line} {l.Text} {l.Context} {l.Owner}.{l.Member} | {l.LineText}"));
    }

    private static void WriteChuaNhacToi(string qaDir, List<Lit> lits)
    {
        var game = lits.Where(l => l.Class == "gameplay").ToList();
        var rx = Section4.Select(s => (s.item, r: new Regex(s.rx))).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("# Chưa nhắc tới — nhóm tham số không khớp mục 4");
        sb.AppendLine();
        sb.AppendLine("Sinh bởi `Tools/export/mbconst scan` (lượt 1). Nhóm = lớp chứa số (lĩnh vực / lớp). Một nhóm \"khớp mục 4\" khi đa số số của nó trúng mẫu tên của một mục 4.x " +
                      "(tên lớp, hàm, biến, tệp). Nhóm dưới đây không trúng mục nào: quyết định ghi ở cột cuối.");
        sb.AppendLine();
        sb.AppendLine("## Số lối chơi (ra dữ liệu ở lượt 2)");
        sb.AppendLine();
        sb.AppendLine("| lĩnh vực | lớp | số literal | ví dụ | quyết định |");
        sb.AppendLine("|---|---|---|---|---|");
        var total = 0;
        foreach (var grp in game.GroupBy(l => (l.Domain, l.Owner)).OrderBy(x => x.Key.Domain).ThenByDescending(x => x.Count()))
        {
            var hits = grp.Count(l => rx.Any(r => r.r.IsMatch(l.Owner + " " + l.Member + " " + l.CtxName + " " + l.File)));
            if (hits * 2 > grp.Count()) continue;
            total += grp.Count();
            var ex = string.Join("; ", grp.Take(3).Select(l => $"{l.File}:{l.Line} `{l.Text}` ({l.Member})"));
            sb.AppendLine($"| {grp.Key.Domain} | {grp.Key.Owner} | {grp.Count()} | {ex.Replace("|", "/")} | ra dữ liệu (lane {grp.First().Lane}) |");
        }
        sb.AppendLine();
        sb.AppendLine($"Tổng: {total} số lối chơi trong các nhóm không khớp mục 4.");
        sb.AppendLine();
        sb.AppendLine("## Nhóm loại (không ra dữ liệu), theo lý do");
        sb.AppendLine();
        sb.AppendLine("| loại | lý do | số | ví dụ |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var grp in lits.Where(l => l.Class != "gameplay").GroupBy(l => (l.Class, Regex.Replace(l.Reason, @" \(.*|, which.*|, read only.*| in \w+\.\w+.*", ""))).OrderBy(x => x.Key.Class).ThenByDescending(x => x.Count()))
        {
            var ex = string.Join("; ", grp.Take(2).Select(l => $"{l.File}:{l.Line} `{l.Text}`"));
            sb.AppendLine($"| {grp.Key.Class} | {grp.Key.Item2.Replace("|", "/")} | {grp.Count()} | {ex} |");
        }
        File.WriteAllText(Path.Combine(qaDir, "Chua_nhac_toi.md"), sb.ToString(), new UTF8Encoding(false));
    }
}
