"""Writes Tools/docs/unit_sheet.json: each unit's shape note ("Hình dạng (cho AI vẽ)"), description ("Miêu tả") and proposed
unlock ("Mở khóa đề xuất") from the balance sheet's unit sheets (Phương tiện, Công trình, Boss), for the design document
(prompt 25 F1, DECISIONS 25E). The game holds no shape notes (they are the model makers' brief), so the document reads
them from here; descriptions and unlocks in the document come from the game (the Guide card, the campaign), the sheet's
are kept for reference.

    python Tools/docs/unit_sheet.py
"""
import json
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / 'Docs' / 'balance' / 'Machine_Brigade_Can_bang.xlsx'
OUT = Path(__file__).resolve().parent / 'unit_sheet.json'
SHEETS = ('Phương tiện', 'Công trình', 'Boss')


def main():
    wb = openpyxl.load_workbook(XLSX, data_only=True, read_only=True)
    units = {}
    for name in SHEETS:
        rows = list(wb[name].iter_rows(values_only=True))
        head = [str(c).strip() if c is not None else '' for c in rows[0]]
        col = {h: i for i, h in enumerate(head)}
        for r in rows[1:]:
            vid = r[col['id']] if r and col.get('id') is not None else None
            if not vid:
                continue
            entry = {'sheet': name}
            for key, title in (('shape', 'Hình dạng (cho AI vẽ)'), ('description', 'Miêu tả'), ('unlock', 'Mở khóa đề xuất')):
                if title in col and r[col[title]] not in (None, ''):
                    entry[key] = ' '.join(str(r[col[title]]).split())
            units[str(vid).strip()] = entry
    doc = {'_about': 'Generated by Tools/docs/unit_sheet.py from Docs/balance/Machine_Brigade_Can_bang.xlsx (sheets '
                     + ', '.join(SHEETS) + '): shape = "Hình dạng (cho AI vẽ)", description = "Miêu tả", unlock = "Mở khóa đề xuất".',
           'units': dict(sorted(units.items()))}
    OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1) + '\n', encoding='utf-8', newline='\n')
    print('wrote', OUT, len(units), 'units')


if __name__ == '__main__':
    main()
