using System.Collections.Generic;

namespace MachineBrigade.Game.Hud
{
    /// <summary>
    /// Prompt 32 L4-L8: the base system's new words in English and Vietnamese (the HQ types and their skill, the HQ's
    /// damage marks, the opening squads, the ammunition handbook's frame). Numbers are filled from the data.
    /// </summary>
    public static class BaseText
    {
        public static readonly Dictionary<string, (string en, string vi)> Table = new()
        {
            // ---------------------------------------------------------------- L4: HQ types
            ["hq.type.fortress"] = ("Fortress", "Pháo đài"),
            ["hq.type.garrison"] = ("Garrison", "Đồn trú"),
            ["hq.type.shield"] = ("Shield", "Lá chắn"),
            ["hq.branch.ground"] = ("ground guns", "pháo mặt đất"),
            ["hq.branch.air"] = ("anti-air guns", "pháo phòng không"),
            ["hq.type.fortress.info"] = ("Guns on the HQ ({branch}): {share}% of a medium tower's fire at this HQ level.",
                "Vũ khí trên nhà chính ({branch}): {share}% hỏa lực một tháp vừa ở cấp nhà chính này."),
            ["hq.type.garrison.info"] = ("A squad stocked every {every} s (two at most) turns out when enemies enter the base; up to {cap} CP of it alive. It never leaves the base and goes back in after {clear} s of quiet.",
                "Mỗi {every} s tích một tổ (tối đa hai), tự ra khi địch vào căn cứ; tối đa {cap} CP còn sống. Không rời căn cứ, rút vào sau {clear} s yên tĩnh."),
            ["hq.type.shield.info"] = ("A point-defence dome over the base ({share}% of a medium C-RAM: missiles, drones, rockets, part of the shells; never tank shells); towers unhit for {delay} s mend {regen}% a second.",
                "Vòm phòng thủ điểm trên căn cứ ({share}% một C-RAM vừa: tên lửa, drone, rốc-két, một phần đạn pháo; không chặn đạn pháo xe tăng); tháp không trúng đạn {delay} s hồi {regen}% máu mỗi giây."),
            ["hq.skill.fortress"] = ("Barrage", "Loạt bắn"),
            ["hq.skill.garrison"] = ("Alarm", "Báo động"),
            ["hq.skill.shield"] = ("Dome", "Vòm khiên"),
            ["hq.skill.fortress.tip"] = ("Focused barrage: three heavy rounds on the point you tap. Every {cooldown} s.",
                "Loạt bắn tập trung: ba phát mạnh vào điểm bạn chạm. Mỗi {cooldown} s."),
            ["hq.skill.garrison.tip"] = ("Alarm: every stocked squad turns out now ({stock} ready). Every {cooldown} s.",
                "Báo động: mọi tổ đã tích ra ngay ({stock} tổ sẵn sàng). Mỗi {cooldown} s."),
            ["hq.skill.shield.tip"] = ("Emergency dome: for {seconds} s the base's dome absorbs {share}% of the HQ's health. Every {cooldown} s.",
                "Vòm khiên khẩn cấp: trong {seconds} s vòm hấp thụ {share}% máu tối đa của nhà chính. Mỗi {cooldown} s."),
            ["target.hqSkill"] = ("Tap where the HQ's barrage lands", "Chạm vào nơi loạt bắn của nhà chính rơi xuống"),
            ["camp.hqType"] = ("HQ type: {type} · tap to change", "Kiểu nhà chính: {type} · chạm để đổi"),
            ["camp.hqTypeFortress"] = ("{type} ({branch})", "{type} ({branch})"),
            ["hq.news.title"] = ("HQ types", "Kiểu nhà chính"),
            ["news.hqType"] = ("The HQ doctrine is now the HQ type: Fortress, Garrison or Shield. Choose one free on the Base screen (tap the HQ).",
                "Học thuyết nhà chính nay là kiểu nhà chính: Pháo đài, Đồn trú hoặc Lá chắn. Chọn miễn phí ở màn Căn cứ (chạm vào nhà chính)."),
            ["unit.headquarters.fortress_ground"] = ("Headquarters · Fortress", "Sở chỉ huy · Pháo đài"),
            ["unit.headquarters.fortress_air"] = ("Headquarters · AA Fortress", "Sở chỉ huy · Pháo đài phòng không"),
            ["unit.headquarters.shield"] = ("Headquarters · Shield", "Sở chỉ huy · Lá chắn"),
            ["short.headquarters.fortress_ground"] = ("Fortress HQ", "SCH Pháo đài"),
            ["short.headquarters.fortress_air"] = ("AA Fortress", "Pháo đài PK"),
            ["short.headquarters.shield"] = ("Shield HQ", "SCH Lá chắn"),

            // ---------------------------------------------------------------- L8: the ammunition handbook (numbers filled from the data)
            ["dossier.ammo"] = ("Ammunition handbook", "Sổ tay đạn"),
            ["hb.intro"] = ("Every number here is read from the game's data.", "Mọi con số ở đây lấy từ dữ liệu của trò chơi."),
            ["hb.none"] = ("none yet", "chưa có"),
            ["hb.kind.Ground"] = ("Ground", "Mặt đất"),
            ["hb.kind.Air"] = ("Air", "Máy bay"),
            ["hb.kind.Structure"] = ("Structures", "Công trình"),
            ["hb.types.title"] = ("Damage types", "Loại sát thương"),
            ["hb.types.type"] = ("Type", "Loại"),
            ["hb.types.line"] = ("{type}: strong against {strong} ({strongMult}), weak against {weak} ({weakMult}). For example: {examples}.",
                "{type}: mạnh với {strong} ({strongMult}), yếu với {weak} ({weakMult}). Ví dụ: {examples}."),
            ["hb.pen.title"] = ("Penetration against armour", "Xuyên so với giáp"),
            ["hb.pen.diff"] = ("Penetration against the face's armour", "Xuyên so với giáp mặt trúng"),
            ["hb.pen.mult"] = ("Damage", "Sát thương"),
            ["hb.pen.step0"] = ("2 levels or more above", "Hơn từ 2 cấp"),
            ["hb.pen.step1"] = ("1 level above", "Hơn 1 cấp"),
            ["hb.pen.step2"] = ("Level", "Bằng cấp"),
            ["hb.pen.step3"] = ("1 level under", "Thiếu 1 cấp"),
            ["hb.pen.step4"] = ("2 levels under", "Thiếu 2 cấp"),
            ["hb.pen.step5"] = ("3 levels or more under", "Thiếu từ 3 cấp"),
            ["hb.pen.faces"] = ("Armour has a direction: front, side, rear and roof, each its own level (vehicles up to {unit}, bosses up to {boss}). A round hits the face it meets; on the roof and on aircraft it never overmatches (one level above, {roofMult}, is the most).",
                "Giáp có hướng: trước, hông, sau và nóc, mỗi mặt một cấp (xe tới cấp {unit}, boss tới cấp {boss}). Đạn trúng mặt nó gặp; trên nóc và lên máy bay không có mức áp đảo (hơn 1 cấp, {roofMult}, là cao nhất)."),
            ["hb.pen.example"] = ("Worked example: one shot of the {shooter}'s {weapon} (penetration {pen}, {damage} damage) on a {target} (health {hp}): front armour {front}: {frontMult}, {frontHit} damage; side armour {side}: {sideMult}, {sideHit} damage.",
                "Ví dụ: một phát {weapon} của {shooter} (xuyên {pen}, sát thương {damage}) lên {target} (máu {hp}): giáp trước cấp {front}: {frontMult}, {frontHit} sát thương; giáp hông cấp {side}: {sideMult}, {sideHit} sát thương."),
            ["hb.top.title"] = ("Top attack", "Đánh nóc"),
            ["hb.top"] = ("A top-attack round strikes the roof armour, the thinnest face (everything lobbed or dropped does too). For example: {examples}.",
                "Đạn đánh nóc trúng giáp nóc, mặt mỏng nhất (mọi thứ bắn cầu vồng hay thả xuống cũng vậy). Ví dụ: {examples}."),
            ["hb.thermo.title"] = ("Thermobaric", "Nhiệt áp"),
            ["hb.thermo"] = ("A thermobaric high-explosive round does {thermo} on structures instead of high explosive's {he}: it replaces the structure multiplier, never adds to it. For example: {examples}.",
                "Đạn nổ mạnh nhiệt áp gây {thermo} lên công trình thay cho {he} của nổ mạnh: thay hệ số công trình, không nhân thêm. Ví dụ: {examples}."),
            ["hb.blast.title"] = ("Blast: core and edge", "Nổ lan: lõi và rìa"),
            ["hb.blast"] = ("A two-layer blast does full damage in its core and a share at its edge: the {weapon}, core {core} m, edge {edge} m at {share}.",
                "Vụ nổ hai lớp gây đủ sát thương ở lõi và một phần ở rìa: {weapon}, lõi {core} m, rìa {edge} m còn {share}."),
            ["hb.blast.plain"] = ("A blast does full damage at its centre and less towards its edge.", "Vụ nổ gây đủ sát thương ở tâm và giảm dần ra rìa."),
            ["hb.guided.title"] = ("Guided", "Dẫn đường"),
            ["hb.guided"] = ("A guided round (missile, drone, guided bomb or shell) follows its target; protection systems can shoot it down and flares can draw off those aimed at aircraft. For example: {examples}.",
                "Đạn dẫn đường (tên lửa, drone, bom hay đạn pháo dẫn đường) bám mục tiêu; hệ thống tự vệ có thể bắn hạ, pháo sáng có thể đánh lừa loại nhắm máy bay. Ví dụ: {examples}."),
            ["hb.airburst.title"] = ("Airburst", "Nổ trên không"),
            ["hb.airburst"] = ("Fragmentation rounds burst in the air: {air} against aircraft, {ground} on the ground. For example: {examples}.",
                "Đạn mảnh nổ trên không: {air} lên máy bay, {ground} lên mặt đất. Ví dụ: {examples}."),
            ["hb.alt.title"] = ("Second rounds", "Đạn thay thế"),
            ["hb.alt"] = ("A gun with a second round switches on its own when its target suits that round; a loaded round stays in at least {hold} s, and a switch takes the round's own time, else the magazine change or the cooldown, {min} s at least (the gun is silent meanwhile).",
                "Súng có đạn thay thế tự đổi khi mục tiêu hợp loại đạn đó; đạn đã nạp giữ ít nhất {hold} s, mỗi lần đổi mất thời gian riêng của loại đạn, nếu không thì thời gian thay băng hoặc hồi chiêu, ít nhất {min} s (súng im trong lúc đổi)."),
            ["hb.alt.example"] = ("For example: the {gun} loads its {round} in {seconds} s.", "Ví dụ: {gun} nạp {round} trong {seconds} s."),
            ["hb.minrange.title"] = ("Minimum range", "Tầm tối thiểu"),
            ["hb.minrange"] = ("Artillery and some missiles cannot fire at what is too close: {examples}.", "Pháo binh và một số tên lửa không bắn được mục tiêu quá gần: {examples}."),
            ["hb.def.title"] = ("What stops which rounds", "Hệ phòng vệ chặn loại đạn nào"),
            ["hb.def.era"] = ("Reactive armour cuts a shaped charge's damage by up to {cap}; a tandem warhead goes through; nothing else is cut.",
                "Giáp phản ứng nổ giảm tới {cap} sát thương nổ lõm; đầu nổ kép xuyên qua; loại khác không bị giảm."),
            ["hb.def.cage"] = ("A cage takes shaped charges on rockets, missiles and drones; kinetic rounds and thermobaric blasts go through.",
                "Lồng chắn đỡ nổ lõm của rốc-két, tên lửa và drone; đạn động năng và nổ nhiệt áp đi qua."),
            ["hb.def.selfaps"] = ("A vehicle's own active protection (SELF_APS) takes guided missiles, drones and direct-fire rockets only: never a tank's shell, bullets or beams.",
                "Hệ tự vệ chủ động của xe (SELF_APS) chỉ chặn tên lửa dẫn đường, drone và rốc-két bắn thẳng: không chặn đạn pháo xe tăng, đạn súng hay tia năng lượng."),
            ["hb.def.pd"] = ("Point defence (POINT_DEFENSE: the C-RAM, the lasers, a Shield HQ's dome) takes missiles, drones, rockets and a share of the artillery shells (C-RAM {cram}, laser {laser}), never a tank's shell, bullets or beams. Each round is offered to one system only, the nearest that can take it.",
                "Phòng thủ điểm (POINT_DEFENSE: C-RAM, la-de, vòm của nhà chính Lá chắn) chặn tên lửa, drone, rốc-két và một phần đạn pháo binh (C-RAM {cram}, la-de {laser}); không chặn đạn pháo xe tăng, đạn súng hay tia năng lượng. Mỗi viên đạn chỉ một hệ nhận, hệ gần nhất chặn được."),
            ["hb.def.flares"] = ("Flares draw off guided missiles aimed at aircraft.", "Pháo sáng đánh lừa tên lửa dẫn đường nhắm máy bay."),
            ["hb.def.smoke"] = ("Smoke hides what is in it and blinds point-defence lasers.", "Khói che mục tiêu bên trong và làm mù la-de phòng thủ điểm."),
            ["hb.def.jam"] = ("Jamming scatters drones and guided fire called into its bubble.", "Gây nhiễu làm tản drone và hỏa lực dẫn đường gọi vào vùng nhiễu."),
            ["hb.def.shield"] = ("A shield dome absorbs every hit but energy until it breaks; a tower's own shield stops only the rounds aimed at the tower.",
                "Vòm khiên hấp thụ mọi đòn trừ năng lượng tới khi vỡ; khiên riêng của tháp chỉ đỡ đạn nhắm vào tháp."),
            ["hb.struct.title"] = ("What to hit structures with", "Đánh công trình bằng gì"),
            ["hb.struct.thermo"] = ("Thermobaric high explosive", "Nổ mạnh nhiệt áp"),
            ["hb.struct"] = ("High explosive ({he}), thermobaric ({thermo}), fire ({fire}), artillery, bombs and a gun's high-explosive second round break structures.",
                "Nổ mạnh ({he}), nhiệt áp ({thermo}), lửa ({fire}), pháo binh, bom và đạn nổ mạnh thay thế của súng phá công trình."),
            ["hb.struct.weak"] = ("Shaped charges ({shaped}) and kinetic rounds ({kinetic}) do little to structures; fragmentation ({frag}) almost nothing.",
                "Nổ lõm ({shaped}) và động năng ({kinetic}) kém hiệu quả lên công trình; mảnh ({frag}) gần như vô hiệu."),
            ["hb.walls.title"] = ("Walls and wall breakers", "Tường và xe phá tường"),
            ["hb.walls"] = ("Wall breakers ({units}) do {mult} to walls (not to towers or the HQ).", "Xe phá tường ({units}) gây {mult} lên tường (không lên tháp hay nhà chính)."),
            ["hb.tiers.title"] = ("Calibre tiers T0-T5", "Bậc cỡ nòng T0–T5"),
            ["hb.tiers.tier"] = ("Tier", "Bậc"),
            ["hb.tiers.families"] = ("Families", "Họ vũ khí"),
            ["hb.tiers.look"] = ("Shot, blast and sound", "Phát bắn, vụ nổ và tiếng"),
            ["hb.tiers.t0"] = ("Small arms: a thin flash and a short crack.", "Súng nhỏ: chớp mảnh, tiếng nổ giòn ngắn."),
            ["hb.tiers.t1"] = ("Autocannon: a small flash and thin smoke; many guns at once are heard as one firefight.", "Pháo tự động: chớp nhỏ, khói mỏng; nhiều súng cùng bắn nghe thành một trận đấu súng."),
            ["hb.tiers.t2"] = ("Medium guns and light rockets: a medium flash, a small hot fireball, dust and earth thrown up.", "Pháo vừa và rocket nhẹ: chớp vừa, quả cầu lửa nhỏ, bụi và đất tung lên."),
            ["hb.tiers.t3"] = ("Heavy guns: a big flash and muzzle fireball, long slow smoke, a dust column; the hull rocks back.", "Pháo nặng: chớp lớn, cầu lửa đầu nòng, khói dài và chậm, cột bụi; thân xe giật lùi."),
            ["hb.tiers.t4"] = ("Very heavy guns, Smerch, 400 kg bombs: a very big flash, a rolling fireball, a shockwave on the blast's edge, a short camera shake.", "Pháo rất nặng, Smerch, bom 400 kg: chớp rất lớn, cầu lửa cuộn, sóng xung kích trên mép vụ nổ, máy quay rung ngắn."),
            ["hb.tiers.t5"] = ("Super weapons: a flash that lights the scene, a small mushroom cloud, rings on the core then the edge, the strongest shake.", "Siêu vũ khí: chớp sáng cả cảnh, đám mây hình nấm nhỏ, vòng trên lõi rồi trên mép, rung mạnh nhất."),
            ["hb.tiers"] = ("A round's tier comes from its family: the bigger it is, the harder each shot hits and the bigger its blast, look and sound, paid for with a longer reload. The rings on the ground are the real blast: the edge, with the core inside.", "Bậc của một viên đạn lấy theo họ của nó: càng to thì mỗi phát càng mạnh, nổ, hình và tiếng càng lớn, bù bằng thời gian nạp dài hơn. Vòng trên mặt đất là đúng vùng nổ thật: mép ngoài, lõi ở trong."),
            ["hb.tiers.warn"] = ("A boss's T4 and T5 rounds warn where they fall for at least 0.5 s + core / 4.5 m/s (T4 at least {floor} s), long enough to drive out of the blast.", "Đạn T4 và T5 của boss báo chỗ rơi ít nhất 0,5 s + lõi / 4,5 m/s (T4 ít nhất {floor} s), đủ để chạy ra khỏi vụ nổ."),
            ["hb.chip.top"] = ("TOP ATTACK", "ĐÁNH NÓC"),
            ["hb.chip.alt"] = ("SECOND ROUND", "ĐẠN THAY THẾ"),
            ["hb.chip.airburst"] = ("AIRBURST", "NỔ TRÊN KHÔNG"),
            ["hb.chip.guided"] = ("GUIDED", "DẪN ĐƯỜNG"),
            ["hb.chip.structure"] = ("STRUCTURE BREAKER", "PHÁ CÔNG TRÌNH"),
            ["hb.chip.wall"] = ("WALL BREAKER", "PHÁ TƯỜNG"),

            // The HQ's damage marks (50 %: a warning only, no loss of function; 25 %: a warning and one free rebuild).
            ["alert.hq.half.ours"] = ("Our HQ is at half strength", "Nhà chính của ta còn một nửa máu"),
            ["alert.hq.half.theirs"] = ("The enemy HQ is at half strength", "Nhà chính địch còn một nửa máu"),
            ["alert.hq.quarter.ours"] = ("Our HQ is badly hit: a tower is flown back in", "Nhà chính của ta bị đánh nặng: một tháp được thả lại"),
            ["alert.hq.quarter.theirs"] = ("The enemy HQ is badly hit", "Nhà chính địch bị đánh nặng"),
            ["alert.hq.garrison.ours"] = ("The garrison turns out", "Quân đồn trú xuất kích"),
            ["alert.hq.garrison.theirs"] = ("Enemy garrison turning out", "Quân đồn trú địch xuất kích"),
            ["alert.hq.dome.ours"] = ("Emergency dome up", "Vòm khiên khẩn cấp đã bật"),
            ["alert.hq.dome.theirs"] = ("Enemy emergency dome up", "Địch bật vòm khiên khẩn cấp"),
            // ---------------------------------------------------------------- L3: walls
            ["wall.line.1"] = ("Outer wall", "Tường ngoài"),
            ["wall.line.2"] = ("Inner wall", "Tường trong"),
            ["wall.line.3"] = ("Keep wall", "Tường thành trong"),
            ["wall.type.none"] = ("none", "không"),
            ["wall.type.hesco"] = ("HESCO", "HESCO"),
            ["wall.type.t_wall"] = ("T-wall", "Tường chữ T"),
            ["wall.type.gun_wall"] = ("Gun wall", "Tường gắn súng"),
            ["camp.wall"] = ("{line}: {type} · tap to change", "{line}: {type} · chạm để đổi"),
            ["wall.type.none.info"] = ("No wall on this line: the quickest way in and out.", "Không có tường ở tuyến này: ra vào nhanh nhất."),
            ["wall.type.hesco.info"] = ("HESCO gabions: durability {durability}, a wide gate (your own vehicles barely slowed).",
                "Rọ HESCO: độ bền {durability}, cổng rộng (quân ta gần như không bị cản đường)."),
            ["wall.type.t_wall.info"] = ("Concrete T-walls: durability {durability}, a narrower gate (your reinforcements take the longer way).",
                "Tường bê tông chữ T: độ bền {durability}, cổng hẹp hơn (đường viện quân của ta dài hơn)."),
            ["wall.type.gun_wall.info"] = ("Gun wall: durability {durability}; one of your small towers stands on it, taking one of the base's small slots.",
                "Tường gắn súng: độ bền {durability}; một tháp nhỏ của bạn đứng trên tường, dùng một ô nhỏ có sẵn của căn cứ."),
            ["unit.wall_hesco"] = ("HESCO wall", "Tường HESCO"),
            ["unit.wall_t"] = ("T-wall", "Tường chữ T"),
            ["unit.wall_gun"] = ("Gun wall", "Tường gắn súng"),
            ["short.wall_hesco"] = ("HESCO", "HESCO"),
            ["short.wall_t"] = ("T-wall", "Tường T"),
            ["short.wall_gun"] = ("Gun wall", "Tường súng"),
            ["note.wall_hesco"] = ("A segment of earth-filled gabions. Rubble when it falls: passable, 20% slower. Wall breakers hit it 1.5 times as hard.",
                "Một đoạn rọ đất. Đổ thành gạch vụn: đi qua được, chậm 20%. Xe phá tường đánh mạnh gấp 1,5 lần."),
            ["note.wall_t"] = ("A segment of precast concrete T-walls, 1.6 times as tough as HESCO. Rubble when it falls: passable, 20% slower.",
                "Một đoạn tường bê tông đúc sẵn chữ T, bền gấp 1,6 lần HESCO. Đổ thành gạch vụn: đi qua được, chậm 20%."),
            ["note.wall_gun"] = ("A wall segment with a firing platform for a small tower (1.2 times as tough as HESCO). Its tower falls with it.",
                "Một đoạn tường có bệ cho một tháp nhỏ (bền gấp 1,2 lần HESCO). Tường đổ thì tháp đổ theo."),
            // ---------------------------------------------------------------- L7: Showdown
            ["mode.showdown"] = ("Showdown", "Đối công"),
            ["mode.showdownSub"] = ("Base against base: destroy the enemy HQ", "Căn cứ đối căn cứ: phá nhà chính đối phương"),
            ["mode.showdown.kicker"] = ("SHOWDOWN", "ĐỐI CÔNG"),
            ["mode.showdown.sub"] = ("Destroy the enemy HQ within 12 minutes", "Phá nhà chính đối phương trong 12 phút"),
            ["mode.showdown.toast"] = ("Break their outer line, then their HQ. Until a base is breached its HQ shrugs off long-range fire. Minute 6: income x1.5; minute 10: no more rebuilt towers.",
                "Phá tuyến ngoài rồi tới nhà chính. Khi căn cứ chưa bị chọc thủng, nhà chính chịu ít sát thương từ xa. Phút 6: thu nhập x1,5; phút 10: không xây lại tháp."),
            ["stat.hq"] = ("HQ health %", "Máu nhà chính %"),
            ["stat.suddenDeath"] = ("Sudden-death damage", "Sát thương đột tử"),
        };
    }
}
