// Generated by Tools/campaign/build_campaign.py: edit the script, not this file.
using System.Collections.Generic;

namespace MachineBrigade.Game.Hud
{
    /// <summary>The story campaign's texts (missions, radio, stages, choices, chapters, the dossier), English and Vietnamese.</summary>
    public static class CampaignText
    {
        public static readonly Dictionary<string, (string en, string vi)> Table = new()
        {
        };
    }
}
