using System.Collections.Generic;
using MachineBrigade.Sim.Commands;
using UnityEngine;

namespace MachineBrigade.Game.Hud
{
    /// <summary>
    /// Player-facing text in English and Vietnamese. The language follows the device, like
    /// Sticky-Wall. A settings override and the Unity Localization tables come with the menus.
    /// </summary>
    public static class Strings
    {
        private static readonly Dictionary<string, (string en, string vi)> Table = new()
        {
            ["brand.top"] = ("MACHINE", "MACHINE"),
            ["brand.bottom"] = ("B R I G A D E", "B R I G A D E"),
            ["stat.allies"] = ("ALLIES", "QUÂN TA"),
            ["stat.enemies"] = ("ENEMIES", "ĐỊCH"),
            ["stat.wave"] = ("WAVE", "ĐỢT"),
            ["stat.next"] = ("NEXT WAVE", "ĐỢT SAU"),
            ["mission.kicker"] = ("OPERATION 01  /  SANDBOX", "CHIẾN DỊCH 01  /  SA BÀN"),
            ["mission.title"] = ("Ashfield.", "Ashfield."),
            ["mission.sub"] = ("HOLD THE LINE  ·  WAVES INCOMING", "GIỮ VỮNG TRẬN ĐỊA  ·  ĐỊCH ĐANG ĐẾN"),
            ["panel.selection"] = ("SELECTION", "ĐANG CHỌN"),
            ["panel.selected"] = ("{0} SELECTED", "{0} XE"),
            ["panel.none"] = ("No vehicles selected", "Chưa chọn xe"),
            ["panel.noneHint"] = ("Tap a vehicle, or use Army", "Chạm vào xe, hoặc bấm Quân đội"),
            ["panel.mixed"] = ("Battle group", "Cụm chiến đấu"),
            ["panel.hp"] = ("{0} / {1} HP", "{0} / {1} HP"),
            ["cmd.attackMove"] = ("Attack-move", "Tiến công"),
            ["cmd.stop"] = ("Stop", "Dừng"),
            ["cmd.retreat"] = ("Retreat", "Rút lui"),
            ["cmd.reinforce"] = ("Reinforce", "Tiếp viện"),
            ["cmd.reinforceReady"] = ("+2 vehicles", "+2 xe"),
            ["cmd.reinforceWait"] = ("Ready in {0}s", "Sẵn sàng sau {0}s"),
            ["tool.army"] = ("Army", "Quân đội"),
            ["tool.box"] = ("Box", "Quét chọn"),
            ["hint"] = ("Tap to select  ·  Drag to pan  ·  Pinch to zoom", "Chạm để chọn  ·  Kéo để di chuyển  ·  Chụm để thu phóng"),
            ["hint.attackMove"] = ("Tap the ground to attack-move", "Chạm xuống đất để tiến công"),
            ["hint.box"] = ("Drag to box-select your vehicles", "Kéo để quét chọn xe"),
            ["toast.reinforceWait"] = ("Reinforcements are not ready", "Tiếp viện chưa sẵn sàng"),
            ["toast.start"] = ("Enemy armour sighted. Select your vehicles and attack.", "Phát hiện thiết giáp địch. Chọn xe và tấn công."),
            ["toast.wave"] = ("Wave {0} incoming", "Đợt {0} đang tới"),
            ["err.NoUnits"] = ("Select your vehicles first", "Hãy chọn xe trước"),
            ["err.InvalidTarget"] = ("That can't be attacked", "Không thể tấn công mục tiêu này"),
            ["err.TargetNotVisible"] = ("Target not visible", "Không nhìn thấy mục tiêu"),
            ["err.OutOfBounds"] = ("Outside the battlefield", "Ngoài chiến trường"),
            ["err.InvalidPoint"] = ("Invalid destination", "Điểm đến không hợp lệ"),
            ["err.NoRallyPoint"] = ("No rally point", "Không có điểm tập kết"),
            ["err.MatchOver"] = ("The match is over", "Trận đấu đã kết thúc"),
            ["unit.scout_jeep"] = ("Scout jeep", "Xe trinh sát"),
            ["unit.light_tank"] = ("Light tank", "Tăng hạng nhẹ"),
            ["unit.main_battle_tank"] = ("Main battle tank", "Tăng chủ lực"),
            ["unit.artillery"] = ("Artillery", "Pháo tự hành"),
            ["unit.apc"] = ("APC", "Xe chở quân"),
            ["unit.flame_tank"] = ("Flame tank", "Tăng phun lửa"),
            ["unit.mlrs"] = ("Rocket launcher", "Pháo phản lực"),
            ["unit.aa_vehicle"] = ("Anti-air", "Xe phòng không"),
            ["unit.attack_helicopter"] = ("Attack helicopter", "Trực thăng tấn công"),
            ["unit.armored_car"] = ("Armored car", "Xe bọc thép"),
            ["unit.tank_destroyer"] = ("Tank destroyer", "Pháo chống tăng"),
            ["unit.heavy_tank"] = ("Heavy tank", "Tăng hạng nặng"),
            ["unit.sam_launcher"] = ("SAM launcher", "Tên lửa phòng không"),
            ["unit.mortar_carrier"] = ("Mortar carrier", "Xe súng cối"),
            ["unit.rocket_technical"] = ("Rocket technical", "Bán tải rocket"),
            ["unit.gunship_heli"] = ("Heavy gunship", "Trực thăng hạng nặng"),
            ["unit.scout_heli"] = ("Scout helicopter", "Trực thăng trinh sát"),
            ["unit.attack_jet"] = ("Attack jet", "Máy bay cường kích"),
            ["unit.strike_drone"] = ("Strike drone", "UAV tấn công"),
            ["support.artillery_barrage"] = ("Barrage", "Pháo kích"),
            ["support.airstrike"] = ("Airstrike", "Không kích"),
            ["support.cruise_missile"] = ("Cruise missile", "Tên lửa hành trình"),
            ["support.smoke_screen"] = ("Smoke", "Màn khói"),
            ["support.repair_drop"] = ("Repair", "Sửa chữa"),
            ["stat.tickets"] = ("TICKETS", "ĐIỂM"),
            ["stat.cp"] = ("CP", "CP"),
            ["stat.army"] = ("ARMY {0}/{1}", "QUÂN {0}/{1}"),
            ["point.west"] = ("A", "A"),
            ["point.town"] = ("B", "B"),
            ["point.east"] = ("C", "C"),
            ["mission.conquest.kicker"] = ("OPERATION 02  /  CONQUEST", "CHIẾN DỊCH 02  /  GIỮ CỨ ĐIỂM"),
            ["mission.conquest.sub"] = ("HOLD MORE POINTS THAN THE ENEMY", "GIỮ NHIỀU CỨ ĐIỂM HƠN ĐỊCH"),
            ["mission.survival.kicker"] = ("OPERATION 01  /  SURVIVAL", "CHIẾN DỊCH 01  /  SINH TỒN"),
            ["toast.conquestStart"] = ("Capture the points. Buy vehicles and strikes from the deck below.", "Chiếm cứ điểm. Mua xe và yểm trợ ở thanh bên dưới."),
            ["toast.deployed"] = ("{0} on the way", "{0} đang tới"),
            ["toast.captured"] = ("Point {0} captured", "Đã chiếm cứ điểm {0}"),
            ["toast.lost"] = ("Point {0} lost", "Mất cứ điểm {0}"),
            ["toast.enemyStrike"] = ("Enemy {0} incoming!", "Địch gọi {0}!"),
            ["toast.airDefence"] = ("Enemy aircraft: bring anti-air", "Máy bay địch: hãy dùng xe phòng không"),
            ["target.hint"] = ("Tap the battlefield to call {0}", "Chạm vào chiến trường để gọi {0}"),
            ["target.cancel"] = ("Cancel", "Hủy"),
            ["err.UnknownCard"] = ("Not in your deck", "Không có trong bộ bài"),
            ["err.NotEnoughCp"] = ("Not enough CP", "Không đủ CP"),
            ["err.ArmyAtCapacity"] = ("Army at capacity", "Quân đã đầy"),
            ["err.OnCooldown"] = ("Not ready yet", "Chưa sẵn sàng"),
            ["err.NotAvailable"] = ("Not available in this mode", "Không dùng được ở chế độ này"),
            ["result.victory"] = ("VICTORY", "CHIẾN THẮNG"),
            ["result.defeat"] = ("DEFEAT", "THẤT BẠI"),
            ["result.draw"] = ("DRAW", "HÒA"),
            ["result.over"] = ("THE LINE HAS FALLEN", "TRẬN ĐỊA ĐÃ THẤT THỦ"),
            ["result.kills"] = ("Destroyed", "Tiêu diệt"),
            ["result.losses"] = ("Lost", "Tổn thất"),
            ["result.time"] = ("Time", "Thời gian"),
            ["result.waves"] = ("Waves held", "Số đợt trụ được"),
            ["result.again"] = ("Play again", "Chơi lại"),
            ["result.menu"] = ("Main menu", "Về menu"),
            ["menu.play"] = ("Deploy", "Xuất kích"),
            ["menu.mode"] = ("MODE", "CHẾ ĐỘ"),
            ["menu.conquest"] = ("Conquest", "Giữ cứ điểm"),
            ["menu.conquestSub"] = ("Take and hold 3 objectives", "Chiếm và giữ 3 cứ điểm"),
            ["menu.survival"] = ("Survival", "Sinh tồn"),
            ["menu.survivalSub"] = ("Hold out against endless waves", "Trụ vững trước các đợt tấn công"),
            ["menu.difficulty"] = ("DIFFICULTY", "ĐỘ KHÓ"),
            ["menu.easy"] = ("Easy", "Dễ"),
            ["menu.normal"] = ("Normal", "Thường"),
            ["menu.hard"] = ("Hard", "Khó"),
            ["menu.weather"] = ("WEATHER", "THỜI TIẾT"),
            ["menu.clear"] = ("Clear", "Nắng"),
            ["menu.overcast"] = ("Overcast", "Nhiều mây"),
            ["menu.rain"] = ("Rain", "Mưa"),
            ["menu.storm"] = ("Storm", "Bão"),
            ["menu.random"] = ("Random", "Ngẫu nhiên"),
            ["menu.deck"] = ("Deck", "Bộ bài"),
            ["menu.deckTitle"] = ("YOUR DECK  ·  {0}/{1} VEHICLES  ·  {2}/{3} SUPPORT", "BỘ BÀI  ·  {0}/{1} XE  ·  {2}/{3} YỂM TRỢ"),
            ["menu.settings"] = ("Settings", "Cài đặt"),
            ["menu.back"] = ("Back", "Quay lại"),
            ["menu.tagline"] = ("Command the armour. Break the line.", "Chỉ huy thiết giáp. Phá vỡ phòng tuyến."),
            ["settings.volume"] = ("Sound volume", "Âm lượng"),
            ["settings.quality"] = ("Graphics", "Đồ họa"),
            ["settings.high"] = ("High", "Cao"),
            ["settings.medium"] = ("Medium", "Vừa"),
            ["settings.low"] = ("Low", "Thấp"),
            ["settings.eco"] = ("Eco", "Tiết kiệm"),
            ["settings.autoTier"] = ("Auto ({0})", "Tự động ({0})"),
            ["settings.section.graphics"] = ("Graphics", "Đồ họa"),
            ["settings.section.game"] = ("Gameplay", "Chơi"),
            ["settings.section.sound"] = ("Sound and language", "Âm thanh và ngôn ngữ"),
            ["settings.preset"] = ("Quality preset", "Mức đồ họa"),
            ["settings.custom"] = ("Custom", "Tùy chỉnh"),
            ["settings.shadows"] = ("Shadows", "Đổ bóng"),
            ["settings.resolution"] = ("Resolution", "Độ phân giải"),
            ["settings.aa"] = ("Anti-aliasing", "Khử răng cưa"),
            ["settings.framerate"] = ("Frame rate cap", "Giới hạn khung hình"),
            ["settings.bloom"] = ("Glow", "Phát sáng"),
            ["settings.battery"] = ("Battery saver", "Tiết kiệm pin"),
            ["settings.brightness"] = ("Brightness", "Độ sáng"),
            ["settings.scenery"] = ("Scenery", "Cảnh vật"),
            ["settings.sparse"] = ("Sparse", "Thưa"),
            ["settings.dense"] = ("Dense", "Dày"),
            ["settings.effects"] = ("Effect detail", "Chi tiết hiệu ứng"),
            ["settings.balanced"] = ("Balanced", "Cân bằng"),
            ["settings.max"] = ("Maximum", "Tối đa"),
            ["settings.shake"] = ("Screen shake", "Rung màn hình"),
            ["settings.full"] = ("Full", "Đầy đủ"),
            ["settings.camera"] = ("Camera speed", "Tốc độ camera"),
            ["settings.cinematic"] = ("Cinematic moments", "Khoảnh khắc điện ảnh"),
            ["settings.slow"] = ("Slow", "Chậm"),
            ["settings.normal"] = ("Normal", "Thường"),
            ["settings.fast"] = ("Fast", "Nhanh"),
            ["settings.ui"] = ("Interface size", "Cỡ giao diện"),
            ["settings.small"] = ("Small", "Nhỏ"),
            ["settings.large"] = ("Large", "Lớn"),
            ["settings.fps"] = ("Show FPS", "Hiện FPS"),
            ["settings.language"] = ("Language", "Ngôn ngữ"),
            ["settings.auto"] = ("Auto", "Tự động"),
            ["settings.on"] = ("On", "Bật"),
            ["settings.off"] = ("Off", "Tắt"),
            ["pause.title"] = ("PAUSED", "TẠM DỪNG"),
            ["panel.commander"] = ("COMMANDER", "CHỈ HUY"),
            ["stance.attack"] = ("Attack", "Tấn công"),
            ["stance.defend"] = ("Defend", "Phòng thủ"),
            ["auto.deploy"] = ("Auto buy", "Tự mua xe"),
            ["auto.strike"] = ("Auto support", "Tự yểm trợ"),
            ["toast.focus"] = ("Army converging on point {0}", "Quân ta dồn về cứ điểm {0}"),
            ["toast.focusClear"] = ("The commander picks targets", "Chỉ huy tự chọn mục tiêu"),
            ["toast.attack"] = ("Stance: attack", "Thế trận: tấn công"),
            ["toast.defend"] = ("Stance: defend", "Thế trận: phòng thủ"),
            ["hint.auto"] = ("Your army fights on its own  ·  Tap A B C to point it  ·  Tap a vehicle to take control",
                "Quân ta tự chiến đấu  ·  Chạm A B C để chỉ hướng  ·  Chạm xe để điều khiển tay"),
            ["hint.autoSurvival"] = ("Your army fights on its own  ·  Tap a vehicle to take control",
                "Quân ta tự chiến đấu  ·  Chạm xe để điều khiển tay"),
            ["menu.map"] = ("Battlefield", "Chiến trường"),
            ["menu.snow"] = ("Snow", "Tuyết"),
            ["menu.sandstorm"] = ("Sandstorm", "Bão cát"),
            ["menu.fog"] = ("Fog", "Sương mù"),
            ["menu.night"] = ("Night", "Ban đêm"),
            ["map.ashfield"] = ("Ashfield", "Ashfield"),
            ["map.ashfield.sub"] = ("Town · Temperate", "Thị trấn · Ôn đới"),
            ["map.dunebreak"] = ("Dunebreak", "Dunebreak"),
            ["map.dunebreak.sub"] = ("Refinery · Desert", "Lọc dầu · Sa mạc"),
            ["map.frostpeak"] = ("Frostpeak", "Frostpeak"),
            ["map.frostpeak.sub"] = ("Village · Snow", "Làng núi · Tuyết"),
            ["map.ironport"] = ("Ironport", "Ironport"),
            ["map.ironport.sub"] = ("Docks · Harbour", "Cảng · Công nghiệp"),
            ["map.redrock"] = ("Redrock Canyon", "Hẻm Đá Đỏ"),
            ["map.redrock.sub"] = ("Canyon · Desert", "Hẻm núi · Sa mạc"),
            ["map.whiteout"] = ("Whiteout Pass", "Đèo Bão Tuyết"),
            ["map.whiteout.sub"] = ("Forest pass · Snow", "Đèo rừng · Tuyết"),
            ["map.greenvale"] = ("Greenvale", "Lũng Xanh"),
            ["map.greenvale.sub"] = ("Farmland · Temperate", "Đồng quê · Ôn đới"),
            ["map.rustyard"] = ("Rust Yard", "Bãi Sắt Gỉ"),
            ["map.rustyard.sub"] = ("Industry · Ruins", "Khu công nghiệp · Đổ nát"),
            ["pause.resume"] = ("Resume", "Tiếp tục"),
            // Quick battle modes.
            ["mode.conquest"] = ("Conquest", "Giữ cứ điểm"),
            ["mode.conquestSub"] = ("Hold more objectives", "Giữ nhiều cứ điểm hơn"),
            ["mode.survival"] = ("Survival", "Sinh tồn"),
            ["mode.survivalSub"] = ("Endless enemy waves", "Các đợt địch bất tận"),
            ["mode.deathmatch"] = ("Deathmatch", "Tử chiến"),
            ["mode.deathmatchSub"] = ("First to 100 kills", "Hạ 100 xe địch trước"),
            ["mode.deathmatch.kicker"] = ("DEATHMATCH", "TỬ CHIẾN"),
            ["mode.deathmatch.sub"] = ("First side to {0} kills wins", "Bên nào hạ {0} xe trước sẽ thắng"),
            ["mode.deathmatch.toast"] = ("No objectives. Destroy {0} enemy vehicles.", "Không có cứ điểm. Hạ {0} xe địch."),
            ["mode.hill"] = ("King of the Hill", "Vua đồi"),
            ["mode.hillSub"] = ("Hold the centre alone", "Một mình giữ trung tâm"),
            ["mode.hill.kicker"] = ("KING OF THE HILL", "VUA ĐỒI"),
            ["mode.hill.sub"] = ("Hold the hill alone to score", "Một mình giữ ngọn đồi để ghi điểm"),
            ["mode.hill.toast"] = ("Take point B and keep the enemy off it.", "Chiếm cứ điểm B và không cho địch lại gần."),
            ["mode.assault"] = ("Assault", "Công phá"),
            ["mode.assaultSub"] = ("Take every objective in time", "Chiếm hết cứ điểm kịp giờ"),
            ["mode.assault.kicker"] = ("ASSAULT", "CÔNG PHÁ"),
            ["mode.assault.sub"] = ("The enemy is dug in on every objective", "Địch cố thủ ở mọi cứ điểm"),
            ["mode.assault.toast"] = ("Capture A, B and C before time runs out.", "Chiếm A, B và C trước khi hết giờ."),
            ["mode.campaign"] = ("Campaign", "Chiến dịch"),
            ["menu.quick"] = ("Quick battle", "Trận nhanh"),
            ["menu.shop"] = ("Shop", "Cửa hàng"),
            ["profile.rank"] = ("Rank {0}", "Cấp {0}"),
            ["campaign.next"] = ("Next: {0} · {1}", "Tiếp: {0} · {1}"),
            ["campaign.detailKicker"] = ("Mission {0} · {1}", "Nhiệm vụ {0} · {1}"),
            ["campaign.replayRewards"] = ("Replay reward: {0} coins", "Thưởng chơi lại: {0} coin"),
            ["deck.hint"] = ("Tap a card to add or remove it. Locked cards are won in the campaign or bought in the shop.",
                "Chạm thẻ để thêm hoặc bỏ. Thẻ khóa được mở trong chiến dịch hoặc mua ở cửa hàng."),
            ["deck.lockedMission"] = ("{0}: won in mission {1}, or unlock it now in the shop for {2} coins.",
                "{0}: mở ở nhiệm vụ {1}, hoặc mua sớm ở cửa hàng với {2} coin."),
            ["deck.lockedShop"] = ("{0}: unlock it in the shop for {1} coins.", "{0}: mua ở cửa hàng với {1} coin."),
            ["deck.lockedPremium"] = ("{0}: premium, {1} coins in the shop.", "{0}: đồ cao cấp, {1} coin ở cửa hàng."),
            ["shop.skins"] = ("Skins", "Skin"),
            ["shop.premium"] = ("Premium", "Cao cấp"),
            ["shop.unlocks"] = ("Unlock early", "Mở khóa sớm"),
            ["shop.pick"] = ("Pick an item", "Chọn một món"),
            ["shop.buy"] = ("Buy · {0}", "Mua · {0}"),
            ["shop.short"] = ("{0} coins short", "Còn thiếu {0} coin"),
            ["shop.equip"] = ("Use this skin", "Dùng skin này"),
            ["shop.equipped"] = ("In use", "Đang dùng"),
            ["shop.owned"] = ("Owned", "Đã có"),
            ["shop.bought"] = ("Bought: {0}", "Đã mua: {0}"),
            ["shop.notEnough"] = ("Not enough coins: win battles and missions, or double a reward with an ad.",
                "Chưa đủ coin: thắng trận và nhiệm vụ, hoặc xem quảng cáo để nhân đôi thưởng."),
            ["shop.soon"] = ("{0} arrives in a coming update.", "{0} sẽ có trong bản cập nhật tới."),
            ["shop.comingSoon"] = ("Coming soon", "Sắp ra mắt"),
            ["shop.fromMission"] = ("Mission {0}", "Nhiệm vụ {0}"),
            ["skin.olive"] = ("Olive", "Xanh ô liu"),
            ["skin.desert"] = ("Desert", "Sa mạc"),
            ["skin.woodland"] = ("Woodland", "Rừng rậm"),
            ["skin.arctic"] = ("Arctic", "Băng giá"),
            ["skin.urban"] = ("Urban", "Đô thị"),
            ["skin.ocean"] = ("Ocean digital", "Đại dương số"),
            ["skin.tiger"] = ("Tiger", "Hổ vằn"),
            ["skin.midnight"] = ("Midnight", "Nửa đêm"),
            ["skin.steel"] = ("Polished steel", "Thép bóng"),
            ["skin.gold"] = ("Gold", "Vàng ròng"),
            ["unit.titan_tank"] = ("Titan super tank", "Siêu tăng Titan"),
            ["unit.heavy_bomber"] = ("Heavy bomber", "Oanh tạc cơ hạng nặng"),
            ["unit.sky_gunship"] = ("Sky gunship", "Pháo đài bay"),
            ["unit.stealth_bomber"] = ("Stealth bomber", "Máy bay ném bom tàng hình"),
            ["unit.howitzer"] = ("Howitzer", "Lựu pháo tự hành"),
            ["unit.thermobaric_launcher"] = ("Thermobaric launcher", "Pháo phản lực nhiệt áp"),
            ["unit.ifv"] = ("Infantry fighting vehicle", "Xe chiến đấu bộ binh"),
            ["unit.heavy_aa"] = ("Gun-missile air defence", "Pháo tên lửa phòng không"),
            ["support.napalm_strike"] = ("Napalm strike", "Bom napalm"),
            ["support.carpet_bombing"] = ("Carpet bombing", "Ném bom rải thảm"),
            ["stat.kills"] = ("Kills", "Hạ gục"),
            ["stat.score"] = ("Score", "Điểm"),
            ["stat.taken"] = ("Objectives", "Cứ điểm"),
            // Campaign.
            ["campaign.title"] = ("Operation Steel Fire", "Chiến dịch Thép Lửa"),
            ["campaign.kicker"] = ("CAMPAIGN · MISSION {0}", "CHIẾN DỊCH · NHIỆM VỤ {0}"),
            ["campaign.progress"] = ("{0}/{1} missions · {2} stars", "{0}/{1} nhiệm vụ · {2} sao"),
            ["campaign.play"] = ("Start mission", "Bắt đầu nhiệm vụ"),
            ["campaign.locked"] = ("Win the previous mission first", "Thắng nhiệm vụ trước để mở"),
            ["campaign.rewards"] = ("Reward: {0} coins", "Thưởng: {0} coin"),
            ["campaign.unlocks"] = ("Unlocks {0}", "Mở khóa {0}"),
            ["campaign.stars"] = ("Stars: win · under {0} · lose at most {1}", "Sao: thắng · dưới {0} · mất tối đa {1} xe"),
            ["campaign.starsNoTime"] = ("Stars: win · lose at most {0}", "Sao: thắng · mất tối đa {0} xe"),
            ["goal.capture"] = ("Capture the objectives", "Chiếm các cứ điểm"),
            ["goal.hold"] = ("Hold the objective", "Giữ cứ điểm"),
            ["goal.destroy"] = ("Destroy the targets", "Phá hủy mục tiêu"),
            ["goal.escort"] = ("Escort the convoy", "Hộ tống đoàn xe"),
            ["goal.survive"] = ("Survive", "Trụ vững"),
            ["goal.boss"] = ("Destroy the boss", "Tiêu diệt trùm"),
            ["goal.intercept"] = ("Stop the armoured train", "Chặn đoàn tàu bọc thép"),
            ["mission.m01.name"] = ("Landfall", "Đổ bộ"),
            ["mission.m01.brief"] = ("Take the town and both depots from a weak garrison.", "Chiếm thị trấn và hai kho nhiên liệu từ đồn địch yếu."),
            ["mission.m02.name"] = ("Supply Run", "Đoàn xe tiếp tế"),
            ["mission.m02.brief"] = ("Get at least two supply trucks to the east depot.", "Đưa ít nhất hai xe tiếp tế tới kho phía đông."),
            ["mission.m03.name"] = ("Iron Bird", "Chim sắt"),
            ["mission.m03.brief"] = ("A giant gunship rules the sky over Ashfield. Bring it down.", "Một trực thăng khổng lồ làm chủ bầu trời Ashfield. Bắn hạ nó."),
            ["mission.m04.name"] = ("Oil and Sand", "Dầu và cát"),
            ["mission.m04.brief"] = ("Hold out at the oil field for five minutes.", "Trụ vững ở mỏ dầu trong năm phút."),
            ["mission.m05.name"] = ("Refinery Inferno", "Hỏa ngục lọc dầu"),
            ["mission.m05.brief"] = ("Blow up every tower and storage tank of the refinery.", "Cho nổ tung mọi tháp và bồn chứa của nhà máy lọc dầu."),
            ["mission.m06.name"] = ("Behemoth", "Quái vật thép"),
            ["mission.m06.brief"] = ("A land battleship crawls out of the sandstorm. Destroy it.", "Một chiến hạm mặt đất bò ra từ bão cát. Tiêu diệt nó."),
            ["mission.m07.name"] = ("Blind the Radar", "Làm mù radar"),
            ["mission.m07.brief"] = ("Destroy the radar station on the western heights.", "Phá hủy trạm radar trên cao điểm phía tây."),
            ["mission.m08.name"] = ("Village in the Fog", "Ngôi làng trong sương"),
            ["mission.m08.brief"] = ("Hold the village for five minutes against everything they send.", "Giữ ngôi làng năm phút trước mọi đợt tấn công."),
            ["mission.m09.name"] = ("Ice Fortress", "Pháo đài băng"),
            ["mission.m09.brief"] = ("A mobile fortress is grinding down the valley. Stop it.", "Một pháo đài di động đang nghiền nát thung lũng. Chặn nó lại."),
            ["mission.m10.name"] = ("Storm the Port", "Tấn công cảng"),
            ["mission.m10.brief"] = ("The enemy holds the whole port. Take all three objectives.", "Địch giữ toàn bộ cảng. Chiếm cả ba cứ điểm."),
            ["mission.m11.name"] = ("Dockside Convoy", "Đoàn xe bến cảng"),
            ["mission.m11.brief"] = ("Bring three of five trucks through the port to the docks.", "Đưa ba trong năm xe tải qua cảng tới bến."),
            ["mission.m12.name"] = ("Iron Train", "Đoàn tàu thép"),
            ["mission.m12.brief"] = ("An armoured train is heading for the docks. Destroy it before it arrives.", "Một đoàn tàu bọc thép đang lao về bến cảng. Phá hủy nó trước khi tới nơi."),
            ["unit.supply_truck"] = ("Supply truck", "Xe tiếp tế"),
            ["unit.behemoth"] = ("Behemoth", "Quái vật thép Behemoth"),
            ["unit.mobile_fortress"] = ("Ice Fortress", "Pháo đài băng"),
            ["unit.armored_train"] = ("Iron Train", "Đoàn tàu thép"),
            ["unit.mega_gunship"] = ("Iron Bird", "Chim sắt"),
            // Rewards and ads.
            ["result.double"] = ("Double coins", "Nhân đôi coin"),
            ["result.doubleSub"] = ("Watch a short ad", "Xem một quảng cáo ngắn"),
            ["result.next"] = ("Next mission", "Nhiệm vụ tiếp"),
            ["result.unlocked"] = ("Unlocked: {0}", "Đã mở khóa: {0}"),
            ["ad.title"] = ("ADVERTISEMENT", "QUẢNG CÁO"),
            ["ad.body"] = ("Test ad: a real ad network is connected before release.", "Quảng cáo thử nghiệm: mạng quảng cáo thật sẽ được gắn trước khi phát hành."),
            ["ad.claim"] = ("Claim double coins", "Nhận gấp đôi coin"),
            ["ad.close"] = ("Close", "Đóng"),
        };

        public static bool Vietnamese { get; set; } = Application.systemLanguage == SystemLanguage.Vietnamese;

        public static string Get(string key) =>
            Table.TryGetValue(key, out var text) ? (Vietnamese ? text.vi : text.en) : key;

        public static string Format(string key, params object[] args) => string.Format(Get(key), args);

        public static string Error(CommandError error) => Get("err." + error);

        public static string Unit(string defId) => Get("unit." + defId);

        public static string Support(string defId) => Get("support." + defId);

        /// <summary>Vehicle or support card name.</summary>
        public static string Card(string defId) => Table.ContainsKey("unit." + defId) ? Unit(defId) : Support(defId);
    }
}
