using System.Collections.Generic;

namespace MachineBrigade.Game.Hud
{
    /// <summary>
    /// The words of the generated unit lines (prompt 13 G, <see cref="UnitLines"/>): ammunition and
    /// behaviour, English and Vietnamese. The numbers come from the data.
    /// </summary>
    public static class UnitText
    {
        public static readonly Dictionary<string, (string en, string vi)> Table = new()
        {
            ["detail.behaviour"] = ("Behaviour", "Hành vi"),
            ["detail.more"] = ("More", "Xem thêm"),
            ["detail.less"] = ("Less", "Thu gọn"),

            ["settings.ammoIcons"] = ("Ammo icons", "Biểu tượng đạn"),
            ["settings.ammoIcons.all"] = ("All units", "Mọi đơn vị"),
            ["settings.ammoIcons.air"] = ("Aircraft only", "Chỉ máy bay"),
            ["hud.stores.bombs"] = ("Bombs {left}/{full}", "Bom {left}/{full}"),
            ["hud.stores.missiles"] = ("Missiles {left}/{full}", "Tên lửa {left}/{full}"),
            ["hud.stores.rockets"] = ("Rockets {left}/{full}", "Rốc-két {left}/{full}"),
            ["hud.stores.rounds"] = ("Ammo {left}/{full}", "Đạn {left}/{full}"),
            ["hud.kit.missiles"] = ("Missiles {left}/{full}", "Tên lửa {left}/{full}"),
            ["hud.kit.flares"] = ("Flares {left}/{full}", "Pháo sáng {left}/{full}"),

            ["detail.ammoIcons"] = ("Ammo icons", "Biểu tượng đạn"),
            ["icons.low"] = ("Yellow magazine: running low (under 20%)", "Băng đạn vàng: sắp hết đạn (dưới 20%)"),
            ["icons.empty"] = ("Red magazine, blinking: empty", "Băng đạn đỏ nhấp nháy: hết đạn"),
            ["icons.leaving"] = ("Grey arrow: flying out to its holding pattern", "Mũi tên xám: đang ra vòng chờ"),
            ["icons.rearming"] = ("Green ring: rearming, filling with the stores; dim at the slow rate, bright at the full one",
                "Vòng xanh: đang hồi đạn, đầy dần theo lượng đạn; mờ khi hồi chậm, sáng khi hồi đầy đủ"),
            ["icons.full"] = ("A short flash of the ring: full again", "Vòng lóe sáng: đã đầy đạn"),
            ["icons.enemy"] = ("Enemies show only empty and flying out", "Địch chỉ hiện hết đạn và đang ra vòng chờ"),
            ["tip.ammoIcons"] = ("Aircraft carry bombs, missiles and rockets that run out and come back on the field. Beside the health bar: a yellow magazine is running low, a red one empty, a grey arrow flies out to rearm, a green ring fills as the stores come back.",
                "Máy bay mang bom, tên lửa và rốc-két có hạn, hồi dần ngay trên chiến trường. Cạnh thanh máu: băng đạn vàng là sắp hết, đỏ là hết, mũi tên xám là đang ra vòng chờ, vòng xanh đầy dần khi đang hồi đạn."),

            // ---------------------------------------------------------------- a weapon
            ["ul.weapon"] = ("{weapon}: {type}, hits {targets}", "{weapon}: {type}, bắn {targets}"),
            ["ul.type.Kinetic"] = ("kinetic", "động năng"),
            ["ul.type.ShapedCharge"] = ("shaped charge", "nổ lõm"),
            ["ul.type.HighExplosive"] = ("high explosive", "nổ mạnh"),
            ["ul.type.Fragmentation"] = ("fragmentation", "mảnh"),
            ["ul.type.Energy"] = ("energy", "năng lượng"),
            ["ul.type.Fire"] = ("fire", "lửa"),
            ["ul.damage"] = ("{damage} damage a round", "Sát thương {damage} mỗi phát"),
            ["ul.damageBurst"] = ("{damage} damage a round, {count|# round|# rounds} a salvo", "Sát thương {damage} mỗi phát, {count} phát mỗi loạt"),
            ["ul.range"] = ("Range {metres} m", "Tầm bắn {metres} m"),
            ["ul.rangeMin"] = ("Range {metres} m, not closer than {minimum} m", "Tầm bắn {metres} m, tối thiểu {minimum} m"),
            ["ul.splash"] = ("{range}, splash {metres} m", "{range}, nổ lan {metres} m"),
            ["ul.splashEdge"] = ("{range}, blast {metres} m core, {edge} m edge at {share}%", "{range}, nổ lan lõi {metres} m, rìa {edge} m còn {share}%"),
            ["ul.endless"] = ("Never runs out", "Không bao giờ hết đạn"),
            ["ul.clip"] = ("Magazine of {count}, changed in place in {seconds} s", "Băng {count} viên, thay băng tại chỗ {seconds} giây"),
            ["ul.shots"] = ("{count|# shot|# shots}, reloaded in place while standing still ({seconds} s for all)", "{count} phát, nạp lại tại chỗ khi đứng yên ({seconds} giây cho đủ)"),
            ["ul.salvos"] = ("{count|# salvo|# salvos}, reloaded in place while standing still ({seconds} s for all)", "{count} loạt, nạp lại tại chỗ khi đứng yên ({seconds} giây cho đủ)"),
            ["ul.stores"] = ("{count} {noun} when full", "{count} {noun} khi đầy đạn"),
            ["ul.storesRefill"] = ("Refills on the field: full in {seconds} s at its holding pattern, half as fast while attacking or in danger",
                "Hồi dần trên chiến trường: đầy trong {seconds} giây ở vòng chờ, chậm gấp đôi khi đang tấn công hoặc trong vùng nguy hiểm"),
            ["ul.storesFaster"] = ("Faster at the landing pad (x{pad}) and over the HQ (x{hq})", "Nhanh hơn ở Bãi đáp (x{pad}) và trên sở chỉ huy (x{hq})"),
            ["ul.storesCarrier"] = ("Faster at the landing pad (x{pad}), over the HQ (x{hq}) and beside an ammo carrier (x{times})",
                "Nhanh hơn ở Bãi đáp (x{pad}), trên sở chỉ huy (x{hq}) và cạnh Xe tiếp đạn (x{times})"),
            ["ul.noun.Bomb"] = ("bombs", "quả bom"),
            ["ul.noun.Missile"] = ("missiles", "tên lửa"),
            ["ul.noun.Rocket"] = ("rockets", "rốc-két"),
            ["ul.noun.Drone"] = ("drones", "drone"),
            ["ul.noun.other"] = ("rounds", "viên"),

            // ---------------------------------------------------------------- how it moves and fights
            ["ul.move.static"] = ("Stands in place and fires at anything in reach", "Đứng yên tại chỗ, bắn mọi mục tiêu trong tầm"),
            ["ul.move.kamikaze"] = ("Goes straight for its target and blows up on it", "Lao thẳng vào mục tiêu và tự nổ"),
            ["ul.move.orbit"] = ("Circles its target, firing from the side", "Bay vòng quanh mục tiêu, bắn từ mạn"),
            ["ul.move.bomber"] = ("Flies over its target and drops its bombs in a run", "Bay qua mục tiêu và thả bom theo lượt"),
            ["ul.move.interceptor"] = ("Hunts enemy aircraft", "Săn máy bay địch"),
            ["ul.move.strike"] = ("Dives on its target and fires, then turns for another pass", "Bổ nhào xả hỏa lực vào mục tiêu, rồi vòng lại lượt khác"),
            ["ul.move.hover"] = ("Hovers at the edge of its range and fires", "Treo trên không ở rìa tầm bắn và nhả đạn"),
            ["ul.move.artillery"] = ("Stops to fire, from {minimum}-{maximum} m; needs its own or a friend's sight of the target",
                "Dừng lại mới bắn, từ {minimum}-{maximum} m; cần ta nhìn thấy mục tiêu (tự nó hoặc quân bạn)"),
            ["ul.move.standoff"] = ("Keeps to the edge of its range", "Giữ khoảng cách ở rìa tầm bắn"),
            ["ul.move.onTheMove"] = ("Fires on the move", "Vừa chạy vừa bắn"),
            ["ul.move.stops"] = ("Stops to fire", "Dừng lại mới bắn"),
            ["ul.move.building"] = ("Stands in place and serves its side", "Đứng yên tại chỗ, phục vụ phe ta"),
            ["ul.move.support"] = ("Keeps behind the front with the vehicles it serves", "Đi sau tuyến đầu, cạnh các xe nó phục vụ"),

            // ---------------------------------------------------------------- after firing
            ["ul.after.scoot"] = ("Moves {minimum}-{maximum} m after every {count|# salvo|# salvos}", "Bắn {count} loạt rồi dời vị trí {minimum}-{maximum} m"),
            ["ul.after.clip"] = ("Changes its magazine after {count|# round|# rounds}", "Bắn hết {count} viên thì thay băng"),
            ["ul.after.pass"] = ("After each pass it turns round and comes in again", "Sau mỗi lượt nó vòng lại và vào lượt mới"),

            // ---------------------------------------------------------------- target priority
            ["ul.target.strong"] = ("Goes for {targets} first", "Ưu tiên {targets}"),
            ["ul.target.bomber"] = ("Picks groups of vehicles and buildings; never bombs near our own units", "Ưu tiên cụm xe và công trình; không ném bom gần quân ta"),
            ["ul.target.air"] = ("Aircraft first", "Ưu tiên máy bay"),

            // ---------------------------------------------------------------- withdrawal
            ["ul.leave.stores"] = ("Out of stores, it finishes its attack, then flies to its holding pattern behind our line; back in with half its stores",
                "Hết đạn thì làm xong lượt tấn công, rồi ra vòng chờ sau tuyến quân ta; quay lại khi hồi được một nửa"),
            ["ul.leave.bomber"] = ("Goes in only with two thirds of its bombs; short of that it waits at its holding pattern",
                "Chỉ vào lượt ném khi có đủ 2/3 số bom; thiếu thì chờ ở vòng chờ"),
            ["ul.leave.hurt"] = ("Badly hurt, it flies to the landing pad (else the HQ) to mend", "Máu thấp thì bay về Bãi đáp (không có thì về sở chỉ huy) để sửa"),
            ["ul.leave.launcher"] = ("Empty, it reloads where it stands, or goes to an ammo carrier or home when that is quicker",
                "Hết đạn thì nạp lại tại chỗ, hoặc tới Xe tiếp đạn hay về nhà khi nhanh hơn"),

            // ---------------------------------------------------------------- skills
            ["ul.skill"] = ("{skill}: {when}", "{skill}: {when}"),
            ["ul.skill.Repair"] = ("Self-repair", "Tự sửa"),
            ["ul.skill.Shield"] = ("Shield", "Khiên"),
            ["ul.skill.Smoke"] = ("Smoke", "Khói"),
            ["ul.skill.Overdrive"] = ("Overdrive", "Tăng tốc"),
            ["ul.skill.Barrage"] = ("Barrage", "Bắn dồn"),
            ["ul.skill.Flares"] = ("Flares", "Pháo sáng"),
            ["ul.skill.Summon"] = ("Reinforcements", "Gọi quân"),
            ["ul.skill.Emp"] = ("EMP", "EMP"),
            ["ul.skill.Patch"] = ("Patch-up", "Vá bộ phận"),
            ["ul.when.Always"] = ("whenever ready (every {seconds} s)", "mỗi khi sẵn sàng (mỗi {seconds} giây)"),
            ["ul.when.HpBelow"] = ("below {percent}% health (every {seconds} s)", "khi máu dưới {percent}% (mỗi {seconds} giây)"),
            ["ul.when.UnderFire"] = ("when under fire (every {seconds} s)", "khi bị bắn (mỗi {seconds} giây)"),
            ["ul.when.EnemyInRange"] = ("when an enemy is in reach (every {seconds} s)", "khi có địch trong tầm (mỗi {seconds} giây)"),
            ["ul.when.MissileIncoming"] = ("when a missile comes at it (every {seconds} s)", "khi có tên lửa lao tới (mỗi {seconds} giây)"),
            ["ul.when.PartBroken"] = ("when a part breaks", "khi một bộ phận bị phá"),
            ["ul.aps"] = ("APS: shoots down missiles, drones and direct-fire rockets aimed within {metres} m ({charges} at a time, one back every {seconds} s)",
                "APS: bắn hạ tên lửa, drone và rốc-két bắn thẳng nhắm vào trong {metres} m ({charges} lần liền, hồi một lần mỗi {seconds} giây)"),
            ["ul.apsRockets"] = ("It also takes artillery rockets", "Bắn hạ cả rốc-két pháo binh"),
            ["ul.apsMagazine"] = ("Interceptor missiles: shoots down rounds aimed within {metres} m ({charges} in the launcher, all back {seconds} s after the last launch)",
                "Tên lửa đánh chặn: bắn hạ đạn nhắm vào trong {metres} m ({charges} quả trong bệ phóng, nạp lại đủ sau {seconds} giây kể từ lần phóng cuối)"),
            ["ul.apsLobbed"] = ("Only rounds lobbed from afar: artillery rockets, drones and long-range missiles; never direct fire (gun rounds, anti-tank missiles, rocket pods) or energy",
                "Chỉ chặn đạn bay cầu vồng từ xa: rốc-két pháo binh, drone và tên lửa tầm xa; không chặn đạn bắn thẳng (đạn pháo bắn thẳng, tên lửa chống tăng, ống phóng rốc-két) và Năng lượng"),
            ["ul.apsShells"] = ("And {percent}% of shells", "Và {percent}% số đạn pháo"),
            ["ul.jammer"] = ("Jams enemy guided weapons and fire support within {metres} m", "Gây nhiễu vũ khí dẫn đường và hỏa lực yểm trợ địch trong {metres} m"),
            ["ul.repairAura"] = ("Repairs friendly vehicles within {metres} m ({percent}% of their health a second; towers half that)",
                "Sửa xe ta trong {metres} m ({percent}% máu mỗi giây; tháp một nửa)"),
            ["ul.rearmAura"] = ("Launchers within {metres} m get one shot back every {seconds} s on top of their own reload", "Xe phóng trong {metres} m được thêm một phát mỗi {seconds} giây ngoài tốc độ nạp của nó"),
            ["ul.airRearm"] = ("Helicopters within {metres} m take their stores on {count} times as fast", "Trực thăng trong {metres} m hồi đạn nhanh gấp {count} lần"),
            ["ul.mines"] = ("Lays a mine every {seconds} s (up to {count})", "Rải một quả mìn mỗi {seconds} giây (tối đa {count})"),
            ["ul.counterBattery"] = ("Finds enemy guns firing within {metres} m", "Định vị pháo địch đang bắn trong {metres} m"),
            ["ul.stealth"] = ("Hard to see: enemies spot it at {percent}% of their sight", "Khó phát hiện: địch chỉ thấy ở {percent}% tầm nhìn"),
            ["ul.hidden"] = ("Hidden until it fires", "Ẩn mình cho tới khi khai hỏa"),

            // ---------------------------------------------------------------- base modules
            ["ul.pad"] = ("Aircraft within {metres} m take their stores on {count} times as fast and mend {percent}% of their health a second",
                "Máy bay trong {metres} m hồi đạn nhanh gấp {count} lần và hồi {percent}% máu mỗi giây"),
            ["ul.airCap"] = ("{count} more aircraft up at once for its side", "Thêm {count} máy bay được bay cùng lúc cho phe ta"),
            ["ul.moduleRearm"] = ("Launchers in the base reload {count} times as fast", "Xe phóng trong căn cứ nạp đạn nhanh gấp {count} lần"),
            ["ul.moduleRepair"] = ("Repairs vehicles in the base", "Sửa xe trong căn cứ"),
            ["ul.moduleSupply"] = ("{supply} more army supply", "Thêm {supply} sức chứa quân"),

            // Prompt 17 C: shield domes, deploying, wingmen, relays, the laser's ramp, the drone swarm.
            ["ul.dome"] = ("Shield dome of {metres} m: takes {health} damage for its side inside (not energy), back {seconds} s after its last hit; domes do not add up", "Vòm khiên {metres} m: hấp thụ {health} sát thương cho phe ta bên trong (trừ năng lượng), hồi lại {seconds} giây sau đòn cuối; các vòm không cộng dồn"),
            ["ul.deploy"] = ("Digs in when it stands with an enemy in reach or on guard ({seconds} s, no firing): front armour +{amount|# level|# levels}, reach x{times}, turret all round; packs up ({seconds} s) to move", "Tự triển khai khi dừng lại có địch trong tầm hoặc đang canh giữ ({seconds} giây, không bắn): giáp trước +{amount} cấp, tầm ×{times}, tháp xoay 360°; thu lại ({seconds} giây) để đi tiếp"),
            ["ul.siege"] = ("Siege mode: standing with an enemy in its mortar's reach, or on guard, it sieges in {seconds} s (no firing) and then only the mortar fires; it packs up ({seconds} s) to move, or when enemies get inside the mortar's minimum reach with nothing further to shell", "Chế độ công thành: dừng lại khi có địch trong tầm cối, hoặc khi canh giữ, nó vào thế trong {seconds} giây (không bắn) rồi chỉ cối bắn; thu lại ({seconds} giây) để đi tiếp, hoặc khi địch lọt vào trong tầm tối thiểu của cối mà không còn gì xa hơn để nã"),
            ["ul.siege.tank"] = ("Tank mode: its turret gun fires on the move; the mortar fires only sieged", "Chế độ xe tăng: pháo trên tháp bắn khi đang chạy; cối chỉ bắn khi đã vào thế"),
            ["ul.deploy.arc"] = ("On its tracks its turret keeps within {degrees}° of the nose", "Khi di chuyển tháp pháo chỉ xoay trong {degrees}° hai bên mũi xe"),
            ["ul.wingman"] = ("Flies on the wing of the nearest manned aircraft of its side within {metres} m (patrols over the front with none)", "Bay kèm máy bay có người lái gần nhất của phe ta trong {metres} m (không có thì tuần tra trên chiến tuyến)"),
            ["ul.wingman.decoy"] = ("An enemy anti-air missile at its leader turns onto it {percent}% of the time (within {metres} m)", "Tên lửa phòng không địch nhắm vào máy bay dẫn có {percent}% khả năng chuyển sang nó (trong {metres} m)"),
            ["ul.airCapFree"] = ("Not counted in the aircraft cap (at most {count} a side)", "Không tính vào trần máy bay (tối đa {count} chiếc mỗi phe)"),
            ["ul.sead"] = ("With no aircraft about, it hunts air defences with its bombs", "Khi không có máy bay địch, nó săn phòng không bằng bom"),
            ["ul.relay"] = ("Its side earns {cp} CP a second more (a second relay {cpSecond}); nothing for {seconds} s after a hit; two to a base, never on an outpost", "Phe mình kiếm thêm {cp} CP mỗi giây (trạm thứ hai {cpSecond}); ngừng {seconds} giây sau khi bị bắn; tối đa hai trạm mỗi căn cứ, không đặt ở tiền đồn"),
            ["ul.ramp"] = ("Ramps from x{from} to x{to} over {seconds} s on one target; starts again on another", "Tăng từ ×{from} lên ×{to} trong {seconds} giây trên cùng một mục tiêu; đổi mục tiêu thì về lại"),
            ["ul.swarm"] = ("Each drone picks its own target within {metres} m of the aim, and another if its target is gone", "Mỗi drone tự chọn mục tiêu trong {metres} m quanh điểm nhắm, và chọn mục tiêu khác nếu mục tiêu đã bị diệt"),
            // Prompt 25 G: second rounds (the detail page, the unit lines, the chip's tooltip).
            ["round.flak"] = ("Air-burst (flak)", "Nổ trên không (flak)"),
            ["round.ap"] = ("Armour-piercing", "Xuyên giáp"),
            ["round.he"] = ("High explosive", "Nổ mạnh"),
            ["round.heat"] = ("Shaped charge (HEAT)", "Nổ lõm (HEAT)"),
            ["round.guided"] = ("Guided shell", "Đạn dẫn đường"),
            ["round.api"] = ("Armour-piercing incendiary (API)", "Xuyên cháy (API)"),
            ["round.ball"] = ("Ball", "Đạn thường"),
            ["round.other"] = ("Standard", "Đạn thường"),
            ["round.for.air"] = ("aircraft and drones", "máy bay và drone"),
            ["round.for.ground"] = ("everything on the ground", "mọi mục tiêu mặt đất"),
            ["round.for.armour"] = ("armoured vehicles", "xe có giáp"),
            ["round.for.light"] = ("light vehicles", "xe nhẹ"),
            ["round.for.structure"] = ("structures", "công trình"),
            ["round.for.cluster"] = ("groups of vehicles", "cụm xe"),
            ["round.for.any"] = ("every target", "mọi mục tiêu"),
            ["round.for.rest"] = ("everything else", "các mục tiêu còn lại"),
            ["round.elite"] = ("elites and rank-7 branches only", "chỉ bản tinh nhuệ và nhánh hạng 7"),
            ["detail.rounds"] = ("Two rounds: switches on its own", "Hai loại đạn: tự đổi"),
            ["detail.roundMain"] = ("{name} (its own)", "{name} (đạn chính)"),
            ["detail.roundLine"] = ("{type}  ·  {pen}  ·  {damage} dmg{splash}", "{type}  ·  {pen}  ·  {damage} ST{splash}"),
            ["detail.roundSplash"] = ("  ·  {metres} m blast", "  ·  nổ lan {metres} m"),
            ["detail.roundFor"] = ("Against {targets}", "Dùng với {targets}"),
            ["detail.roundSwitch"] = ("Against {targets}  ·  switch {seconds} s", "Dùng với {targets}  ·  đổi đạn {seconds} giây"),
            ["tag.swap"] = ("Two rounds, switched on its own", "Hai loại đạn, tự đổi"),
            ["ul.round"] = ("Second round, on its own: {name} ({figures}) for {targets}; the switch takes {seconds} s",
                "Đạn thay thế, tự đổi: {name} ({figures}) dùng với {targets}; đổi đạn mất {seconds} giây"),
            ["ul.heRound"] = ("Loads armour-piercing for armour and high explosive ({damage}, {metres} m blast) for structures and light vehicles, on its own", "Tự đổi đạn: đạn xuyên cho xe có giáp, đạn nổ mạnh ({damage}, nổ {metres} m) cho công trình và xe nhẹ"),
            ["hud.deploying"] = ("Digging in", "Đang triển khai"),
            ["hud.deployed"] = ("Dug in", "Đã triển khai"),
            ["hud.packing"] = ("Packing up", "Đang thu lại"),

            // Prompt 25 F2 batch A (DECISIONS 25F2-A): the new units' and structures' behaviour lines.
            ["ul.blastWall"] = ("Towers of its side up to {metres} m behind it take {percent}% less direct fire (not shells, bombs or top attack); vehicles drive through it",
                "Tháp phe ta trong {metres} m sau nó nhận ít hơn {percent}% sát thương bắn thẳng (không che đạn cầu vồng, bom, đánh nóc); xe chạy xuyên qua được"),
            ["ul.decoy"] = ("Looks like a real tower: the enemy shoots at it until a scout, a radar, a drone or a UAV scan of theirs sees it for what it is",
                "Trông như tháp thật: địch bắn vào nó cho tới khi trinh sát, radar, drone hoặc UAV quét của chúng lật tẩy"),
            ["ul.fireControl"] = ("Towers of its side within {metres} m hit {percent}% harder and gang up on one target", "Tháp phe ta trong {metres} m gây thêm {percent}% sát thương và dồn hỏa lực vào cùng mục tiêu"),
            ["ul.searchlight"] = ("At night and in fog its side sees everything within {metres} m of it; enemies there shoot {percent}% less accurately",
                "Ban đêm và trong sương mù, phe ta thấy mọi thứ trong {metres} m quanh nó; địch trong vùng bắn kém chính xác {percent}%"),
            ["ul.balloon"] = ("Enemy aircraft bombing within {metres} m of it must fly higher: their bombs scatter {percent}% wider; helicopters keep out",
                "Máy bay địch ném bom trong {metres} m quanh nó phải bay cao hơn: bom tản mát thêm {percent}%; trực thăng tránh vùng"),
            ["ul.sightJammer"] = ("Enemies see nothing of its side within {metres} m of it from further than {close} m, unless they are scouts",
                "Địch không thấy gì của phe ta trong {metres} m quanh nó nếu đứng xa hơn {close} m, trừ trinh sát"),
            ["ul.shelter"] = ("Vehicles of its side within {metres} m take {percent}% less from shells, mortars, bombs and strikes (not direct fire)",
                "Xe phe ta trong {metres} m nhận ít hơn {percent}% sát thương từ pháo, cối, bom và không kích (không che đạn bắn thẳng)"),
            ["ul.flares"] = ("At night and in fog, every {seconds} s: a flare over the nearest enemy within {range} m shows everything within {metres} m",
                "Ban đêm và trong sương mù, mỗi {seconds} giây: một quả pháo sáng trên đầu địch gần nhất trong {range} m làm lộ mọi thứ trong {metres} m"),
            ["ul.microwave"] = ("Every {seconds} s: a microwave pulse downs every enemy drone within {metres} m in a {degrees}° cone; it harms nothing else",
                "Mỗi {seconds} giây: một xung vi sóng làm rơi mọi drone địch trong {metres} m, hình nón {degrees}°; không gây hại gì khác"),
            ["ul.droneHunt"] = ("Its interceptor drones also go after enemy drones flying at anything within {metres} m", "Drone đánh chặn còn lao vào drone địch đang bay tới mục tiêu trong {metres} m"),
            ["ul.paradrop"] = ("Can be dropped by parachute wherever its side sees (not into an enemy base): {seconds} s under the canopies, when anti-air can shoot it",
                "Thả dù được ở bất kỳ đâu phe ta nhìn thấy (trừ căn cứ địch): {seconds} giây dưới dù, lúc đó phòng không bắn được"),
            ["ul.reconPass"] = ("One straight run across the battlefield, showing a strip {metres} m wide for {seconds} s (stealth too), then it leaves",
                "Bay thẳng ngang chiến trường một lần, làm lộ một dải rộng {metres} m trong {seconds} giây (cả tàng hình), rồi rời trận"),
            ["ul.turretArc"] = ("Its gun covers {degrees}° ahead only and traverses slowly", "Pháo chỉ bắn trong cung {degrees}° phía trước và xoay chậm"),
            ["ul.smokeSight"] = ("Its radar sees through smoke", "Radar nhìn xuyên màn khói"),
            ["ul.stillVision"] = ("Standing still {seconds} s it raises its radar mast: sight {metres} m", "Đứng yên {seconds} giây thì dựng cột radar: tầm nhìn {metres} m"),
            ["ul.glideRelease"] = ("Releases its glide bombs from far off and turns away before the target's short-range anti-air", "Thả bom lượn từ xa rồi quay đi trước khi vào tầm phòng không tầm gần của mục tiêu"),
            ["ul.flightHigh"] = ("Flies high: only long-range SAMs and fighters reach it", "Bay rất cao: chỉ tên lửa phòng không tầm xa và tiêm kích với tới"),
            ["ul.groundRange"] = ("Reach {air} m in the air, {ground} m with the barrel lowered at the ground", "Tầm {air} m trên không, {ground} m khi hạ nòng bắn mặt đất"),
            ["ul.groupPriority"] = ("Goes for tight groups of aircraft and big aircraft first", "Ưu tiên tốp máy bay bay dày và máy bay lớn"),
            ["ul.bigGame"] = ("Goes for bombers, gunships and big aircraft first; poor in a close dogfight", "Ưu tiên oanh tạc cơ, pháo hạm bay và máy bay lớn; kém khi không chiến tầm gần"),
            ["ul.jamProof"] = ("Fibre-optic control: jammers do nothing to it", "Điều khiển qua cáp quang: gây nhiễu không có tác dụng"),
            ["ul.oneAtATime"] = ("One drone in the air at a time", "Mỗi lúc chỉ điều khiển một drone"),
            ["ul.mrsi"] = ("All {count} rounds of a salvo land at the same moment", "Cả {count} phát của một loạt rơi xuống cùng lúc"),
            ["ul.glides"] = ("Glide bombs fly slowly: point defences can shoot them down", "Bom lượn bay chậm: hệ thống phòng thủ tầm gần bắn hạ được"),
            ["ul.lofted"] = ("Fired over cover at what its side sees; strikes the roof", "Bắn vòng qua vật cản vào mục tiêu phe ta nhìn thấy; đánh vào nóc"),
            ["ul.prey.Drones"] = ("Shoots only at drones", "Chỉ bắn drone"),
            ["ul.prey.Rotors"] = ("Shoots only at drones and helicopters", "Chỉ bắn drone và trực thăng"),
        };
    }
}
