using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using NUnit.Framework;
using MachineBrigade.Game.Match;
using MachineBrigade.Sim.Content;
using UnityEngine;

namespace MachineBrigade.Tests
{
    /// <summary>
    /// Prompt 25 (DECISIONS 25A): the owner's balance spreadsheet, applied by Tools/balance/import_xlsx.py, holds in
    /// the game. The workbook itself is not read here: the importer writes the columns the tests check into
    /// Docs/balance (sheet_dps.tsv), generated from the sheet, never typed in.
    /// </summary>
    public class BalanceSheetTests
    {
        private static string Balance(string file) => Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Docs", "balance", file));

        /// <summary>The rows of a generated tab-separated file, its '#' comment lines and its header skipped.</summary>
        internal static List<string[]> Rows(string file)
        {
            var path = Balance(file);
            Assert.IsTrue(File.Exists(path), path + " is generated by Tools/balance/import_xlsx.py");
            return File.ReadAllLines(path).Where(l => l.Length > 0 && !l.StartsWith("#")).Skip(1).Select(l => l.Split('\t')).ToList();
        }

        [Test]
        public void EveryWeaponFiresTheSheetsSustainedDpsWithinFivePercent()
        {
            // A2: the sheet's "DPS duy trì đề xuất" is a cycle's damage over a cycle (damage x rounds / (rounds / rate +
            // rest)); the game's is WeaponDef.SustainedDps, the same cycle (a launcher's restock and an aircraft's rearm
            // are FirePower.Sustained's, which the sheet does not count).
            var catalog = GameContent.LoadCatalog();
            var failures = new List<string>();
            var checkedCount = 0;
            foreach (var r in Rows("sheet_dps.tsv"))
            {
                var id = r[0];
                Assert.IsTrue(catalog.Weapons.ContainsKey(id), $"the sheet's weapon '{id}' is in the catalog");
                if (string.IsNullOrEmpty(r[1]))
                {
                    Assert.IsNotEmpty(r.Length > 2 ? r[2] : "", $"{id}: an unchecked row says why");
                    continue;
                }
                var want = float.Parse(r[1], CultureInfo.InvariantCulture);
                var got = catalog.Weapons[id].SustainedDps;
                checkedCount++;
                if (Math.Abs(got / want - 1f) > 0.05f) failures.Add($"{id}: {got:0.0} a second, the sheet {want:0.0}");
            }
            Assert.IsEmpty(failures, string.Join("\n", failures));
            Assert.Greater(checkedCount, 140, "every weapon of the sheet is checked");
        }

        // ------------------------------------------------------------------ A3: weapon families

        /// <summary>Names the sheet counts as one weapon (Tools/balance/steps_a3.py ALIASES).</summary>
        private static readonly Dictionary<string, string> Aliases = new()
        {
            ["AGM-114L Hellfire Longbow"] = "AGM-114 Hellfire", ["AIM-9X Sidewinder"] = "AIM-9 Sidewinder", ["Oerlikon KDA 35 mm"] = "Oerlikon 35 mm",
        };

        /// <summary>A real name without its mount in brackets ("M2 Browning 12.7 mm" for the tower's), aliases folded.</summary>
        internal static string RealName(string real)
        {
            var name = System.Text.RegularExpressions.Regex.Replace(real, @"\s*\([^)]*\)\s*$", "").Trim();
            return Aliases.TryGetValue(name, out var alias) ? alias : name;
        }

        /// <summary>
        /// The same real weapon (steps_a3.real_key): its real name, and the same round (damage type, kind, size, a cluster
        /// or not) fired the same way (lobbed or direct): a coastal gun's flat 155 mm is not a howitzer's lobbed one.
        /// </summary>
        /// <summary>Play-test 14 (lane H): boss weapons that fly at their own speed, out of their real missile's family.</summary>
        internal static readonly HashSet<string> BossOwnSpeed = new() { "sam_post", "sam_battery", "p26_nemesis_sec_boss_rockets", "pt14_train_grad" };

        internal static string FamilyKey(WeaponDef w) =>
            w.RealName == null ? null
                : string.Join("|", RealName(w.RealName), w.DamageType, w.Projectile, w.Size.ToString(CultureInfo.InvariantCulture), w.Indirect, w.Cluster != null);

        [Test]
        public void NoTwoWeaponsOfOneFamilyDifferInSpeedBlastOrRound()
        {
            var catalog = GameContent.LoadCatalog();
            var failures = new List<string>();
            var families = 0;
            // The families of the data: each shares its speed, blast radius and round model.
            foreach (var family in catalog.Weapons.Values.Where(w => w.WeaponFamily != null).GroupBy(w => w.WeaponFamily))
            {
                families++;
                var first = family.First();
                foreach (var w in family)
                {
                    if (w.ProjectileSpeed != first.ProjectileSpeed) failures.Add($"{family.Key}: {w.Id} flies {w.ProjectileSpeed}, {first.Id} {first.ProjectileSpeed}");
                    if (w.SplashRadius != first.SplashRadius) failures.Add($"{family.Key}: {w.Id} blasts {w.SplashRadius} m, {first.Id} {first.SplashRadius} m");
                    if (w.ProjectileModel != first.ProjectileModel) failures.Add($"{family.Key}: {w.Id} flies {w.ProjectileModel}, {first.Id} {first.ProjectileModel}");
                    if (w.RoundWeight != first.RoundWeight) failures.Add($"{family.Key}: {w.Id} looks {w.RoundWeight}, {first.Id} {first.RoundWeight}");
                }
            }
            // Every set of weapons that are the same real weapon is one family (none left out of it).
            // Play-test 14 (lane H): the bosses' own SAM posts (the Buk post of the ships and Typhon, Nemesis' Patriot car) fly at
            // the boss's slower speed, out of their families; the player's launchers of the same missiles keep the family's.
            foreach (var same in catalog.Weapons.Values.Where(w => FamilyKey(w) != null && !BossOwnSpeed.Contains(w.Id)).GroupBy(FamilyKey).Where(g => g.Count() > 1))
            {
                var named = same.Select(w => w.WeaponFamily).Distinct().ToList();
                if (named.Count != 1 || named[0] == null)
                    failures.Add($"{same.Key}: {string.Join(", ", same.Select(w => $"{w.Id} ({w.WeaponFamily ?? "none"})"))} are one weapon in one family");
                if (same.Select(w => w.ProjectileSpeed).Distinct().Count() > 1 || same.Select(w => w.SplashRadius).Distinct().Count() > 1)
                    failures.Add($"{same.Key}: {string.Join(", ", same.Select(w => $"{w.Id} {w.ProjectileSpeed} m/s {w.SplashRadius} m"))}");
            }
            Assert.IsEmpty(failures, string.Join("\n", failures));
            Assert.Greater(families, 25, "the families are in the data (weaponFamilies)");
        }

        // ------------------------------------------------------------------ A4: missile speeds

        /// <summary>The span of an entry of balance.json (its braces included), found by its id.</summary>
        private static (int start, int end) EntrySpan(string text, string id)
        {
            var at = text.IndexOf("{ \"id\": \"" + id + "\"", StringComparison.Ordinal);
            Assert.GreaterOrEqual(at, 0, "no entry " + id);
            var depth = 0;
            var inString = false;
            for (var i = at; i < text.Length; i++)
            {
                var c = text[i];
                if (inString)
                {
                    if (c == '\\') i++;
                    else if (c == '"') inString = false;
                    continue;
                }
                if (c == '"') inString = true;
                else if (c == '{' || c == '[') depth++;
                else if ((c == '}' || c == ']') && --depth == 0) return (at, i + 1);
            }
            throw new AssertionException("unbalanced entry " + id);
        }

        /// <summary>
        /// The shipped catalog with a test launcher (the SAM launcher's hull, <paramref name="missile"/> its only weapon) and
        /// the fighter and the escort drone without their flares (their skills cut).
        /// </summary>
        private static Catalog LauncherOf(string missile)
        {
            var text = Resources.Load<TextAsset>("Data/balance").text.Replace("\r\n", "\n");
            var (s, e) = EntrySpan(text, "sam_launcher");
            var launcher = System.Text.RegularExpressions.Regex.Replace(text.Substring(s, e - s), "\"weapon\": \"[^\"]+\"", "\"weapon\": \"" + missile + "\"");
            launcher = System.Text.RegularExpressions.Regex.Replace(launcher, "\"secondary\": \\[[^\\]]*\\]", "\"secondary\": []");
            text = text.Substring(0, s) + launcher + text.Substring(e);
            foreach (var id in new[] { "fighter_jet", "strike_drone" })
            {
                (s, e) = EntrySpan(text, id);
                var entry = System.Text.RegularExpressions.Regex.Replace(text.Substring(s, e - s), "\"skills\": \\[[^\\]]*\\]", "\"skills\": []");
                text = text.Substring(0, s) + entry + text.Substring(e);
            }
            return Catalog.FromJson(text);
        }

        /// <summary>
        /// Missiles fired at a target that cannot die, flying a circle at <paramref name="reach"/> of the missile's range round
        /// the launcher (tangentially, at its own speed): (fired, hits).
        /// </summary>
        private static (int fired, int hits) FireAt(Catalog catalog, string missile, string targetId, int seed, float seconds, float reach)
        {
            var world = new MachineBrigade.Sim.SimWorld(catalog, new MapDefinition("range", 320f,
                new[] { new TeamStart(0, new System.Numerics.Vector2(0f, -140f)), new TeamStart(1, new System.Numerics.Vector2(0f, 140f)) },
                new List<PropPlacement>(), new List<UnitPlacement>()), seed: seed);
            world.RevealAll = true;
            var shooter = world.SpawnVehicle("sam_launcher", 0, System.Numerics.Vector2.Zero, 0f);
            var radius = catalog.Weapons[missile].Range * reach;
            var target = world.SpawnVehicle(targetId, 1, new System.Numerics.Vector2(radius, 0f), MathF.PI / 2f);
            world.MakeSparring(target);
            target.HoldFire = true;
            var angle = 0f;
            int fired = 0, hits = 0;
            for (var t = 0f; t < seconds; t += TestWorlds.Step)
            {
                // Round the launcher at its own speed: the edge of the missile's reach the whole time.
                angle += target.Def.Speed / radius * TestWorlds.Step;
                target.Position = new System.Numerics.Vector2(MathF.Cos(angle), MathF.Sin(angle)) * radius;
                target.Heading = angle + MathF.PI / 2f;
                world.Step(TestWorlds.Step);
                foreach (var e in world.Events)
                {
                    if (e.DefId != missile) continue;
                    if (e.Kind == MachineBrigade.Sim.Events.SimEventKind.WeaponFired && e.Entity == shooter.Id) fired++;
                    else if (e.Kind == MachineBrigade.Sim.Events.SimEventKind.ProjectileImpact && e.Team == 0 && e.Entity == target.Id) hits++;
                }
                world.ClearEvents();
                shooter.Hp = shooter.MaxHp;
            }
            return (fired, hits);
        }

        [Test]
        public void EverySamAndAirToAirMissileHitsAFighterAndAnEscortDroneNineTimesInTen()
        {
            // A4 (the sheet's "Tốc độ tên lửa"): every anti-aircraft and air-to-air missile, fired at a fighter (40 m/s) and at
            // an escort drone (46 m/s) near the edge of its range, with no flares, hits at least 90 % of the time. The sim's
            // guided missile follows its target; what loses it without flares is a lost lock at launch (2 % + 8 % x the
            // square of the share of its range: 8.5 % at 0.9), a jammer, a decoy or active protection, none of them here.
            var shipped = GameContent.LoadCatalog();
            var missiles = shipped.Weapons.Values
                .Where(w => w.Projectile == ProjectileKind.Missile && (w.Targets & TargetLayers.Air) != 0 && !w.InterceptOnly && !w.Laid && w.Damage > 0f)
                .Where(w => shipped.Vehicles.Values.Any(v => v.Mounts.Any(m => m.Weapon.Id == w.Id)))
                .Select(w => w.Id).OrderBy(id => id).ToList();
            Assert.Greater(missiles.Count, 12, "the SAMs and air-to-air missiles");
            var failures = new List<string>();
            foreach (var id in missiles)
            {
                var catalog = LauncherOf(id);
                var w = catalog.Weapons[id];
                // Long enough for about 30 missiles a seed (a launcher's magazine and restock counted).
                var seconds = Math.Min(400f, 30f * w.CycleSeconds / Math.Max(1, w.RoundsPerCycle) + (w.Ammo > 0 ? 30f / w.Ammo * w.MagazineReload : 0f));
                foreach (var target in new[] { "fighter_jet", "strike_drone" })
                {
                    int fired = 0, hits = 0;
                    foreach (var seed in new[] { 3, 7, 11, 19 })
                    {
                        var (f, h) = FireAt(catalog, id, target, seed, seconds, 0.9f);
                        fired += f;
                        hits += h;
                    }
                    if (fired < 40) failures.Add($"{id} at {target}: only {fired} fired");
                    else if (hits < 0.9f * fired) failures.Add($"{id} at {target}: {hits} of {fired} hit ({100f * hits / fired:0} %)");
                }
            }
            Assert.IsEmpty(failures, string.Join("\n", failures));
        }

        [Test]
        public void TheSameRoundBlastsTheSameWhereverItIsFired()
        {
            // A5 and the sheet's rule ("cùng một loại đạn phải cùng bán kính ở mọi đơn vị"): the same real round (its name,
            // damage type, size, a cluster or not) has one blast radius, lobbed or fired flat, on any carrier.
            var catalog = GameContent.LoadCatalog();
            var failures = new List<string>();
            foreach (var round in catalog.Weapons.Values.Where(w => w.RealName != null && w.SplashRadius > 0f)
                         .GroupBy(w => string.Join("|", RealName(w.RealName), w.DamageType, w.Size.ToString(CultureInfo.InvariantCulture), w.Cluster != null)))
                if (round.Select(w => w.SplashRadius).Distinct().Count() > 1)
                    failures.Add($"{round.Key}: {string.Join(", ", round.Select(w => $"{w.Id} {w.SplashRadius} m"))}");
            Assert.IsEmpty(failures, string.Join("\n", failures));
        }
    }
}
