using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using NUnit.Framework;
using MachineBrigade.Game.Match;
using MachineBrigade.Sim.Content;
using UnityEngine;

namespace MachineBrigade.Tests
{
    /// <summary>
    /// Prompt 25 (DECISIONS 25A): the owner's balance spreadsheet, applied by Tools/balance/import_xlsx.py, holds in
    /// the game. The workbook itself is not read here: the importer writes the columns the tests check into
    /// Docs/balance (sheet_dps.tsv), generated from the sheet, never typed in.
    /// </summary>
    public class BalanceSheetTests
    {
        private static string Balance(string file) => Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Docs", "balance", file));

        /// <summary>The rows of a generated tab-separated file, its '#' comment lines and its header skipped.</summary>
        internal static List<string[]> Rows(string file)
        {
            var path = Balance(file);
            Assert.IsTrue(File.Exists(path), path + " is generated by Tools/balance/import_xlsx.py");
            return File.ReadAllLines(path).Where(l => l.Length > 0 && !l.StartsWith("#")).Skip(1).Select(l => l.Split('\t')).ToList();
        }

        [Test]
        public void EveryWeaponFiresTheSheetsSustainedDpsWithinFivePercent()
        {
            // A2: the sheet's "DPS duy trì đề xuất" is a cycle's damage over a cycle (damage x rounds / (rounds / rate +
            // rest)); the game's is WeaponDef.SustainedDps, the same cycle (a launcher's restock and an aircraft's rearm
            // are FirePower.Sustained's, which the sheet does not count).
            var catalog = GameContent.LoadCatalog();
            var failures = new List<string>();
            var checkedCount = 0;
            foreach (var r in Rows("sheet_dps.tsv"))
            {
                var id = r[0];
                Assert.IsTrue(catalog.Weapons.ContainsKey(id), $"the sheet's weapon '{id}' is in the catalog");
                if (string.IsNullOrEmpty(r[1]))
                {
                    Assert.IsNotEmpty(r.Length > 2 ? r[2] : "", $"{id}: an unchecked row says why");
                    continue;
                }
                var want = float.Parse(r[1], CultureInfo.InvariantCulture);
                var got = catalog.Weapons[id].SustainedDps;
                checkedCount++;
                if (Math.Abs(got / want - 1f) > 0.05f) failures.Add($"{id}: {got:0.0} a second, the sheet {want:0.0}");
            }
            Assert.IsEmpty(failures, string.Join("\n", failures));
            Assert.Greater(checkedCount, 140, "every weapon of the sheet is checked");
        }
    }
}
