using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using MachineBrigade.Game.Match;
using MachineBrigade.Sim.Abilities;
using MachineBrigade.Sim.Content;
using MachineBrigade.Sim.Economy;
using UnityEngine;

namespace MachineBrigade.Tests
{
    /// <summary>
    /// Writes Docs/EQUIPMENT_FIT.md and the generated part of Docs/EQUIPMENT_VALUES.md from the code
    /// and data (prompt 8 I.1 and I.11), so the documents never drift from the game: the classes of
    /// every branch, what each base type, stat line, unique line, module and brand needs and which
    /// branches and classes it works on; the numbers of every line, the caps, the proc coefficient of
    /// every card's main weapon and the module scale by price; and, when the lab has run, its measured
    /// tables. MB_BALANCE=1 (it writes into the repository).
    /// </summary>
    public class EquipmentDocsExport
    {
        private static string Docs => Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Docs"));

        private static readonly GearBranch[] Branches = { GearBranch.Armor, GearBranch.Light, GearBranch.Artillery, GearBranch.Air };

        private static string Mark(BranchMask mask, GearBranch b) => (mask & (BranchMask)(1 << (int)b)) != 0 ? "yes" : "-";

        private static string Classes(VehicleNeed need) =>
            string.Join(", ", Branches.SelectMany(b => VehicleFit.ClassesOf(b).Where(c => VehicleFit.ClassMeets(c.cls, b, need)).Select(c => c.cls.ToString())).Distinct());

        private static string NeedText(VehicleNeed need) => need == VehicleNeed.None ? "anything" : need.ToString().Replace(", ", " + ");

        private static string Row(string name, string slot, VehicleNeed need, BranchMask mask) =>
            $"| {name} | {slot} | {NeedText(need)} | {string.Join(" | ", Branches.Select(b => Mark(mask, b)))} | {Classes(need)} |";

        [Test, Category("Balance"), Timeout(600000)]
        public void WriteEquipmentFitAndValues()
        {
            Lab.Gate();
            var catalog = Lab.Catalog;
            File.WriteAllText(Path.Combine(Docs, "EQUIPMENT_FIT.md"), Fit(catalog).Replace("\n", "\r\n"));
            File.WriteAllText(Path.Combine(Docs, "EQUIPMENT_VALUES.md"), Values(catalog).Replace("\n", "\r\n"));
        }

        private static string Fit(Catalog catalog)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Equipment fit matrix");
            sb.AppendLine();
            sb.AppendLine("Generated by `EquipmentDocsExport` (MB_BALANCE=1) from the code and balance.json: do not edit by hand.");
            sb.AppendLine();
            sb.AppendLine("Rules (prompt 8 I.1): every card says what it has from its weapons and body (`VehicleFit.Of`); every piece, stat line, unique line, module and brand says what it needs. " +
                          "A class meets a need when at least a third of its cards do; a branch fits a piece when one of its classes meets the piece's need (the base type and its unique line together). " +
                          "Crates only drop pieces that fit at least one branch, and the equipment screen only lets a piece onto a branch it fits (old saves: unfit pieces go back to the inventory, `PlayerProfile.MigrateFit`).");
            sb.AppendLine();
            sb.AppendLine("## Branches and their classes");
            sb.AppendLine();
            sb.AppendLine("| branch | class | cards |");
            sb.AppendLine("|---|---|---|");
            foreach (var b in Branches)
                foreach (var (cls, cards) in VehicleFit.ClassesOf(b))
                {
                    var ids = catalog.Vehicles.Values.Where(v => v.CpCost > 0 && !v.Static && !v.Boss && v.Class == cls && (GearBranch)(int)v.Branch == b)
                        .Select(v => v.Id).OrderBy(x => x);
                    sb.AppendLine($"| {b} | {cls} | {cards}: {string.Join(", ", ids)} |");
                }
            sb.AppendLine();
            var head = "| | slot | needs | Armor | Light | Artillery | Air | classes it works on |\n|---|---|---|---|---|---|---|---|";
            sb.AppendLine("## Base types");
            sb.AppendLine();
            sb.AppendLine(head.Replace("| |", "| base type |"));
            foreach (var bt in GearCatalog.Bases.Where(x => !Gear.IsTower(x.Slot)))
                sb.AppendLine(Row(bt.Id, bt.Slot.ToString(), VehicleFit.Need(bt), bt.Branches));
            sb.AppendLine();
            sb.AppendLine("## Stat lines");
            sb.AppendLine();
            sb.AppendLine(head.Replace("| |", "| stat |"));
            foreach (StatId stat in Enum.GetValues(typeof(StatId)))
            {
                if (stat == StatId.Count) continue;
                var need = VehicleFit.Need(stat);
                sb.AppendLine(Row(stat.ToString(), "sub-stat", need, VehicleFit.BranchesFor(need)));
            }
            sb.AppendLine();
            sb.AppendLine("## Unique lines");
            sb.AppendLine();
            sb.AppendLine(head.Replace("| |", "| unique line |"));
            foreach (var t in GearCatalog.Traits.Where(x => !Gear.IsTower(x.Slot)))
                sb.AppendLine(Row(t.Key, t.Slot.ToString(), t.Needs, t.Branches));
            sb.AppendLine();
            sb.AppendLine("## Modules");
            sb.AppendLine();
            sb.AppendLine(head.Replace("| |", "| module |"));
            foreach (var m in GearCatalog.Modules)
                sb.AppendLine(Row(m.Key, m.Scaled ? "module (scaled to price)" : "module", m.Needs, m.Branches));
            sb.AppendLine();
            sb.AppendLine("## Brands");
            sb.AppendLine();
            sb.AppendLine(head.Replace("| |", "| brand |"));
            foreach (var br in GearCatalog.Brands.Where(x => !x.TowerOnly))
            {
                sb.AppendLine(Row(br.Id + " (2)", "set", VehicleFit.Need(br, false), VehicleFit.BranchesFor(VehicleFit.Need(br, false))));
                sb.AppendLine(Row(br.Id + " (4)", "set", VehicleFit.Need(br, true), VehicleFit.BranchesFor(VehicleFit.Need(br, true))));
            }
            sb.AppendLine("| bulwark | tower set | a base's towers | - | - | - | - | towers only (counted across the whole base) |");
            sb.AppendLine();
            // The checks the prompt asks for: nothing that fits no branch, nothing that works on one class only.
            sb.AppendLine("## Checks");
            sb.AppendLine();
            var none = new List<string>();
            var single = new List<string>();
            void Check(string name, VehicleNeed need, BranchMask mask)
            {
                if (mask == BranchMask.None) none.Add(name);
                else if (VehicleFit.ClassesMeeting(need) == 1) single.Add(name + " (" + Classes(need) + ")");
            }
            foreach (var bt in GearCatalog.Bases.Where(x => !Gear.IsTower(x.Slot))) Check(bt.Id, VehicleFit.Need(bt), bt.Branches);
            foreach (var t in GearCatalog.Traits.Where(x => !Gear.IsTower(x.Slot))) Check(t.Key, t.Needs, t.Branches);
            foreach (var m in GearCatalog.Modules) Check(m.Key, m.Needs, m.Branches);
            sb.AppendLine("Fits no branch: " + (none.Count == 0 ? "none." : string.Join(", ", none)));
            sb.AppendLine();
            sb.AppendLine("Works on one class only: " + (single.Count == 0 ? "none." : string.Join(", ", single)) +
                          (single.Count == 0 ? "" : " (kept on purpose: see DECISIONS.md section 8)."));
            return sb.ToString();
        }

        private static string Values(Catalog catalog)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Equipment values");
            sb.AppendLine();
            sb.AppendLine("Generated by `EquipmentDocsExport` (MB_BALANCE=1) from the code and balance.json, with the equipment lab's measured tables when they are there: do not edit by hand. " +
                          "The rules behind the numbers are in DECISIONS.md section 8.");
            sb.AppendLine();
            sb.AppendLine("## Unique lines (Epic / Legendary)");
            sb.AppendLine();
            sb.AppendLine("| line | slot | Epic | Legendary |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var t in GearCatalog.Traits)
                sb.AppendLine($"| {t.Key} | {t.Slot} | {string.Join(" / ", t.Epic.Select(x => x.ToString("0.###")))} | {string.Join(" / ", t.Legendary.Select(x => x.ToString("0.###")))} |");
            sb.AppendLine();
            sb.AppendLine("## Modules (Epic / Legendary, second number)");
            sb.AppendLine();
            sb.AppendLine("| module | Epic | Legendary | scaled to the card's price |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var m in GearCatalog.Modules)
                sb.AppendLine($"| {m.Key} | {m.Epic:0.###} / {m.Epic2:0.###} | {m.Legendary:0.###} / {m.Legendary2:0.###} | {(m.Scaled ? "yes" : "-")} |");
            sb.AppendLine();
            sb.AppendLine("Module scale: clamp(CP / 7, 0.4, 1.3) of the card's price (an elite: its elite price). Fuel blast (Volatile Fuel Tanks) capped at " +
                          $"{GearSystem.FuelBlastCap:0} damage. Kill refund share capped at {EconomySystem.KillRefundCap:0.00}, own-loss refund at {EconomySystem.LossRefundCap:0.00}.");
            sb.AppendLine();
            sb.AppendLine("## Brands");
            sb.AppendLine();
            sb.AppendLine("| brand | 2 pieces | 4 pieces |");
            sb.AppendLine("|---|---|---|");
            foreach (var br in GearCatalog.Brands)
            {
                var two = br.TwoPiece.Id != TraitId.None ? $"{GearKeys.Trait(br.TwoPiece.Id)} {br.TwoPiece.A:0.###} / {br.TwoPiece.B:0.###} / {br.TwoPiece.C:0.###}" : $"{br.Stat} +{br.Value:0.###}";
                sb.AppendLine($"| {br.Id}{(br.TowerOnly ? " (towers)" : "")} | {two} | {GearKeys.Trait(br.FourPiece.Id)} {br.FourPiece.A:0.###} / {br.FourPiece.B:0.###} / {br.FourPiece.C:0.###} |");
            }
            sb.AppendLine();
            sb.AppendLine("## Stat caps (vehicles / towers)");
            sb.AppendLine();
            sb.AppendLine("| stat | vehicle cap | tower cap |");
            sb.AppendLine("|---|---|---|");
            foreach (StatId stat in Enum.GetValues(typeof(StatId)))
            {
                if (stat == StatId.Count) continue;
                var i = (int)stat;
                var v = i < GearCatalog.StatCap.Length ? GearCatalog.StatCap[i] : 0f;
                var t = i < GearCatalog.TowerStatCap.Length ? GearCatalog.TowerStatCap[i] : 0f;
                sb.AppendLine($"| {stat} | {v:0.###} | {t:0.###} |");
            }
            sb.AppendLine();
            sb.AppendLine("## Proc coefficient and module scale by card");
            sb.AppendLine();
            sb.AppendLine($"Proc coefficient: the main weapon's time between hits (a whole burst or charge counted; machine guns 1.7 times) over {GearSystem.ProcReference:0.0} s, clamped to 0.15-2.5. " +
                          "Every on-hit chance and flat on-hit amount is multiplied by it, so a fast gun and a slow one get the same share of their damage from a proc.");
            sb.AppendLine();
            sb.AppendLine("| card | CP | main weapon | time between hits (s) | proc coefficient | module scale |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var v in catalog.Vehicles.Values.Where(x => x.CpCost > 0 && !x.Static && !x.Boss).OrderBy(x => x.CpCost).ThenBy(x => x.Id))
                sb.AppendLine($"| {v.Id} | {v.CpCost} | {v.Weapon.Id} | {GearSystem.HitInterval(v.Weapon):0.00} | {GearSystem.ProcCoefficient(v.Weapon):0.00} | {Math.Clamp(v.CpCost / 7f, 0.4f, 1.3f):0.00} |");
            sb.AppendLine();
            // The lab's measured tables (MB_LAB_OUT, tag "after"), when they have been run.
            var lab = Environment.GetEnvironmentVariable("MB_LAB_OUT");
            foreach (var (file, title) in new[]
            {
                ("offensive_lines_after.md", "Offensive lines at Legendary, gain in duel damage a second by weapon group"),
                ("twin_feed_after.md", "Twin Feed by weapon group"),
                ("defensive_lines_after.md", "Other unique lines and modules at Legendary, by branch: gain in damage a second / in time alive"),
                ("risky_combos_after.md", "Risky combinations"),
                ("tower_gear_mono_after.md", "One-tower bases in Legendary tower gear"),
                ("elite_power_after.md", "Elites against their base cards"),
            })
            {
                var path = lab != null ? Path.Combine(lab, file) : null;
                if (path == null || !File.Exists(path)) continue;
                sb.AppendLine("## " + title + " (measured)");
                sb.AppendLine();
                sb.AppendLine(File.ReadAllText(path).Replace("\r\n", "\n").TrimEnd());
                sb.AppendLine();
            }
            return sb.ToString();
        }
    }
}
