// Generated by Tools/balance/import_unlocks.py from the sheet "Phương tiện" of Docs/balance/Machine_Brigade_Can_bang.xlsx.
// Edit the sheet or the script, not this file.
namespace MachineBrigade.Tests
{
    /// <summary>Prompt 25 D2: where the balance spreadsheet opens each vehicle card (Prompt25UnlockTests).</summary>
    internal static class UnlockSheetData
    {
        /// <summary>Each card: the chapter that opens it (0 a starter; 13-15 the interludes), its early price (0: none), story loot.</summary>
        internal static readonly (string id, int chapter, int early, bool loot)[] Cards =
        {
            ("armored_car", 0, 0, false),
            ("ifv", 0, 0, false),
            ("engineer_vehicle", 1, 300, false),
            ("ammo_carrier", 2, 300, false),
            ("ew_jammer", 5, 800, false),
            ("mine_layer", 3, 300, false),
            ("command_vehicle", 4, 800, false),
            ("shield_carrier", 14, 1500, false),
            ("scout_jeep", 0, 0, false),
            ("vbied", 2, 300, false),
            ("light_tank", 1, 300, false),
            ("flame_tank", 2, 300, false),
            ("rocket_technical", 1, 300, false),
            ("mortar_carrier", 1, 300, false),
            ("artillery", 2, 300, false),
            ("mlrs", 4, 800, false),
            ("shahed_truck", 5, 800, false),
            ("thermobaric_launcher", 7, 1500, false),
            ("ballistic_launcher", 8, 1500, false),
            ("heavy_rocket_artillery", 8, 1500, false),
            ("siege_tank", 7, 1500, false),
            ("zu23_technical", 1, 300, false),
            ("aa_vehicle", 2, 300, false),
            ("sam_launcher", 3, 300, false),
            ("heavy_aa", 4, 800, false),
            ("iron_beam", 6, 800, false),
            ("long_sam", 8, 1500, false),
            ("scout_heli", 3, 300, false),
            ("recon_drone", 3, 300, false),
            ("strike_drone", 5, 800, false),
            ("swarm_carrier", 5, 0, true),
            ("attack_helicopter", 3, 300, false),
            ("fighter_jet", 3, 300, false),
            ("stealth_fighter", 7, 1500, false),
            ("attack_jet", 7, 1500, false),
            ("stealth_bomber", 10, 2500, false),
            ("heavy_bomber", 9, 1500, false),
            ("sky_gunship", 10, 2500, false),
            ("armored_bulldozer", 4, 800, false),
            ("main_battle_tank", 0, 0, false),
            ("twin_tank", 6, 800, false),
            ("heavy_tank", 6, 800, false),
            ("titan_tank", 11, 2500, false),
            ("fpv_carrier", 5, 800, false),
            ("wheeled_gun", 4, 800, false),
            ("tank_destroyer", 4, 800, false),
            ("railgun_truck", 4, 0, true),
            ("laser_tank", 9, 1500, false),
        };

        /// <summary>Rows of the sheet that are no card (a boss escort, a mission unit).</summary>
        internal static readonly string[] NotCards = { "hover_gunboat", "supply_truck" };
    }
}
