#nullable enable
using System;
using System.Collections.Generic;

namespace MachineBrigade.Sim.Content
{
    /// <summary>Who drives a side in a mode (prompt 28 appendix B); a profile can combine them.</summary>
    [Flags]
    public enum AiController
    {
        None = 0,
        Commander = 1,
        WaveDirector = 2,
        Fortress = 4,
        Boss = 8,
        Static = 16,
    }

    /// <summary>Who the pressure tiers (I.6) may push: nobody, the attacker only, both sides, or only the objective's value.</summary>
    public enum StallPolicy
    {
        Both,
        Off,
        AttackerOnly,
        ObjectiveStallOnly,

        /// <summary>A fixed-deck mission: the mission type's.</summary>
        Inherit,
    }

    public enum SupportPolicy
    {
        Normal,
        DefensiveOnly,

        /// <summary>No fire support until the mission's alarm (recon, infiltration).</summary>
        DisabledUntilAlert,
    }

    public enum EngagementPolicy
    {
        Normal,

        /// <summary>Recon before the alarm: fight only what blocks the way, never chase.</summary>
        AvoidUnlessBlocking,
    }

    /// <summary>Escort and evacuation: the army stays around the convoy (appendix B).</summary>
    public sealed class EscortParams
    {
        public float MaxAdvanceDistance { get; internal set; } = 30f;
        public float RearGuardWeight { get; internal set; } = 0.3f;
        public float ThreatToConvoyWeight { get; internal set; } = 2f;
        public bool NoChaseOutsideLeash { get; internal set; } = true;

        /// <summary>No auto support with splash lands within this of a convoy truck.</summary>
        public float SafeZoneRadius { get; internal set; } = 12f;
    }

    /// <summary>A phase's change to a profile: a whole other profile (recon after the alarm) or a stall policy (outpost steps).</summary>
    public readonly struct PhaseOverride
    {
        public PhaseOverride(string when, string? profile, StallPolicy? stall)
        {
            When = when;
            Profile = profile;
            Stall = stall;
        }

        /// <summary>"alert", or "step:&lt;name&gt;" / "phase:&lt;n&gt;" as the mode names its phases.</summary>
        public string When { get; }
        public string? Profile { get; }
        public StallPolicy? Stall { get; }
    }

    /// <summary>
    /// Prompt 28 appendix B: how the AI plays one mode or mission type (balance.json "aiModeProfiles", generated by
    /// Tools/ai/import_ai_modes.py from the sheet "AI theo chế độ"). Priority: the mission's hard constraints, then this
    /// profile, then the general's preferred tactic (a start, not a lock), then the tactic's parameters, then the
    /// difficulty, which never turns on what the profile turns off.
    /// </summary>
    public sealed class AiModeProfile
    {
        public string Id { get; internal set; } = "conquest";
        public string Name { get; internal set; } = "";
        public AiController Controllers { get; internal set; } = AiController.Commander;

        /// <summary>The tactic ids the AI may play; "*" any. Empty: no strategic tactic (wave directors, bosses).</summary>
        public IReadOnlyList<string> Tactics { get; internal set; } = new[] { "*" };

        /// <summary>The commanding general's preferred tactic starts the battle (campaign, operations, a weekly fortress with a general).</summary>
        public bool GeneralTactic { get; internal set; }

        public StallPolicy Stall { get; internal set; } = StallPolicy.Both;

        /// <summary>Must spend CP: no sitting at the bank cap (the all-out saving still allowed below it).</summary>
        public bool SpendPressure { get; internal set; } = true;

        /// <summary>The use-or-lose fall of the attack threshold (I.4): push forward with a full army and bank.</summary>
        public bool AdvancePressure { get; internal set; } = true;

        public SupportPolicy Support { get; internal set; }
        public EngagementPolicy Engagement { get; internal set; }
        public bool NoChase { get; internal set; }

        /// <summary>The side that holds: "ai", "player" or "none". The defender never gets stall pressure.</summary>
        public string Defender { get; internal set; } = "none";

        public string? LeashRegion { get; internal set; }
        public float LeashDistance { get; internal set; }

        /// <summary>The factions the side may damage; a ceasefire faction is never among them (DamageSystem enforces it).</summary>
        public IReadOnlyList<string> TargetMask { get; internal set; } = new[] { "enemy" };

        public IReadOnlyList<PhaseOverride> PhaseOverrides { get; internal set; } = Array.Empty<PhaseOverride>();
        public IReadOnlyList<string> Flags { get; internal set; } = Array.Empty<string>();

        /// <summary>The player's Auto-buy / Support AI rule: "protectTarget", "escort", "breakSiege" or empty.</summary>
        public string AutoAi { get; internal set; } = "";

        public string ObjectivePolicy { get; internal set; } = "";
        public string AutoAiNote { get; internal set; } = "";
        public EscortParams? Escort { get; internal set; }

        /// <summary>A fixed-deck mission: takes the mission type's profile, changed only by its special rules.</summary>
        public bool Inherits { get; internal set; }

        public bool Has(AiController c) => (Controllers & c) != 0;
        public bool HasFlag(string flag) => Contains(Flags, flag);

        /// <summary>Whether the side may play a tactic.</summary>
        public bool Allows(string tactic) => Contains(Tactics, "*") || Contains(Tactics, tactic);

        /// <summary>Whether the team of this profile's AI side (team 1) or the player (team 0) is the defender.</summary>
        public bool Defends(int team) => Defender == "ai" ? team != 0 : Defender == "player" && team == 0;

        /// <summary>A copy with the fixed deck's special-rule flags on top (prompt 31 missions).</summary>
        public AiModeProfile WithFlags(IEnumerable<string> flags)
        {
            var copy = (AiModeProfile)MemberwiseClone();
            var all = new List<string>(Flags);
            foreach (var f in flags)
                if (!all.Contains(f)) all.Add(f);
            copy.Flags = all;
            return copy;
        }

        private static bool Contains(IReadOnlyList<string> list, string value)
        {
            foreach (var x in list)
                if (x == value) return true;
            return false;
        }

        internal static AiModeProfile Parse(string id, JsonObject o)
        {
            var p = new AiModeProfile
            {
                Id = id,
                Name = o.OptionalString("name") ?? id,
                Tactics = o.StringArray("tactics"),
                GeneralTactic = o.Bool("generalTactic", false),
                Stall = o.Enum("stall", StallPolicy.Both),
                SpendPressure = o.Bool("spend", true),
                AdvancePressure = o.Bool("advance", true),
                Support = o.Enum("support", SupportPolicy.Normal),
                Engagement = o.Enum("engagement", EngagementPolicy.Normal),
                NoChase = o.Bool("noChase", false),
                Defender = o.OptionalString("defender") ?? "none",
                LeashRegion = o.OptionalString("leashRegion"),
                LeashDistance = o.Float("leashDistance", 0f),
                AutoAi = o.OptionalString("autoAi") ?? "",
                ObjectivePolicy = o.OptionalString("objectivePolicy") ?? "",
                AutoAiNote = o.OptionalString("autoAiNote") ?? "",
                Inherits = o.Bool("inherits", false),
            };
            if (o.Has("targetMask")) p.TargetMask = o.StringArray("targetMask");
            if (o.Has("flags")) p.Flags = o.StringArray("flags");
            var controllers = AiController.None;
            foreach (var c in o.StringArray("controllers"))
                controllers |= Enum.TryParse<AiController>(c, true, out var e) ? e : throw new FormatException($"{id}: controller {c}");
            p.Controllers = controllers;
            var phases = new List<PhaseOverride>();
            foreach (var ph in o.Array("phaseOverrides"))
                phases.Add(new PhaseOverride(ph.String("when"), ph.OptionalString("profile"),
                    ph.Has("stall") ? ph.Enum<StallPolicy>("stall") : null));
            p.PhaseOverrides = phases;
            if (o.Has("escort"))
            {
                var e = o.Object("escort");
                p.Escort = new EscortParams
                {
                    MaxAdvanceDistance = e.Float("maxAdvanceDistance", 30f),
                    RearGuardWeight = e.Float("rearGuardWeight", 0.3f),
                    ThreatToConvoyWeight = e.Float("threatToConvoyWeight", 2f),
                    NoChaseOutsideLeash = e.Bool("noChaseOutsideLeash", true),
                    SafeZoneRadius = e.Float("safeZoneRadius", 12f),
                };
            }
            return p;
        }
    }

    /// <summary>The profiles and which one each mode tag and campaign goal plays.</summary>
    public sealed class AiModeProfiles
    {
        private readonly Dictionary<string, AiModeProfile> _profiles = new();
        private readonly Dictionary<string, string> _modes = new();
        private readonly Dictionary<string, string> _goals = new();

        public IReadOnlyDictionary<string, AiModeProfile> Profiles => _profiles;
        public IReadOnlyDictionary<string, string> Modes => _modes;
        public IReadOnlyDictionary<string, string> Goals => _goals;

        private static readonly AiModeProfile Fallback = new();

        public AiModeProfile Get(string id) => _profiles.TryGetValue(id, out var p) ? p : Fallback;

        /// <summary>A goal's profile id, or null when the data names none.</summary>
        public string? GoalProfile(string goal) => _goals.TryGetValue(goal, out var id) && _profiles.ContainsKey(id) ? id : null;

        /// <summary>
        /// The profile for a mode tag and, in the campaign, a mission goal (the goal wins: a campaign mission plays its
        /// type). An unknown tag plays the default (Conquest's rules).
        /// </summary>
        public AiModeProfile For(string? modeTag, string? missionGoal)
        {
            if (missionGoal != null && GoalProfile(missionGoal) is { } goal) return _profiles[goal];
            if (modeTag != null && _modes.TryGetValue(modeTag, out var id) && _profiles.TryGetValue(id, out var p)) return p;
            return _profiles.TryGetValue("conquest", out var c) ? c : Fallback;
        }

        internal static AiModeProfiles Parse(JsonObject o)
        {
            var data = new AiModeProfiles();
            var profiles = o.Object("profiles");
            foreach (var id in profiles.Keys) data._profiles[id] = AiModeProfile.Parse(id, profiles.Object(id));
            if (o.Has("modes"))
            {
                var m = o.Object("modes");
                foreach (var k in m.Keys) data._modes[k] = m.String(k);
            }
            if (o.Has("goals"))
            {
                var g = o.Object("goals");
                foreach (var k in g.Keys) data._goals[k] = g.String(k);
            }
            return data;
        }
    }

    public sealed partial class Catalog
    {
        /// <summary>Prompt 28 appendix B: the AI profile of each mode and mission type (balance.json "aiModeProfiles").</summary>
        public AiModeProfiles AiModes { get; internal set; } = new();
    }
}
