#nullable enable
using System;
using System.Collections.Generic;

namespace MachineBrigade.Sim.Content
{
    /// <summary>
    /// Prompt 30 L4: one mode's match rules (balance.json "matchRules", generated by Tools/story/import_match_rules.py from
    /// the sheet "Luật trận"): the schema's seven fields as worded (win, loss, time limit, overtime, draw, score,
    /// catch-up) and the numbers the mode reads. There is no general "no army left loses" rule: a mode says so itself.
    /// </summary>
    public sealed class MatchRuleSet
    {
        public string Mode { get; internal set; } = "";
        public IReadOnlyDictionary<string, string> Text { get; internal set; } = new Dictionary<string, string>();
        private readonly Dictionary<string, float> _numbers = new();

        public float Get(string key, float fallback) => _numbers.TryGetValue(key, out var v) ? v : fallback;
        public bool Has(string key) => _numbers.ContainsKey(key);

        private readonly Dictionary<string, IReadOnlyList<string>> _lists = new();

        /// <summary>Prompt 32 L7: a named list of the rules ("lists": Showdown's eligible maps); empty when the data has none.</summary>
        public IReadOnlyList<string> List(string key) => _lists.TryGetValue(key, out var l) ? l : Array.Empty<string>();

        internal static MatchRuleSet Parse(string mode, JsonObject o)
        {
            var set = new MatchRuleSet { Mode = mode };
            var text = new Dictionary<string, string>();
            if (o.Has("text"))
            {
                var t = o.Object("text");
                foreach (var k in t.Keys) text[k] = t.String(k);
            }
            set.Text = text;
            if (o.Has("numbers"))
            {
                var n = o.Object("numbers");
                foreach (var k in n.Keys) set._numbers[k] = n.Float(k);
            }
            if (o.Has("lists"))
            {
                var l = o.Object("lists");
                foreach (var k in l.Keys) set._lists[k] = l.StringArray(k);
            }
            return set;
        }
    }

    /// <summary>What a campaign mission's second and third stars ask (by goal; a mission's own challenge is its ★3).</summary>
    public readonly struct StarRule
    {
        public StarRule(string kind, float value)
        {
            Kind = kind;
            Value = value;
        }

        public string Kind { get; }
        public float Value { get; }
    }

    /// <summary>What happened in a won mission, for its stars (MissionMode fills the battle's part, the session the rest).</summary>
    public struct StarFacts
    {
        public bool Won;
        public int ConvoyArrived, ConvoySent;
        public float HoldShare;
        public int ProtectStanding, ProtectTotal;
        public int LostCp, ArmyCpLeft;
        public int BossParts;
        public float HqShare, AllyHqShare;
        public int ReconQuiet, ReconTotal;
        public int Kills;
        public bool UsedStrikes, BoughtAircraft;

        /// <summary>The share of the army lost (lost CP over lost plus what is left).</summary>
        public float LossShare => LostCp + ArmyCpLeft > 0 ? LostCp / (float)(LostCp + ArmyCpLeft) : 0f;
    }

    /// <summary>
    /// Prompt 30 L4 campaignStarRules[3], campaign missions only: ★1 the win; ★2 the mission type's mastery
    /// (<see cref="Mastery"/> by goal); ★3 the mission's own challenge (its "challenge"), else <see cref="Third"/> by goal.
    /// Neither is ever a loss condition.
    /// </summary>
    public sealed class CampaignStars
    {
        private readonly Dictionary<string, StarRule> _mastery = new(), _third = new();

        public StarRule? Mastery(string goal) => _mastery.TryGetValue(goal, out var r) ? r : null;
        public StarRule? Third(string goal) => _third.TryGetValue(goal, out var r) ? r : null;

        /// <summary>The ★3 rule of a mission: its own challenge, else the goal's default.</summary>
        public StarRule? ThirdFor(MissionDef mission) =>
            mission.Challenge != null ? new StarRule(mission.Challenge, mission.ChallengeValue) : Third(mission.Goal.ToString());

        public static bool Met(StarRule rule, in StarFacts f) => rule.Kind switch
        {
            "ConvoyShare" => f.ConvoySent > 0 && f.ConvoyArrived >= rule.Value * f.ConvoySent - 1e-3f,
            "HoldShare" => f.HoldShare >= rule.Value,
            "ProtectShare" => f.ProtectTotal > 0 && f.ProtectStanding >= rule.Value * f.ProtectTotal - 1e-3f,
            "LossShare" => f.LossShare <= rule.Value,
            "BossParts" => f.BossParts >= rule.Value,
            "HqShare" => f.HqShare >= rule.Value,
            "AllyHqShare" => f.AllyHqShare >= rule.Value,
            "ReconQuiet" => f.ReconTotal > 0 && f.ReconQuiet >= rule.Value * f.ReconTotal - 1e-3f,
            "Kills" => f.Kills >= rule.Value,
            "NoStrikes" => !f.UsedStrikes,
            "NoAircraft" => !f.BoughtAircraft,
            _ => true,
        };

        /// <summary>The stars of a mission: 0 for a loss, else 1 + mastery + third.</summary>
        public int Count(MissionDef mission, in StarFacts f)
        {
            if (!f.Won) return 0;
            var stars = 1;
            if (Mastery(mission.Goal.ToString()) is not { } m || Met(m, f)) stars++;
            if (ThirdFor(mission) is not { } t || Met(t, f)) stars++;
            return stars;
        }

        internal static CampaignStars Parse(JsonObject root)
        {
            var s = new CampaignStars();
            void Read(string key, Dictionary<string, StarRule> into)
            {
                if (!root.Has(key)) return;
                var o = root.Object(key);
                foreach (var goal in o.Keys)
                {
                    var r = o.Object(goal);
                    into[goal] = new StarRule(r.String("kind"), r.Float("value", 0f));
                }
            }
            Read("starMastery", s._mastery);
            Read("starThird", s._third);
            return s;
        }
    }

    /// <summary>One leaderboard entry's numbers (what the board's keys name).</summary>
    public sealed class BoardEntry
    {
        public string Player { get; set; } = "";
        public IDictionary<string, double> Values { get; } = new Dictionary<string, double>();
        public double this[string key] => Values.TryGetValue(key, out var v) ? v : 0;
    }

    /// <summary>
    /// Prompt 30 L4: a leaderboard's order, key by key ("-waves" descending, "+seconds" ascending), never a merged
    /// formula, so a long farm can never pass someone who got further.
    /// </summary>
    public sealed class BoardOrder : IComparer<BoardEntry>
    {
        public BoardOrder(IReadOnlyList<string> keys) => Keys = keys;

        public IReadOnlyList<string> Keys { get; }

        public int Compare(BoardEntry? a, BoardEntry? b)
        {
            if (ReferenceEquals(a, b)) return 0;
            if (a == null) return 1;
            if (b == null) return -1;
            foreach (var k in Keys)
            {
                var name = k.Substring(1);
                var c = a[name].CompareTo(b[name]);
                if (c != 0) return k[0] == '-' ? -c : c;
            }
            return string.CompareOrdinal(a.Player, b.Player);
        }
    }

    /// <summary>All of balance.json "matchRules".</summary>
    public sealed class MatchRules
    {
        private readonly Dictionary<string, MatchRuleSet> _modes = new();
        private readonly Dictionary<string, BoardOrder> _boards = new();

        public IReadOnlyDictionary<string, MatchRuleSet> Modes => _modes;
        public IReadOnlyDictionary<string, BoardOrder> Boards => _boards;
        public CampaignStars Stars { get; private set; } = new();

        /// <summary>A mode's rules, or null when the data has none (the mode keeps its own defaults).</summary>
        public MatchRuleSet? For(string mode) => _modes.TryGetValue(mode, out var r) ? r : null;

        public BoardOrder? Board(string id) => _boards.TryGetValue(id, out var b) ? b : null;

        internal static MatchRules Parse(JsonObject o)
        {
            var m = new MatchRules();
            if (o.Has("modes"))
            {
                var modes = o.Object("modes");
                foreach (var k in modes.Keys) m._modes[k] = MatchRuleSet.Parse(k, modes.Object(k));
            }
            m.Stars = CampaignStars.Parse(o);
            if (o.Has("leaderboards"))
            {
                var b = o.Object("leaderboards");
                foreach (var k in b.Keys) m._boards[k] = new BoardOrder(b.StringArray(k));
            }
            return m;
        }
    }

    public sealed partial class Catalog
    {
        /// <summary>Prompt 30 L4: balance.json "matchRules".</summary>
        public MatchRules MatchRules { get; internal set; } = new();
    }
}
