// AI MASTER lane P4 (advanced planning): the new values live in Resources/Data/tunables.json under "ai" -> planning / forecast /
// packageAbort / commitment / opportunity / probe / feint / adaptation / airOps / bossTactics / stagger / gating / ownership / cues;
// these defaults equal the file's. Spec values where the master spec gives a number (sections 132-133, 152-158, 174-184, 204,
// 214-218), the lane's choices elsewhere (DECISIONS "AI MASTER P4 (lane A)"). Generated by the lane's gen_tunables_p4.py.
#nullable enable
using System;

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Ai
        {
            /// <summary>Lane switch, shallow counterfactual plans (154), anti-repetition (158), plan choice.</summary>
            public static partial class Planning
            {
                /// <summary>ai.planning.enabled (flag): the P4 planning layer (forecast, plans, probe / feint, adaptation, air packages, boss tactics, stagger); false = P3 behaviour.</summary>
                public static bool Enabled = true;
                /// <summary>ai.planning.plansByLevel (count): spec 216: candidate plans by difficulty (Easy, Normal, Hard, Very Hard).</summary>
                public static int[] PlansByLevel = { 1, 2, 3, 4 };
                /// <summary>ai.planning.depthByLevel (count): spec 154: forecast depth by difficulty (1: one step; 2: plus the enemy's known reinforcements).</summary>
                public static int[] DepthByLevel = { 1, 1, 2, 2 };
                /// <summary>ai.planning.objectiveGain (points): spec 154 ObjectiveGain: utility of taking the objective, times the breakthrough chance.</summary>
                public static float ObjectiveGain = 30.0f;
                /// <summary>ai.planning.enemyLossWeight (x): spec 154 EnemyLossValue: utility points per strength point of forecast enemy loss.</summary>
                public static float EnemyLossWeight = 1.0f;
                /// <summary>ai.planning.friendlyLossWeight (x): spec 154 FriendlyLossValue: utility points per strength point of forecast own loss.</summary>
                public static float FriendlyLossWeight = 1.2f;
                /// <summary>ai.planning.delayCostPerS (points): spec 154 DelayCost: points per second of delay (times 1 + urgency).</summary>
                public static float DelayCostPerS = 0.6f;
                /// <summary>ai.planning.congestionWeight (points): spec 154 CongestionCost: points per unit of P3 route congestion.</summary>
                public static float CongestionWeight = 4.0f;
                /// <summary>ai.planning.uncertaintyWeight (points): spec 154 UncertaintyRisk: points per share of unknown ground on the way.</summary>
                public static float UncertaintyWeight = 10.0f;
                /// <summary>ai.planning.waitArtilleryS (s): plan B (wait artillery): the prep seconds the guns get before contact.</summary>
                public static float WaitArtilleryS = 4.0f;
                /// <summary>ai.planning.flankDpsBonus (x): plan C (flank): own damage on side armour.</summary>
                public static float FlankDpsBonus = 1.25f;
                /// <summary>ai.planning.flankEnemyUptime (share): plan C (flank): share of the enemy's guns that bear on a flanking force.</summary>
                public static float FlankEnemyUptime = 0.6f;
                /// <summary>ai.planning.holdPowerFloor (share): plan D (split / hold) wins when every attack plan leaves less than this own power (pre-contact only).</summary>
                public static float HoldPowerFloor = 0.35f;
                /// <summary>ai.planning.switchMargin (share): a new plan must beat the current one by this share (anti-churn).</summary>
                public static float SwitchMargin = 0.1f;
                /// <summary>ai.planning.repeatPenalty (share): spec 158: penalty of a plan that just failed (light failure .. heavy).</summary>
                public static float[] RepeatPenalty = { 0.25f, 0.5f };
                /// <summary>ai.planning.repeatHalfLifeS (s): spec 158 / 218: the penalty's half-life (30-60 s).</summary>
                public static float RepeatHalfLifeS = 45.0f;
            }

            /// <summary>Spec 152-153 / 222: the short-horizon combat forecast (shallow, cached, no projectile simulation).</summary>
            public static partial class Forecast
            {
                /// <summary>ai.forecast.seconds (s): spec 218 combatForecastSeconds (4-8 s).</summary>
                public static float Seconds = 6.0f;
                /// <summary>ai.forecast.cacheS (s): spec 218 combatForecastCacheS.</summary>
                public static float CacheS = 0.75f;
                /// <summary>ai.forecast.aoeClusterBonus (x): splash damage gain per extra enemy in the cluster.</summary>
                public static float AoeClusterBonus = 0.15f;
                /// <summary>ai.forecast.aoeMax (x): the splash gain's cap.</summary>
                public static float AoeMax = 1.0f;
                /// <summary>ai.forecast.uptimeFloor (share): the lowest range uptime counted.</summary>
                public static float UptimeFloor = 0.15f;
                /// <summary>ai.forecast.unknownMargin (x): enemy estimate x this where the ground round the cluster is mostly unknown.</summary>
                public static float UnknownMargin = 1.25f;
                /// <summary>ai.forecast.reinforceRadius (m): depth 2: known enemy groups within this join after the first step.</summary>
                public static float ReinforceRadius = 80.0f;
                /// <summary>ai.forecast.depthTwoShare (share): depth 2: the second step's share of the horizon.</summary>
                public static float DepthTwoShare = 0.5f;
                /// <summary>ai.forecast.enoughRatio (x): P0-B open item: buying stops when own power is this many times the known enemy's.</summary>
                public static float EnoughRatio = 2.0f;
                /// <summary>ai.forecast.enoughEnemyAfter (share): and the forecast leaves the enemy at most this share of its power.</summary>
                public static float EnoughEnemyAfter = 0.3f;
                /// <summary>ai.forecast.enoughMaxHoldS (s): the 'force enough' hold never lasts longer than this at a time.</summary>
                public static float EnoughMaxHoldS = 30.0f;
                /// <summary>ai.forecast.enoughMinKnown (count): the hold needs at least this many known enemies (an unknown enemy is not a weak one).</summary>
                public static int EnoughMinKnown = 3;
            }

            /// <summary>Spec 155 / 182-183: plan validity dependencies, abort before contact, interrupt / replan.</summary>
            public static partial class PackageAbort
            {
                /// <summary>ai.packageAbort.enemyRise (x): spec 155: the enemy estimate at the target rose this much since the plan.</summary>
                public static float EnemyRise = 1.5f;
                /// <summary>ai.packageAbort.clusterShift (m): spec 183: the target cluster moved this far (cluster version).</summary>
                public static float ClusterShift = 25.0f;
                /// <summary>ai.packageAbort.lethalWarningPad (m): spec 182: a big warning this close to a member or the staging is a new lethal warning.</summary>
                public static float LethalWarningPad = 8.0f;
            }

            /// <summary>Spec 184: commitment windows (turret target 1-1.5 s and firing spot 2-3 s stay P0-A's / P2's).</summary>
            public static partial class Commitment
            {
                /// <summary>ai.commitment.routeS (s): spec 184: a squad's flank side (route) is kept this long.</summary>
                public static float[] RouteS = { 4.0f, 6.0f };
                /// <summary>ai.commitment.packageS (s): spec 184: an attack package's plan is kept this long (emergency safety may break it).</summary>
                public static float[] PackageS = { 6.0f, 12.0f };
            }

            /// <summary>Spec 156: opportunity / exploit windows (location, confidence, expiry, required roles).</summary>
            public static partial class Opportunity
            {
                /// <summary>ai.opportunity.aaDownS (s): an enemy anti-air seen destroyed: air window.</summary>
                public static float AaDownS = 15.0f;
                /// <summary>ai.opportunity.partDownS (s): a boss APS / shield / radar part seen broken.</summary>
                public static float PartDownS = 12.0f;
                /// <summary>ai.opportunity.artilleryExposedS (s): an enemy gun seen with no known escort near.</summary>
                public static float ArtilleryExposedS = 8.0f;
                /// <summary>ai.opportunity.exposedRadius (m): no known enemy direct-fire unit within this of the gun.</summary>
                public static float ExposedRadius = 35.0f;
                /// <summary>ai.opportunity.redeployS (s): defenders seen leaving the objective.</summary>
                public static float RedeployS = 10.0f;
                /// <summary>ai.opportunity.redeployDrop (share): the seen enemy strength at the objective dropped by this share without seen losses.</summary>
                public static float RedeployDrop = 0.4f;
                /// <summary>ai.opportunity.mainFarS (s): the enemy main force far from the objective.</summary>
                public static float MainFarS = 10.0f;
                /// <summary>ai.opportunity.mainFarDistance (m): its distance from the objective.</summary>
                public static float MainFarDistance = 120.0f;
                /// <summary>ai.opportunity.gateS (s): a gate of the enemy's walls seen open.</summary>
                public static float GateS = 10.0f;
                /// <summary>ai.opportunity.attackPoints (points): squad option points for a window of its roles near its goal.</summary>
                public static float AttackPoints = 10.0f;
                /// <summary>ai.opportunity.planGain (points): plan utility points for a window at the plan's target.</summary>
                public static float PlanGain = 10.0f;
            }

            /// <summary>Spec 132: probe-and-exploit.</summary>
            public static partial class Probe
            {
                /// <summary>ai.probe.powerShare (share): spec 132 / 218 probePowerShare: the probe's share of the army's power.</summary>
                public static float[] PowerShare = { 0.08f, 0.15f };
                /// <summary>ai.probe.maxSeconds (s): a probe reports by then.</summary>
                public static float MaxSeconds = 20.0f;
                /// <summary>ai.probe.envelope (share): never closer than this share of its reach to the known enemy (a probe is not a suicide).</summary>
                public static float Envelope = 0.9f;
                /// <summary>ai.probe.lowResistance (x): seen enemy / probe strength under this: low resistance (exploit window).</summary>
                public static float LowResistance = 0.6f;
                /// <summary>ai.probe.atThreat (x): anti-tank threat / probe strength over this: high (threat event, artillery / flank / SEAD).</summary>
                public static float AtThreat = 1.0f;
                /// <summary>ai.probe.exploitS (s): the exploit window's life.</summary>
                public static float ExploitS = 20.0f;
                /// <summary>ai.probe.cooldownS (s): time between two probes.</summary>
                public static float CooldownS = 45.0f;
                /// <summary>ai.probe.blockedS (s): no progress this long: the lane is blocked.</summary>
                public static float BlockedS = 8.0f;
                /// <summary>ai.probe.laneMemoryS (s): a blocked / hot lane is remembered this long.</summary>
                public static float LaneMemoryS = 60.0f;
                /// <summary>ai.probe.minUnknown (share): probe only where at least this share of the lane is unknown.</summary>
                public static float MinUnknown = 0.35f;
            }

            /// <summary>Spec 133: conditional feint (tactical utility only, success only when a redeploy is seen).</summary>
            public static partial class Feint
            {
                /// <summary>ai.feint.minUtility (share): the feint's own utility must reach this.</summary>
                public static float MinUtility = 0.5f;
                /// <summary>ai.feint.weights (share): utility of: contest a secondary point, force spotting, threaten a flank, pin a turret arc.</summary>
                public static float[] Weights = { 0.4f, 0.3f, 0.3f, 0.2f };
                /// <summary>ai.feint.maxSeconds (s): a feint ends by then.</summary>
                public static float MaxSeconds = 25.0f;
                /// <summary>ai.feint.redeployShare (share): success: this share of the seen enemy at the main objective moved towards the feint.</summary>
                public static float RedeployShare = 0.25f;
                /// <summary>ai.feint.cooldownS (s): time between two feints.</summary>
                public static float CooldownS = 60.0f;
                /// <summary>ai.feint.powerShareMax (share): the feinting squad's largest share of the army.</summary>
                public static float PowerShareMax = 0.2f;
            }

            /// <summary>Spec 157 / Part M: same-match adaptation (EMA, reset each match, observed data only).</summary>
            public static partial class Adaptation
            {
                /// <summary>ai.adaptation.emaAlpha (share): the moving averages' weight of a new sample.</summary>
                public static float EmaAlpha = 0.2f;
                /// <summary>ai.adaptation.lowUtilization (share): spec 218 sameMatchLowUtilizationThreshold.</summary>
                public static float LowUtilization = 0.15f;
                /// <summary>ai.adaptation.lowUtilizationS (s): spec 218 sameMatchLowUtilizationSeconds.</summary>
                public static float LowUtilizationS = 20.0f;
                /// <summary>ai.adaptation.purchaseFloor (x): the lowest purchase modifier of an under-used class.</summary>
                public static float PurchaseFloor = 0.5f;
                /// <summary>ai.adaptation.baitRepeat (count): Part M: deaths while chasing near the same spot this often = a bait pattern.</summary>
                public static int BaitRepeat = 2;
                /// <summary>ai.adaptation.leashScale (x): Part M: the pursuit leash under a bait pattern.</summary>
                public static float LeashScale = 0.6f;
                /// <summary>ai.adaptation.reconBoost (share): Part M: scout-before-commit's unknown share lowered by this under an ambush pattern.</summary>
                public static float ReconBoost = 0.15f;
                /// <summary>ai.adaptation.airHeavyShare (share): Part M: the seen enemy is air-heavy above this share.</summary>
                public static float AirHeavyShare = 0.35f;
                /// <summary>ai.adaptation.campImpacts (count): Part M: this many observed shells from one battery estimate = artillery camping.</summary>
                public static int CampImpacts = 6;
                /// <summary>ai.adaptation.towerCount (count): Part M: this many enemy towers seen = a tower-defence pattern.</summary>
                public static int TowerCount = 3;
            }

            /// <summary>Spec 174-178 + predictive air interception: SEAD, risk routing, CAP, handoff, bomber packages.</summary>
            public static partial class AirOps
            {
                /// <summary>ai.airOps.seadHoldS (s): spec 174: strike aircraft wait this long for the suppression, then reroute or delay.</summary>
                public static float SeadHoldS = 12.0f;
                /// <summary>ai.airOps.seadStandoff (m): the ingress hold point's distance outside the SAM's known reach.</summary>
                public static float SeadStandoff = 50.0f;
                /// <summary>ai.airOps.seadThreat (x): known anti-air / aircraft strength over this at the goal asks for SEAD.</summary>
                public static float SeadThreat = 1.0f;
                /// <summary>ai.airOps.riskSamples (count): spec 175: AirRiskMap samples along a leg.</summary>
                public static int RiskSamples = 6;
                /// <summary>ai.airOps.riskPassLimit (count): spec 175: passes through the strongest SAM bubble before a detour is forced.</summary>
                public static int RiskPassLimit = 1;
                /// <summary>ai.airOps.capRadius (m): spec 176: a CAP zone's radius.</summary>
                public static float CapRadius = 60.0f;
                /// <summary>ai.airOps.capLeash (x): spec 176: a fighter chases at most this many zone radii from its zone.</summary>
                public static float CapLeash = 1.5f;
                /// <summary>ai.airOps.capPatrolS (s): spec 176: the patrol point turns this often.</summary>
                public static float CapPatrolS = 8.0f;
                /// <summary>ai.airOps.handoffMax (count): spec 177: attackers on one aircraft at most.</summary>
                public static int HandoffMax = 2;
                /// <summary>ai.airOps.handoffTtkS (s): spec 177: the TTK one attacker should reach (else a second).</summary>
                public static float HandoffTtkS = 4.0f;
                /// <summary>ai.airOps.bomberMinValue (x): spec 178: the seen enemy strength under a bomber's blast worth the sortie.</summary>
                public static float BomberMinValue = 8.0f;
                /// <summary>ai.airOps.bomberRiskMax (x): spec 178: route risk / bomber strength accepted.</summary>
                public static float BomberRiskMax = 1.5f;
                /// <summary>ai.airOps.bomberBlastGap (m): spec 178: friendlies kept this far beyond the blast.</summary>
                public static float BomberBlastGap = 8.0f;
                /// <summary>ai.airOps.bomberWaitMaxS (s): spec 178: a bomber waits for a target this long, then goes as before.</summary>
                public static float BomberWaitMaxS = 30.0f;
                /// <summary>ai.airOps.interceptHorizonS (s): predictive interception: the lead horizon of a fighter on an aircraft.</summary>
                public static float InterceptHorizonS = 6.0f;
            }

            /// <summary>Spec 179-181, 204, 214 + P0-B section 18: boss weakpoints, telegraph escape sectors, pacing.</summary>
            public static partial class BossTactics
            {
                /// <summary>ai.bossTactics.weakpointWeights (points): spec 179: disabled DPS share, disabled APS / shield / radar, phase utility, kill progress.</summary>
                public static float[] WeakpointWeights = { 50.0f, 25.0f, 40.0f, 30.0f };
                /// <summary>ai.bossTactics.sectorsByLevel (count): spec 181: escape sectors by difficulty (quality only).</summary>
                public static int[] SectorsByLevel = { 3, 3, 4, 5 };
                /// <summary>ai.bossTactics.sectorMargin (m): spec 181: an exit point this far outside the ring.</summary>
                public static float SectorMargin = 6.0f;
                /// <summary>ai.bossTactics.patternWindowS (s): spec 214: a follow-up zone of the same boss within this is part of its pattern.</summary>
                public static float PatternWindowS = 8.0f;
                /// <summary>ai.bossTactics.patternCost (m): spec 214: route cost added to a sector the learnt pattern covered.</summary>
                public static float PatternCost = 25.0f;
                /// <summary>ai.bossTactics.pressureBudget (count): spec 204: dangerous actions already active before a non-critical one waits.</summary>
                public static int PressureBudget = 2;
                /// <summary>ai.bossTactics.pressureDelayS (s): spec 204: the short wait.</summary>
                public static float PressureDelayS = 1.5f;
                /// <summary>ai.bossTactics.pressureMaxDelayS (s): spec 204: the most one cast waits (the cooldown after it is shortened by the wait: no damage lost).</summary>
                public static float PressureMaxDelayS = 3.0f;
                /// <summary>ai.bossTactics.phaseMargin (share): P0-B 18: a seen boss this close above its next phase mark: keep CP back.</summary>
                public static float PhaseMargin = 0.08f;
                /// <summary>ai.bossTactics.phaseReserveShare (share): P0-B 18: the share of the bank kept back.</summary>
                public static float PhaseReserveShare = 0.3f;
                /// <summary>ai.bossTactics.phaseReserveMaxS (s): P0-B 18: never longer than this at a time.</summary>
                public static float PhaseReserveMaxS = 25.0f;
            }

            /// <summary>Spec 217: deterministic human-like stagger (hash of unit and event, never Random).</summary>
            public static partial class Stagger
            {
                /// <summary>ai.stagger.window (s): spec 217: 150-400 ms between equivalent actions.</summary>
                public static float[] Window = { 0.15f, 0.4f };
            }

            /// <summary>Spec 216: advanced difficulty gating (0 Easy, 1 Normal, 2 Hard, 3 Very Hard).</summary>
            public static partial class Gating
            {
                /// <summary>ai.gating.probeLevel (count): probe-and-exploit from this level.</summary>
                public static int ProbeLevel = 2;
                /// <summary>ai.gating.feintLevel (count): conditional feint from this level.</summary>
                public static int FeintLevel = 2;
                /// <summary>ai.gating.adaptationLevel (count): same-match adaptation from this level.</summary>
                public static int AdaptationLevel = 2;
                /// <summary>ai.gating.seadLevel (count): SEAD packages from this level.</summary>
                public static int SeadLevel = 2;
                /// <summary>ai.gating.patternLevel (count): within-encounter pattern learning from this level.</summary>
                public static int PatternLevel = 2;
                /// <summary>ai.gating.bomberLevel (count): bomber packages and CAP zones from this level.</summary>
                public static int BomberLevel = 1;
            }

            /// <summary>Intent ownership: one owner orders a unit at a time (P3 fire missions vs TacticalAi.DirectArtillery, air packages vs the old air logic).</summary>
            public static partial class Ownership
            {
                /// <summary>ai.ownership.missionClaimS (s): a fire mission owns its gun this long.</summary>
                public static float MissionClaimS = 10.0f;
                /// <summary>ai.ownership.scootClaimS (s): a scoot owns its gun this long.</summary>
                public static float ScootClaimS = 8.0f;
                /// <summary>ai.ownership.airClaimS (s): an air package / CAP order owns its aircraft this long (renewed each look).</summary>
                public static float AirClaimS = 3.0f;
            }

            /// <summary>Spec 215: tactical communication cues (presentation only, no gameplay bonus).</summary>
            public static partial class Cues
            {
                /// <summary>ai.cues.enabled (flag): record cues (synchronized go, flank, feint, escape) for the presentation.</summary>
                public static bool Enabled = true;
                /// <summary>ai.cues.cooldownS (s): one cue of a kind per side this often.</summary>
                public static float CooldownS = 10.0f;
                /// <summary>ai.cues.kept (count): cues kept for the presentation to read.</summary>
                public static int Kept = 32;
            }
        }

        private static readonly Entry[] AiMasterP4 =
        {
            new Entry("ai.planning.enabled", "flag", () => Ai.Planning.Enabled ? 1 : 0, v => Ai.Planning.Enabled = v >= 0.5, flag: true),
            Entry.IntArray("ai.planning.plansByLevel", "count", () => Ai.Planning.PlansByLevel, v => Ai.Planning.PlansByLevel = v),
            Entry.IntArray("ai.planning.depthByLevel", "count", () => Ai.Planning.DepthByLevel, v => Ai.Planning.DepthByLevel = v),
            new Entry("ai.planning.objectiveGain", "points", () => Ai.Planning.ObjectiveGain, v => Ai.Planning.ObjectiveGain = (float)v),
            new Entry("ai.planning.enemyLossWeight", "x", () => Ai.Planning.EnemyLossWeight, v => Ai.Planning.EnemyLossWeight = (float)v),
            new Entry("ai.planning.friendlyLossWeight", "x", () => Ai.Planning.FriendlyLossWeight, v => Ai.Planning.FriendlyLossWeight = (float)v),
            new Entry("ai.planning.delayCostPerS", "points", () => Ai.Planning.DelayCostPerS, v => Ai.Planning.DelayCostPerS = (float)v),
            new Entry("ai.planning.congestionWeight", "points", () => Ai.Planning.CongestionWeight, v => Ai.Planning.CongestionWeight = (float)v),
            new Entry("ai.planning.uncertaintyWeight", "points", () => Ai.Planning.UncertaintyWeight, v => Ai.Planning.UncertaintyWeight = (float)v),
            new Entry("ai.planning.waitArtilleryS", "s", () => Ai.Planning.WaitArtilleryS, v => Ai.Planning.WaitArtilleryS = (float)v),
            new Entry("ai.planning.flankDpsBonus", "x", () => Ai.Planning.FlankDpsBonus, v => Ai.Planning.FlankDpsBonus = (float)v),
            new Entry("ai.planning.flankEnemyUptime", "share", () => Ai.Planning.FlankEnemyUptime, v => Ai.Planning.FlankEnemyUptime = (float)v),
            new Entry("ai.planning.holdPowerFloor", "share", () => Ai.Planning.HoldPowerFloor, v => Ai.Planning.HoldPowerFloor = (float)v),
            new Entry("ai.planning.switchMargin", "share", () => Ai.Planning.SwitchMargin, v => Ai.Planning.SwitchMargin = (float)v),
            Entry.FloatArray("ai.planning.repeatPenalty", "share", () => Ai.Planning.RepeatPenalty, v => Ai.Planning.RepeatPenalty = v),
            new Entry("ai.planning.repeatHalfLifeS", "s", () => Ai.Planning.RepeatHalfLifeS, v => Ai.Planning.RepeatHalfLifeS = (float)v),
            new Entry("ai.forecast.seconds", "s", () => Ai.Forecast.Seconds, v => Ai.Forecast.Seconds = (float)v),
            new Entry("ai.forecast.cacheS", "s", () => Ai.Forecast.CacheS, v => Ai.Forecast.CacheS = (float)v),
            new Entry("ai.forecast.aoeClusterBonus", "x", () => Ai.Forecast.AoeClusterBonus, v => Ai.Forecast.AoeClusterBonus = (float)v),
            new Entry("ai.forecast.aoeMax", "x", () => Ai.Forecast.AoeMax, v => Ai.Forecast.AoeMax = (float)v),
            new Entry("ai.forecast.uptimeFloor", "share", () => Ai.Forecast.UptimeFloor, v => Ai.Forecast.UptimeFloor = (float)v),
            new Entry("ai.forecast.unknownMargin", "x", () => Ai.Forecast.UnknownMargin, v => Ai.Forecast.UnknownMargin = (float)v),
            new Entry("ai.forecast.reinforceRadius", "m", () => Ai.Forecast.ReinforceRadius, v => Ai.Forecast.ReinforceRadius = (float)v),
            new Entry("ai.forecast.depthTwoShare", "share", () => Ai.Forecast.DepthTwoShare, v => Ai.Forecast.DepthTwoShare = (float)v),
            new Entry("ai.forecast.enoughRatio", "x", () => Ai.Forecast.EnoughRatio, v => Ai.Forecast.EnoughRatio = (float)v),
            new Entry("ai.forecast.enoughEnemyAfter", "share", () => Ai.Forecast.EnoughEnemyAfter, v => Ai.Forecast.EnoughEnemyAfter = (float)v),
            new Entry("ai.forecast.enoughMaxHoldS", "s", () => Ai.Forecast.EnoughMaxHoldS, v => Ai.Forecast.EnoughMaxHoldS = (float)v),
            new Entry("ai.forecast.enoughMinKnown", "count", () => Ai.Forecast.EnoughMinKnown, v => Ai.Forecast.EnoughMinKnown = (int)Math.Round(v)),
            new Entry("ai.packageAbort.enemyRise", "x", () => Ai.PackageAbort.EnemyRise, v => Ai.PackageAbort.EnemyRise = (float)v),
            new Entry("ai.packageAbort.clusterShift", "m", () => Ai.PackageAbort.ClusterShift, v => Ai.PackageAbort.ClusterShift = (float)v),
            new Entry("ai.packageAbort.lethalWarningPad", "m", () => Ai.PackageAbort.LethalWarningPad, v => Ai.PackageAbort.LethalWarningPad = (float)v),
            Entry.FloatArray("ai.commitment.routeS", "s", () => Ai.Commitment.RouteS, v => Ai.Commitment.RouteS = v),
            Entry.FloatArray("ai.commitment.packageS", "s", () => Ai.Commitment.PackageS, v => Ai.Commitment.PackageS = v),
            new Entry("ai.opportunity.aaDownS", "s", () => Ai.Opportunity.AaDownS, v => Ai.Opportunity.AaDownS = (float)v),
            new Entry("ai.opportunity.partDownS", "s", () => Ai.Opportunity.PartDownS, v => Ai.Opportunity.PartDownS = (float)v),
            new Entry("ai.opportunity.artilleryExposedS", "s", () => Ai.Opportunity.ArtilleryExposedS, v => Ai.Opportunity.ArtilleryExposedS = (float)v),
            new Entry("ai.opportunity.exposedRadius", "m", () => Ai.Opportunity.ExposedRadius, v => Ai.Opportunity.ExposedRadius = (float)v),
            new Entry("ai.opportunity.redeployS", "s", () => Ai.Opportunity.RedeployS, v => Ai.Opportunity.RedeployS = (float)v),
            new Entry("ai.opportunity.redeployDrop", "share", () => Ai.Opportunity.RedeployDrop, v => Ai.Opportunity.RedeployDrop = (float)v),
            new Entry("ai.opportunity.mainFarS", "s", () => Ai.Opportunity.MainFarS, v => Ai.Opportunity.MainFarS = (float)v),
            new Entry("ai.opportunity.mainFarDistance", "m", () => Ai.Opportunity.MainFarDistance, v => Ai.Opportunity.MainFarDistance = (float)v),
            new Entry("ai.opportunity.gateS", "s", () => Ai.Opportunity.GateS, v => Ai.Opportunity.GateS = (float)v),
            new Entry("ai.opportunity.attackPoints", "points", () => Ai.Opportunity.AttackPoints, v => Ai.Opportunity.AttackPoints = (float)v),
            new Entry("ai.opportunity.planGain", "points", () => Ai.Opportunity.PlanGain, v => Ai.Opportunity.PlanGain = (float)v),
            Entry.FloatArray("ai.probe.powerShare", "share", () => Ai.Probe.PowerShare, v => Ai.Probe.PowerShare = v),
            new Entry("ai.probe.maxSeconds", "s", () => Ai.Probe.MaxSeconds, v => Ai.Probe.MaxSeconds = (float)v),
            new Entry("ai.probe.envelope", "share", () => Ai.Probe.Envelope, v => Ai.Probe.Envelope = (float)v),
            new Entry("ai.probe.lowResistance", "x", () => Ai.Probe.LowResistance, v => Ai.Probe.LowResistance = (float)v),
            new Entry("ai.probe.atThreat", "x", () => Ai.Probe.AtThreat, v => Ai.Probe.AtThreat = (float)v),
            new Entry("ai.probe.exploitS", "s", () => Ai.Probe.ExploitS, v => Ai.Probe.ExploitS = (float)v),
            new Entry("ai.probe.cooldownS", "s", () => Ai.Probe.CooldownS, v => Ai.Probe.CooldownS = (float)v),
            new Entry("ai.probe.blockedS", "s", () => Ai.Probe.BlockedS, v => Ai.Probe.BlockedS = (float)v),
            new Entry("ai.probe.laneMemoryS", "s", () => Ai.Probe.LaneMemoryS, v => Ai.Probe.LaneMemoryS = (float)v),
            new Entry("ai.probe.minUnknown", "share", () => Ai.Probe.MinUnknown, v => Ai.Probe.MinUnknown = (float)v),
            new Entry("ai.feint.minUtility", "share", () => Ai.Feint.MinUtility, v => Ai.Feint.MinUtility = (float)v),
            Entry.FloatArray("ai.feint.weights", "share", () => Ai.Feint.Weights, v => Ai.Feint.Weights = v),
            new Entry("ai.feint.maxSeconds", "s", () => Ai.Feint.MaxSeconds, v => Ai.Feint.MaxSeconds = (float)v),
            new Entry("ai.feint.redeployShare", "share", () => Ai.Feint.RedeployShare, v => Ai.Feint.RedeployShare = (float)v),
            new Entry("ai.feint.cooldownS", "s", () => Ai.Feint.CooldownS, v => Ai.Feint.CooldownS = (float)v),
            new Entry("ai.feint.powerShareMax", "share", () => Ai.Feint.PowerShareMax, v => Ai.Feint.PowerShareMax = (float)v),
            new Entry("ai.adaptation.emaAlpha", "share", () => Ai.Adaptation.EmaAlpha, v => Ai.Adaptation.EmaAlpha = (float)v),
            new Entry("ai.adaptation.lowUtilization", "share", () => Ai.Adaptation.LowUtilization, v => Ai.Adaptation.LowUtilization = (float)v),
            new Entry("ai.adaptation.lowUtilizationS", "s", () => Ai.Adaptation.LowUtilizationS, v => Ai.Adaptation.LowUtilizationS = (float)v),
            new Entry("ai.adaptation.purchaseFloor", "x", () => Ai.Adaptation.PurchaseFloor, v => Ai.Adaptation.PurchaseFloor = (float)v),
            new Entry("ai.adaptation.baitRepeat", "count", () => Ai.Adaptation.BaitRepeat, v => Ai.Adaptation.BaitRepeat = (int)Math.Round(v)),
            new Entry("ai.adaptation.leashScale", "x", () => Ai.Adaptation.LeashScale, v => Ai.Adaptation.LeashScale = (float)v),
            new Entry("ai.adaptation.reconBoost", "share", () => Ai.Adaptation.ReconBoost, v => Ai.Adaptation.ReconBoost = (float)v),
            new Entry("ai.adaptation.airHeavyShare", "share", () => Ai.Adaptation.AirHeavyShare, v => Ai.Adaptation.AirHeavyShare = (float)v),
            new Entry("ai.adaptation.campImpacts", "count", () => Ai.Adaptation.CampImpacts, v => Ai.Adaptation.CampImpacts = (int)Math.Round(v)),
            new Entry("ai.adaptation.towerCount", "count", () => Ai.Adaptation.TowerCount, v => Ai.Adaptation.TowerCount = (int)Math.Round(v)),
            new Entry("ai.airOps.seadHoldS", "s", () => Ai.AirOps.SeadHoldS, v => Ai.AirOps.SeadHoldS = (float)v),
            new Entry("ai.airOps.seadStandoff", "m", () => Ai.AirOps.SeadStandoff, v => Ai.AirOps.SeadStandoff = (float)v),
            new Entry("ai.airOps.seadThreat", "x", () => Ai.AirOps.SeadThreat, v => Ai.AirOps.SeadThreat = (float)v),
            new Entry("ai.airOps.riskSamples", "count", () => Ai.AirOps.RiskSamples, v => Ai.AirOps.RiskSamples = (int)Math.Round(v)),
            new Entry("ai.airOps.riskPassLimit", "count", () => Ai.AirOps.RiskPassLimit, v => Ai.AirOps.RiskPassLimit = (int)Math.Round(v)),
            new Entry("ai.airOps.capRadius", "m", () => Ai.AirOps.CapRadius, v => Ai.AirOps.CapRadius = (float)v),
            new Entry("ai.airOps.capLeash", "x", () => Ai.AirOps.CapLeash, v => Ai.AirOps.CapLeash = (float)v),
            new Entry("ai.airOps.capPatrolS", "s", () => Ai.AirOps.CapPatrolS, v => Ai.AirOps.CapPatrolS = (float)v),
            new Entry("ai.airOps.handoffMax", "count", () => Ai.AirOps.HandoffMax, v => Ai.AirOps.HandoffMax = (int)Math.Round(v)),
            new Entry("ai.airOps.handoffTtkS", "s", () => Ai.AirOps.HandoffTtkS, v => Ai.AirOps.HandoffTtkS = (float)v),
            new Entry("ai.airOps.bomberMinValue", "x", () => Ai.AirOps.BomberMinValue, v => Ai.AirOps.BomberMinValue = (float)v),
            new Entry("ai.airOps.bomberRiskMax", "x", () => Ai.AirOps.BomberRiskMax, v => Ai.AirOps.BomberRiskMax = (float)v),
            new Entry("ai.airOps.bomberBlastGap", "m", () => Ai.AirOps.BomberBlastGap, v => Ai.AirOps.BomberBlastGap = (float)v),
            new Entry("ai.airOps.bomberWaitMaxS", "s", () => Ai.AirOps.BomberWaitMaxS, v => Ai.AirOps.BomberWaitMaxS = (float)v),
            new Entry("ai.airOps.interceptHorizonS", "s", () => Ai.AirOps.InterceptHorizonS, v => Ai.AirOps.InterceptHorizonS = (float)v),
            Entry.FloatArray("ai.bossTactics.weakpointWeights", "points", () => Ai.BossTactics.WeakpointWeights, v => Ai.BossTactics.WeakpointWeights = v),
            Entry.IntArray("ai.bossTactics.sectorsByLevel", "count", () => Ai.BossTactics.SectorsByLevel, v => Ai.BossTactics.SectorsByLevel = v),
            new Entry("ai.bossTactics.sectorMargin", "m", () => Ai.BossTactics.SectorMargin, v => Ai.BossTactics.SectorMargin = (float)v),
            new Entry("ai.bossTactics.patternWindowS", "s", () => Ai.BossTactics.PatternWindowS, v => Ai.BossTactics.PatternWindowS = (float)v),
            new Entry("ai.bossTactics.patternCost", "m", () => Ai.BossTactics.PatternCost, v => Ai.BossTactics.PatternCost = (float)v),
            new Entry("ai.bossTactics.pressureBudget", "count", () => Ai.BossTactics.PressureBudget, v => Ai.BossTactics.PressureBudget = (int)Math.Round(v)),
            new Entry("ai.bossTactics.pressureDelayS", "s", () => Ai.BossTactics.PressureDelayS, v => Ai.BossTactics.PressureDelayS = (float)v),
            new Entry("ai.bossTactics.pressureMaxDelayS", "s", () => Ai.BossTactics.PressureMaxDelayS, v => Ai.BossTactics.PressureMaxDelayS = (float)v),
            new Entry("ai.bossTactics.phaseMargin", "share", () => Ai.BossTactics.PhaseMargin, v => Ai.BossTactics.PhaseMargin = (float)v),
            new Entry("ai.bossTactics.phaseReserveShare", "share", () => Ai.BossTactics.PhaseReserveShare, v => Ai.BossTactics.PhaseReserveShare = (float)v),
            new Entry("ai.bossTactics.phaseReserveMaxS", "s", () => Ai.BossTactics.PhaseReserveMaxS, v => Ai.BossTactics.PhaseReserveMaxS = (float)v),
            Entry.FloatArray("ai.stagger.window", "s", () => Ai.Stagger.Window, v => Ai.Stagger.Window = v),
            new Entry("ai.gating.probeLevel", "count", () => Ai.Gating.ProbeLevel, v => Ai.Gating.ProbeLevel = (int)Math.Round(v)),
            new Entry("ai.gating.feintLevel", "count", () => Ai.Gating.FeintLevel, v => Ai.Gating.FeintLevel = (int)Math.Round(v)),
            new Entry("ai.gating.adaptationLevel", "count", () => Ai.Gating.AdaptationLevel, v => Ai.Gating.AdaptationLevel = (int)Math.Round(v)),
            new Entry("ai.gating.seadLevel", "count", () => Ai.Gating.SeadLevel, v => Ai.Gating.SeadLevel = (int)Math.Round(v)),
            new Entry("ai.gating.patternLevel", "count", () => Ai.Gating.PatternLevel, v => Ai.Gating.PatternLevel = (int)Math.Round(v)),
            new Entry("ai.gating.bomberLevel", "count", () => Ai.Gating.BomberLevel, v => Ai.Gating.BomberLevel = (int)Math.Round(v)),
            new Entry("ai.ownership.missionClaimS", "s", () => Ai.Ownership.MissionClaimS, v => Ai.Ownership.MissionClaimS = (float)v),
            new Entry("ai.ownership.scootClaimS", "s", () => Ai.Ownership.ScootClaimS, v => Ai.Ownership.ScootClaimS = (float)v),
            new Entry("ai.ownership.airClaimS", "s", () => Ai.Ownership.AirClaimS, v => Ai.Ownership.AirClaimS = (float)v),
            new Entry("ai.cues.enabled", "flag", () => Ai.Cues.Enabled ? 1 : 0, v => Ai.Cues.Enabled = v >= 0.5, flag: true),
            new Entry("ai.cues.cooldownS", "s", () => Ai.Cues.CooldownS, v => Ai.Cues.CooldownS = (float)v),
            new Entry("ai.cues.kept", "count", () => Ai.Cues.Kept, v => Ai.Cues.Kept = (int)Math.Round(v)),
        };
    }
}
