// AI MASTER lane P3 (coordination): the new values live in Resources/Data/tunables.json under "ai" -> coordination / memory /
// confidence / routes / attackSync / board / fireMissions / pursuit / rangeMargin / reserveRelease / objectives / coverage /
// stance; these defaults equal the file's. Spec values where the master spec gives a number (sections 125-151, 199-213, 218),
// the lane's choices elsewhere (DECISIONS "AI MASTER P3 (lane A)"). Generated by the lane's gen_tunables.py.
#nullable enable
using System;

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Ai
        {
            /// <summary>Lane switch and cadence (Part P: frontline / influence staggered).</summary>
            public static partial class Coordination
            {
                /// <summary>ai.coordination.enabled (flag): the P3 coordination layer (frontline, memory, board, packages, fire missions, pursuit); false = P2 behaviour.</summary>
                public static bool Enabled = true;
                /// <summary>ai.coordination.frontlineUpdateS (s): spec 218 frontlineUpdateS: the frontline model is rebuilt this often.</summary>
                public static float FrontlineUpdateS = 1.0f;
                /// <summary>ai.coordination.localRadius (m): spec 125 LocalForceRatio: own / enemy strength within this of a squad (at least its reach).</summary>
                public static float LocalRadius = 50.0f;
            }

            /// <summary>Spec 127-130, 206: temporal influence, recent deaths, unknown ground, failed routes.</summary>
            public static partial class Memory
            {
                /// <summary>ai.memory.mobileHalfLifeS (s): spec 128: a mobile contact's threat memory half-life (8-12 s).</summary>
                public static float MobileHalfLifeS = 10.0f;
                /// <summary>ai.memory.artilleryHalfLifeS (s): spec 128: a suspected artillery's threat memory half-life (15-25 s).</summary>
                public static float ArtilleryHalfLifeS = 20.0f;
                /// <summary>ai.memory.staticHalfLifeS (s): spec 128 / 218: a tower / static defence's threat memory half-life (30-60 s).</summary>
                public static float StaticHalfLifeS = 45.0f;
                /// <summary>ai.memory.absentDecay (x): spec 128 ConfirmedAbsent: a remembered threat in a cell seen empty keeps this share per refresh.</summary>
                public static float AbsentDecay = 0.25f;
                /// <summary>ai.memory.deathHalfLifeS (s): spec 129 / 218 deathMemoryHalfLifeS.</summary>
                public static float DeathHalfLifeS = 18.0f;
                /// <summary>ai.memory.deathRadius (m): spec 129: a friendly death marks danger within this.</summary>
                public static float DeathRadius = 20.0f;
                /// <summary>ai.memory.unknownSeconds (s): spec 130: ground not seen for this long is Unknown (uncertainty cost).</summary>
                public static float UnknownSeconds = 20.0f;
                /// <summary>ai.memory.unknownRisk (x): spec 130 tactic modifier: blitz, balanced, attrition, recon / ambush.</summary>
                public static float[] UnknownRisk = { 0.3f, 0.6f, 1.0f, 1.0f };
                /// <summary>ai.memory.repeatPlanPenalty (x): spec 218 repeatPlanPenalty: a route that just failed costs this much more.</summary>
                public static float RepeatPlanPenalty = 0.35f;
                /// <summary>ai.memory.repeatPlanHalfLifeS (s): spec 218 repeatPlanPenaltyHalfLifeS.</summary>
                public static float RepeatPlanHalfLifeS = 45.0f;
                /// <summary>ai.memory.routeFailShare (share): spec 127: a squad that loses this share of its strength on a route marks it failed.</summary>
                public static float RouteFailShare = 0.4f;
            }

            /// <summary>Spec 125 / 219: tactical confidence (mechanical, never morale).</summary>
            public static partial class Confidence
            {
                /// <summary>ai.confidence.weights (share): spec 125: force ratio, role coverage, support, position, urgency, intel.</summary>
                public static float[] Weights = { 0.35f, 0.2f, 0.15f, 0.1f, 0.1f, 0.1f };
                /// <summary>ai.confidence.aggressive (share): spec 125: at or over this: aggressive opportunity.</summary>
                public static float Aggressive = 0.7f;
                /// <summary>ai.confidence.cautious (share): spec 125: under this: cautious / hold / regroup.</summary>
                public static float Cautious = 0.45f;
                /// <summary>ai.confidence.noCommit (share): spec 125: under this: no fresh commitment without an emergency objective.</summary>
                public static float NoCommit = 0.3f;
                /// <summary>ai.confidence.points (points): squad option points of a full confidence step.</summary>
                public static float Points = 12.0f;
            }

            /// <summary>Spec 127 / P2 76: route diversity and traffic-aware flank costs.</summary>
            public static partial class Routes
            {
                /// <summary>ai.routes.distanceScale (m): a route's length is counted in units of this.</summary>
                public static float DistanceScale = 100.0f;
                /// <summary>ai.routes.congestionWeight (x): spec 127 Congestion x 0.8.</summary>
                public static float CongestionWeight = 0.8f;
                /// <summary>ai.routes.occupancyWeight (x): spec 127 FriendlyRouteOccupancy x 0.5.</summary>
                public static float OccupancyWeight = 0.5f;
                /// <summary>ai.routes.lossWeight (x): spec 127 RecentLosses x 0.7.</summary>
                public static float LossWeight = 0.7f;
                /// <summary>ai.routes.points (points): squad option points per unit of route cost over the cheapest.</summary>
                public static float Points = 10.0f;
                /// <summary>ai.routes.occupancyRadius (m): two squads whose route middles are this close share a corridor.</summary>
                public static float OccupancyRadius = 25.0f;
                /// <summary>ai.routes.bookSeconds (s): a squad's corridor booking lasts this long unless renewed.</summary>
                public static float BookSeconds = 8.0f;
            }

            /// <summary>Spec 131, 134-137, 126: attack packages, synchronized ETA, staging, scout first, frontage.</summary>
            public static partial class AttackSync
            {
                /// <summary>ai.attackSync.groundToleranceS (s): spec 135 / 218 syncGroundToleranceS.</summary>
                public static float GroundToleranceS = 3.0f;
                /// <summary>ai.attackSync.airToleranceS (s): spec 135 / 218 syncAirToleranceS.</summary>
                public static float AirToleranceS = 4.0f;
                /// <summary>ai.attackSync.artilleryPrepLeadS (s): spec 135 / 218: artillery lands this long before ground contact.</summary>
                public static float ArtilleryPrepLeadS = 2.0f;
                /// <summary>ai.attackSync.detour (x): a straight distance times this is the ETA's path length.</summary>
                public static float Detour = 1.25f;
                /// <summary>ai.attackSync.packageSeconds (s): a package ends this long after its execute time.</summary>
                public static float PackageSeconds = 25.0f;
                /// <summary>ai.attackSync.stagingBand (m): spec 137: staging stands this far outside the known enemy reach.</summary>
                public static float StagingBand = 12.0f;
                /// <summary>ai.attackSync.subZoneSpacing (m): spec 137: each squad's staging sub-zone this far from the next.</summary>
                public static float SubZoneSpacing = 14.0f;
                /// <summary>ai.attackSync.maxStageS (s): a squad never stages longer than this (never wait forever).</summary>
                public static float MaxStageS = 15.0f;
                /// <summary>ai.attackSync.scoutMaxWaitS (s): spec 131 / 218 scoutBeforeCommitMaxWaitS (2-6 s).</summary>
                public static float ScoutMaxWaitS = 5.0f;
                /// <summary>ai.attackSync.scoutUnknownShare (share): spec 131: unknown share round the objective that asks for a scout.</summary>
                public static float ScoutUnknownShare = 0.5f;
                /// <summary>ai.attackSync.scoutDeathDanger (x): spec 129 / 131: recent-death danger round the objective that asks for a scout.</summary>
                public static float ScoutDeathDanger = 1.0f;
                /// <summary>ai.attackSync.fixEnvelope (share): spec 134: a Fix squad keeps this share of its reach from the target (no suicide).</summary>
                public static float FixEnvelope = 0.85f;
                /// <summary>ai.attackSync.frontageSeparation (m): spec 126: desired separation per hull in the frontage sum.</summary>
                public static float FrontageSeparation = 6.0f;
                /// <summary>ai.attackSync.waveGapS (s): spec 126: a staggered wave waits this long per wave.</summary>
                public static float WaveGapS = 6.0f;
                /// <summary>ai.attackSync.defaultFrontage (m): spec 126: usable width when no front segment or choke narrows it.</summary>
                public static float DefaultFrontage = 60.0f;
            }

            /// <summary>Spec 138-142, 199-201: planned action board, focus fire, handoff.</summary>
            public static partial class Board
            {
                /// <summary>ai.board.plannedOverkillShare (x): spec 139 / 218: planned + committed damage over hp x this: another target.</summary>
                public static float PlannedOverkillShare = 1.15f;
                /// <summary>ai.board.damageLeadS (s): spec 139: a damage reservation lasts a weapon cycle plus this.</summary>
                public static float DamageLeadS = 1.5f;
                /// <summary>ai.board.repairWindowS (s): spec 140: an engineer's reservation counts this many seconds of its repair.</summary>
                public static float RepairWindowS = 8.0f;
                /// <summary>ai.board.smokeSpacing (m): spec 142: no second smoke within this of a running or planned one.</summary>
                public static float SmokeSpacing = 10.0f;
                /// <summary>ai.board.smokeSeconds (s): spec 142: a planned smoke mission's length when the card does not say.</summary>
                public static float SmokeSeconds = 20.0f;
                /// <summary>ai.board.handoffRatio (x): spec 200: a mate this much better suited takes the target.</summary>
                public static float HandoffRatio = 1.6f;
                /// <summary>ai.board.handoffLockS (s): spec 200: a handoff holds this long (no churn).</summary>
                public static float HandoffLockS = 2.5f;
                /// <summary>ai.board.preferWorth (x): spec 200: the handed-over target's weight for its new owner.</summary>
                public static float PreferWorth = 1.5f;
                /// <summary>ai.board.avoidWorth (x): spec 200: the handed-off target's weight for the old owner.</summary>
                public static float AvoidWorth = 0.4f;
                /// <summary>ai.board.spreadFocusShare (x): spec 199: the squad focus weight kept when a focus is not worth massing on.</summary>
                public static float SpreadFocusShare = 0.3f;
                /// <summary>ai.board.nearKillShare (share): spec 199: a target under this health share is near kill.</summary>
                public static float NearKillShare = 0.3f;
                /// <summary>ai.board.secondaryHeavy (x): spec 201: a light secondary mount on heavy armour.</summary>
                public static float SecondaryHeavy = 0.4f;
                /// <summary>ai.board.secondaryFit (x): spec 201: a secondary mount on what it is made for (light, air, cluster, structure).</summary>
                public static float SecondaryFit = 1.3f;
            }

            /// <summary>Spec 143-145, 213: fire mission scheduler, counter-battery, shoot-and-scoot.</summary>
            public static partial class FireMissions
            {
                /// <summary>ai.fireMissions.minError (m): spec 144: the smallest error radius of an origin estimate.</summary>
                public static float MinError = 8.0f;
                /// <summary>ai.fireMissions.errorShare (share): spec 144: one observed shell's origin error, as a share of its flight distance.</summary>
                public static float ErrorShare = 0.2f;
                /// <summary>ai.fireMissions.mergeRadius (m): spec 144: estimates this close (plus error) are one battery.</summary>
                public static float MergeRadius = 30.0f;
                /// <summary>ai.fireMissions.halfLifeS (s): spec 128 / 144: an origin estimate's confidence half-life.</summary>
                public static float HalfLifeS = 20.0f;
                /// <summary>ai.fireMissions.missionConfidence (share): spec 144: a counter-battery mission from this confidence.</summary>
                public static float MissionConfidence = 0.6f;
                /// <summary>ai.fireMissions.strikeConfidence (share): spec 144: an unseen origin is area-fired (support barrage) from this confidence.</summary>
                public static float StrikeConfidence = 0.7f;
                /// <summary>ai.fireMissions.strikeMaxError (m): spec 144: no area fire on an estimate wider than this.</summary>
                public static float StrikeMaxError = 25.0f;
                /// <summary>ai.fireMissions.staleSeconds (s): spec 143: no barrage on a remembered position older than this.</summary>
                public static float StaleSeconds = 4.0f;
                /// <summary>ai.fireMissions.maxGunsPerTarget (count): spec 143: guns one mission may take.</summary>
                public static int MaxGunsPerTarget = 2;
                /// <summary>ai.fireMissions.scootSalvos (count): spec 145 / 218 artilleryScootMin/MaxSalvos.</summary>
                public static int[] ScootSalvos = { 2, 4 };
                /// <summary>ai.fireMissions.scootDistance (m): spec 145 / 218 artilleryScootMin/MaxM.</summary>
                public static float[] ScootDistance = { 12.0f, 30.0f };
                /// <summary>ai.fireMissions.threatRadius (m): spec 145: enemy shells landing this close to a gun are a counter-battery threat.</summary>
                public static float ThreatRadius = 25.0f;
                /// <summary>ai.fireMissions.impactMemoryS (s): spec 145 / 213: observed impacts are remembered this long.</summary>
                public static float ImpactMemoryS = 8.0f;
                /// <summary>ai.fireMissions.frontMargin (m): spec 145: a scoot spot stays this far behind the frontline.</summary>
                public static float FrontMargin = 15.0f;
                /// <summary>ai.fireMissions.chokeMargin (m): spec 145: a scoot spot stays this far outside a choke.</summary>
                public static float ChokeMargin = 4.0f;
            }

            /// <summary>Spec 146-148, 206, 223: pursuit discipline, interception, cutoff, bait resistance.</summary>
            public static partial class Pursuit
            {
                /// <summary>ai.pursuit.maxSeconds (s): spec 148: max pursuit seconds.</summary>
                public static float MaxSeconds = 20.0f;
                /// <summary>ai.pursuit.maxDistance (m): spec 148: max pursuit distance from the task anchor.</summary>
                public static float MaxDistance = 60.0f;
                /// <summary>ai.pursuit.aaMaxSeconds (s): spec 148: an AA squad's pursuit seconds (no chase across the map).</summary>
                public static float AaMaxSeconds = 10.0f;
                /// <summary>ai.pursuit.aaMaxDistance (m): spec 148: an AA squad's pursuit distance.</summary>
                public static float AaMaxDistance = 40.0f;
                /// <summary>ai.pursuit.urgencyDrop (share): spec 223: over this urgency a target that does not threaten the objective is dropped.</summary>
                public static float UrgencyDrop = 0.75f;
                /// <summary>ai.pursuit.horizonS (s): spec 146: intercept horizon.</summary>
                public static float HorizonS = 6.0f;
                /// <summary>ai.pursuit.ageFadeS (s): spec 146: a hidden target's extrapolation fades over this (uncertainty grows).</summary>
                public static float AgeFadeS = 4.0f;
                /// <summary>ai.pursuit.cutoffConfidence (share): spec 147: route confidence needed for a cutoff.</summary>
                public static float CutoffConfidence = 0.6f;
                /// <summary>ai.pursuit.cutoffLookS (s): spec 147: how far ahead an enemy group's way is followed to a choke.</summary>
                public static float CutoffLookS = 20.0f;
                /// <summary>ai.pursuit.retrySeconds (s): spec 148: a dropped pursuit is not taken up again for this long.</summary>
                public static float RetrySeconds = 10.0f;
                /// <summary>ai.pursuit.baitLeashMin (x): spec 206: the leash never shrinks under this share.</summary>
                public static float BaitLeashMin = 0.4f;
                /// <summary>ai.pursuit.baitDangerScale (x): spec 206: leash shrink per unit of recent-death danger round the chase.</summary>
                public static float BaitDangerScale = 0.5f;
            }

            /// <summary>Spec 151: preferred max = range - margin.</summary>
            public static partial class RangeMargin
            {
                /// <summary>ai.rangeMargin.direct (share): spec 151: direct gun (3-6 %).</summary>
                public static float Direct = 0.045f;
                /// <summary>ai.rangeMargin.artillery (share): spec 151: artillery (5-10 %).</summary>
                public static float Artillery = 0.075f;
                /// <summary>ai.rangeMargin.atgm (share): spec 151: ATGM (~5 %).</summary>
                public static float Atgm = 0.05f;
                /// <summary>ai.rangeMargin.aaMissile (share): spec 151: AA missile (5-8 %).</summary>
                public static float AaMissile = 0.065f;
            }

            /// <summary>Spec 170: reserve release order and the won-fight guard.</summary>
            public static partial class ReserveRelease
            {
                /// <summary>ai.reserveRelease.wonRatio (x): spec 170: own / enemy at the spot this high: the fight is won, no release.</summary>
                public static float WonRatio = 2.0f;
                /// <summary>ai.reserveRelease.collapseRatio (x): spec 170: own / enemy at the primary objective under this: collapse.</summary>
                public static float CollapseRatio = 0.6f;
                /// <summary>ai.reserveRelease.breakthroughRatio (x): spec 170: enemy / own on a front segment over this, moving in: breakthrough.</summary>
                public static float BreakthroughRatio = 1.5f;
                /// <summary>ai.reserveRelease.exploitConfidence (share): spec 170: a high-value exploit needs this event confidence.</summary>
                public static float ExploitConfidence = 0.5f;
            }

            /// <summary>Spec 171, 172, 207, 210-212: economy of force, sunk cost, deadlines, depth, counterattack.</summary>
            public static partial class Objectives
            {
                /// <summary>ai.objectives.deadlineSlack (x): spec 207: a squad whose ETA is over the deadline x this is not sent.</summary>
                public static float DeadlineSlack = 1.1f;
                /// <summary>ai.objectives.sunkHalfLifeS (s): spec 172: losses at an objective fade with this half-life.</summary>
                public static float SunkHalfLifeS = 90.0f;
                /// <summary>ai.objectives.sunkValue (CP): spec 172: an objective's future value (x 1 + urgency).</summary>
                public static float SunkValue = 60.0f;
                /// <summary>ai.objectives.sunkResetS (s): spec 172: after a reset no reinforcement is sent there for this long.</summary>
                public static float SunkResetS = 30.0f;
                /// <summary>ai.objectives.depthLines (count): spec 211: hold lines of a defence (2-3).</summary>
                public static int DepthLines = 3;
                /// <summary>ai.objectives.depthStep (share): spec 211: each line this share further from the objective towards home.</summary>
                public static float DepthStep = 0.3f;
                /// <summary>ai.objectives.depthLostS (s): spec 211: a line counts as lost after the enemy holds it this long.</summary>
                public static float DepthLostS = 5.0f;
                /// <summary>ai.objectives.counterLossShare (share): spec 212: observed enemy losses over this share of its local power open a window.</summary>
                public static float CounterLossShare = 0.35f;
                /// <summary>ai.objectives.counterWindowS (s): spec 212: how long the counterattack window lasts.</summary>
                public static float CounterWindowS = 8.0f;
                /// <summary>ai.objectives.counterLookS (s): spec 212: losses within this many seconds count together.</summary>
                public static float CounterLookS = 6.0f;
                /// <summary>ai.objectives.counterRadius (m): spec 212: losses within this of each other count together.</summary>
                public static float CounterRadius = 40.0f;
                /// <summary>ai.objectives.economyDelayShare (x): spec 171: a secondary gets the enemy strength there x this (delay / screen / contest).</summary>
                public static float EconomyDelayShare = 0.8f;
                /// <summary>ai.objectives.economyMaxShare (share): spec 171: at most this share of the army on secondaries while the primary is decisive.</summary>
                public static float EconomyMaxShare = 0.3f;
                /// <summary>ai.objectives.splitMinMembers (count): P2 22: a squad this big may split for a second simultaneous objective.</summary>
                public static int SplitMinMembers = 6;
            }

            /// <summary>Spec 141, 169: AA coverage reservation and the coverage optimiser.</summary>
            public static partial class Coverage
            {
                /// <summary>ai.coverage.updateS (s): coverage assignments are made this often.</summary>
                public static float UpdateS = 2.0f;
                /// <summary>ai.coverage.reachShare (share): spec 169: candidate spots this share of the AA reach from the asset.</summary>
                public static float ReachShare = 0.4f;
                /// <summary>ai.coverage.exposureWeight (x): spec 169 Exposure.</summary>
                public static float ExposureWeight = 1.0f;
                /// <summary>ai.coverage.congestionWeight (x): spec 169 Congestion.</summary>
                public static float CongestionWeight = 0.5f;
                /// <summary>ai.coverage.redundantWeight (x): spec 169 RedundantCoverage.</summary>
                public static float RedundantWeight = 0.5f;
                /// <summary>ai.coverage.assetWorth (x): spec 141: boss, main force, artillery, objective cover worth.</summary>
                public static float[] AssetWorth = { 4.0f, 2.0f, 3.0f, 1.5f };
                /// <summary>ai.coverage.coverWorth (x): spec 141: an aircraft over the AA's own asset.</summary>
                public static float CoverWorth = 1.4f;
                /// <summary>ai.coverage.offWorth (x): spec 141: an aircraft away from the AA's asset.</summary>
                public static float OffWorth = 0.8f;
            }

            /// <summary>Spec 149, 205, 213: internal stances, ambush discipline, dispersion timing.</summary>
            public static partial class Stance
            {
                /// <summary>ai.stance.returnFireSeconds (s): spec 149 ReturnFire: free to fire this long after being hit.</summary>
                public static float ReturnFireSeconds = 3.0f;
                /// <summary>ai.stance.ambushRange (share): spec 205: an ambush opens with the enemy inside this share of its effective range.</summary>
                public static float[] AmbushRange = { 0.55f, 0.7f };
                /// <summary>ai.stance.ambushSyncRadius (m): spec 205: ambush squads this close open fire together.</summary>
                public static float AmbushSyncRadius = 60.0f;
                /// <summary>ai.stance.highValueReach (share): spec 205: a high-value target this deep in reach opens the ambush.</summary>
                public static float HighValueReach = 0.85f;
                /// <summary>ai.stance.dispersalHoldS (s): spec 213: no regroup for this long after enemy shells landed near the squad.</summary>
                public static float DispersalHoldS = 8.0f;
            }
        }

        private static readonly Entry[] AiMasterP3 =
        {
            new Entry("ai.coordination.enabled", "flag", () => Ai.Coordination.Enabled ? 1 : 0, v => Ai.Coordination.Enabled = v >= 0.5, flag: true),
            new Entry("ai.coordination.frontlineUpdateS", "s", () => Ai.Coordination.FrontlineUpdateS, v => Ai.Coordination.FrontlineUpdateS = (float)v),
            new Entry("ai.coordination.localRadius", "m", () => Ai.Coordination.LocalRadius, v => Ai.Coordination.LocalRadius = (float)v),
            new Entry("ai.memory.mobileHalfLifeS", "s", () => Ai.Memory.MobileHalfLifeS, v => Ai.Memory.MobileHalfLifeS = (float)v),
            new Entry("ai.memory.artilleryHalfLifeS", "s", () => Ai.Memory.ArtilleryHalfLifeS, v => Ai.Memory.ArtilleryHalfLifeS = (float)v),
            new Entry("ai.memory.staticHalfLifeS", "s", () => Ai.Memory.StaticHalfLifeS, v => Ai.Memory.StaticHalfLifeS = (float)v),
            new Entry("ai.memory.absentDecay", "x", () => Ai.Memory.AbsentDecay, v => Ai.Memory.AbsentDecay = (float)v),
            new Entry("ai.memory.deathHalfLifeS", "s", () => Ai.Memory.DeathHalfLifeS, v => Ai.Memory.DeathHalfLifeS = (float)v),
            new Entry("ai.memory.deathRadius", "m", () => Ai.Memory.DeathRadius, v => Ai.Memory.DeathRadius = (float)v),
            new Entry("ai.memory.unknownSeconds", "s", () => Ai.Memory.UnknownSeconds, v => Ai.Memory.UnknownSeconds = (float)v),
            Entry.FloatArray("ai.memory.unknownRisk", "x", () => Ai.Memory.UnknownRisk, v => Ai.Memory.UnknownRisk = v),
            new Entry("ai.memory.repeatPlanPenalty", "x", () => Ai.Memory.RepeatPlanPenalty, v => Ai.Memory.RepeatPlanPenalty = (float)v),
            new Entry("ai.memory.repeatPlanHalfLifeS", "s", () => Ai.Memory.RepeatPlanHalfLifeS, v => Ai.Memory.RepeatPlanHalfLifeS = (float)v),
            new Entry("ai.memory.routeFailShare", "share", () => Ai.Memory.RouteFailShare, v => Ai.Memory.RouteFailShare = (float)v),
            Entry.FloatArray("ai.confidence.weights", "share", () => Ai.Confidence.Weights, v => Ai.Confidence.Weights = v),
            new Entry("ai.confidence.aggressive", "share", () => Ai.Confidence.Aggressive, v => Ai.Confidence.Aggressive = (float)v),
            new Entry("ai.confidence.cautious", "share", () => Ai.Confidence.Cautious, v => Ai.Confidence.Cautious = (float)v),
            new Entry("ai.confidence.noCommit", "share", () => Ai.Confidence.NoCommit, v => Ai.Confidence.NoCommit = (float)v),
            new Entry("ai.confidence.points", "points", () => Ai.Confidence.Points, v => Ai.Confidence.Points = (float)v),
            new Entry("ai.routes.distanceScale", "m", () => Ai.Routes.DistanceScale, v => Ai.Routes.DistanceScale = (float)v),
            new Entry("ai.routes.congestionWeight", "x", () => Ai.Routes.CongestionWeight, v => Ai.Routes.CongestionWeight = (float)v),
            new Entry("ai.routes.occupancyWeight", "x", () => Ai.Routes.OccupancyWeight, v => Ai.Routes.OccupancyWeight = (float)v),
            new Entry("ai.routes.lossWeight", "x", () => Ai.Routes.LossWeight, v => Ai.Routes.LossWeight = (float)v),
            new Entry("ai.routes.points", "points", () => Ai.Routes.Points, v => Ai.Routes.Points = (float)v),
            new Entry("ai.routes.occupancyRadius", "m", () => Ai.Routes.OccupancyRadius, v => Ai.Routes.OccupancyRadius = (float)v),
            new Entry("ai.routes.bookSeconds", "s", () => Ai.Routes.BookSeconds, v => Ai.Routes.BookSeconds = (float)v),
            new Entry("ai.attackSync.groundToleranceS", "s", () => Ai.AttackSync.GroundToleranceS, v => Ai.AttackSync.GroundToleranceS = (float)v),
            new Entry("ai.attackSync.airToleranceS", "s", () => Ai.AttackSync.AirToleranceS, v => Ai.AttackSync.AirToleranceS = (float)v),
            new Entry("ai.attackSync.artilleryPrepLeadS", "s", () => Ai.AttackSync.ArtilleryPrepLeadS, v => Ai.AttackSync.ArtilleryPrepLeadS = (float)v),
            new Entry("ai.attackSync.detour", "x", () => Ai.AttackSync.Detour, v => Ai.AttackSync.Detour = (float)v),
            new Entry("ai.attackSync.packageSeconds", "s", () => Ai.AttackSync.PackageSeconds, v => Ai.AttackSync.PackageSeconds = (float)v),
            new Entry("ai.attackSync.stagingBand", "m", () => Ai.AttackSync.StagingBand, v => Ai.AttackSync.StagingBand = (float)v),
            new Entry("ai.attackSync.subZoneSpacing", "m", () => Ai.AttackSync.SubZoneSpacing, v => Ai.AttackSync.SubZoneSpacing = (float)v),
            new Entry("ai.attackSync.maxStageS", "s", () => Ai.AttackSync.MaxStageS, v => Ai.AttackSync.MaxStageS = (float)v),
            new Entry("ai.attackSync.scoutMaxWaitS", "s", () => Ai.AttackSync.ScoutMaxWaitS, v => Ai.AttackSync.ScoutMaxWaitS = (float)v),
            new Entry("ai.attackSync.scoutUnknownShare", "share", () => Ai.AttackSync.ScoutUnknownShare, v => Ai.AttackSync.ScoutUnknownShare = (float)v),
            new Entry("ai.attackSync.scoutDeathDanger", "x", () => Ai.AttackSync.ScoutDeathDanger, v => Ai.AttackSync.ScoutDeathDanger = (float)v),
            new Entry("ai.attackSync.fixEnvelope", "share", () => Ai.AttackSync.FixEnvelope, v => Ai.AttackSync.FixEnvelope = (float)v),
            new Entry("ai.attackSync.frontageSeparation", "m", () => Ai.AttackSync.FrontageSeparation, v => Ai.AttackSync.FrontageSeparation = (float)v),
            new Entry("ai.attackSync.waveGapS", "s", () => Ai.AttackSync.WaveGapS, v => Ai.AttackSync.WaveGapS = (float)v),
            new Entry("ai.attackSync.defaultFrontage", "m", () => Ai.AttackSync.DefaultFrontage, v => Ai.AttackSync.DefaultFrontage = (float)v),
            new Entry("ai.board.plannedOverkillShare", "x", () => Ai.Board.PlannedOverkillShare, v => Ai.Board.PlannedOverkillShare = (float)v),
            new Entry("ai.board.damageLeadS", "s", () => Ai.Board.DamageLeadS, v => Ai.Board.DamageLeadS = (float)v),
            new Entry("ai.board.repairWindowS", "s", () => Ai.Board.RepairWindowS, v => Ai.Board.RepairWindowS = (float)v),
            new Entry("ai.board.smokeSpacing", "m", () => Ai.Board.SmokeSpacing, v => Ai.Board.SmokeSpacing = (float)v),
            new Entry("ai.board.smokeSeconds", "s", () => Ai.Board.SmokeSeconds, v => Ai.Board.SmokeSeconds = (float)v),
            new Entry("ai.board.handoffRatio", "x", () => Ai.Board.HandoffRatio, v => Ai.Board.HandoffRatio = (float)v),
            new Entry("ai.board.handoffLockS", "s", () => Ai.Board.HandoffLockS, v => Ai.Board.HandoffLockS = (float)v),
            new Entry("ai.board.preferWorth", "x", () => Ai.Board.PreferWorth, v => Ai.Board.PreferWorth = (float)v),
            new Entry("ai.board.avoidWorth", "x", () => Ai.Board.AvoidWorth, v => Ai.Board.AvoidWorth = (float)v),
            new Entry("ai.board.spreadFocusShare", "x", () => Ai.Board.SpreadFocusShare, v => Ai.Board.SpreadFocusShare = (float)v),
            new Entry("ai.board.nearKillShare", "share", () => Ai.Board.NearKillShare, v => Ai.Board.NearKillShare = (float)v),
            new Entry("ai.board.secondaryHeavy", "x", () => Ai.Board.SecondaryHeavy, v => Ai.Board.SecondaryHeavy = (float)v),
            new Entry("ai.board.secondaryFit", "x", () => Ai.Board.SecondaryFit, v => Ai.Board.SecondaryFit = (float)v),
            new Entry("ai.fireMissions.minError", "m", () => Ai.FireMissions.MinError, v => Ai.FireMissions.MinError = (float)v),
            new Entry("ai.fireMissions.errorShare", "share", () => Ai.FireMissions.ErrorShare, v => Ai.FireMissions.ErrorShare = (float)v),
            new Entry("ai.fireMissions.mergeRadius", "m", () => Ai.FireMissions.MergeRadius, v => Ai.FireMissions.MergeRadius = (float)v),
            new Entry("ai.fireMissions.halfLifeS", "s", () => Ai.FireMissions.HalfLifeS, v => Ai.FireMissions.HalfLifeS = (float)v),
            new Entry("ai.fireMissions.missionConfidence", "share", () => Ai.FireMissions.MissionConfidence, v => Ai.FireMissions.MissionConfidence = (float)v),
            new Entry("ai.fireMissions.strikeConfidence", "share", () => Ai.FireMissions.StrikeConfidence, v => Ai.FireMissions.StrikeConfidence = (float)v),
            new Entry("ai.fireMissions.strikeMaxError", "m", () => Ai.FireMissions.StrikeMaxError, v => Ai.FireMissions.StrikeMaxError = (float)v),
            new Entry("ai.fireMissions.staleSeconds", "s", () => Ai.FireMissions.StaleSeconds, v => Ai.FireMissions.StaleSeconds = (float)v),
            new Entry("ai.fireMissions.maxGunsPerTarget", "count", () => Ai.FireMissions.MaxGunsPerTarget, v => Ai.FireMissions.MaxGunsPerTarget = (int)Math.Round(v)),
            Entry.IntArray("ai.fireMissions.scootSalvos", "count", () => Ai.FireMissions.ScootSalvos, v => Ai.FireMissions.ScootSalvos = v),
            Entry.FloatArray("ai.fireMissions.scootDistance", "m", () => Ai.FireMissions.ScootDistance, v => Ai.FireMissions.ScootDistance = v),
            new Entry("ai.fireMissions.threatRadius", "m", () => Ai.FireMissions.ThreatRadius, v => Ai.FireMissions.ThreatRadius = (float)v),
            new Entry("ai.fireMissions.impactMemoryS", "s", () => Ai.FireMissions.ImpactMemoryS, v => Ai.FireMissions.ImpactMemoryS = (float)v),
            new Entry("ai.fireMissions.frontMargin", "m", () => Ai.FireMissions.FrontMargin, v => Ai.FireMissions.FrontMargin = (float)v),
            new Entry("ai.fireMissions.chokeMargin", "m", () => Ai.FireMissions.ChokeMargin, v => Ai.FireMissions.ChokeMargin = (float)v),
            new Entry("ai.pursuit.maxSeconds", "s", () => Ai.Pursuit.MaxSeconds, v => Ai.Pursuit.MaxSeconds = (float)v),
            new Entry("ai.pursuit.maxDistance", "m", () => Ai.Pursuit.MaxDistance, v => Ai.Pursuit.MaxDistance = (float)v),
            new Entry("ai.pursuit.aaMaxSeconds", "s", () => Ai.Pursuit.AaMaxSeconds, v => Ai.Pursuit.AaMaxSeconds = (float)v),
            new Entry("ai.pursuit.aaMaxDistance", "m", () => Ai.Pursuit.AaMaxDistance, v => Ai.Pursuit.AaMaxDistance = (float)v),
            new Entry("ai.pursuit.urgencyDrop", "share", () => Ai.Pursuit.UrgencyDrop, v => Ai.Pursuit.UrgencyDrop = (float)v),
            new Entry("ai.pursuit.horizonS", "s", () => Ai.Pursuit.HorizonS, v => Ai.Pursuit.HorizonS = (float)v),
            new Entry("ai.pursuit.ageFadeS", "s", () => Ai.Pursuit.AgeFadeS, v => Ai.Pursuit.AgeFadeS = (float)v),
            new Entry("ai.pursuit.cutoffConfidence", "share", () => Ai.Pursuit.CutoffConfidence, v => Ai.Pursuit.CutoffConfidence = (float)v),
            new Entry("ai.pursuit.cutoffLookS", "s", () => Ai.Pursuit.CutoffLookS, v => Ai.Pursuit.CutoffLookS = (float)v),
            new Entry("ai.pursuit.retrySeconds", "s", () => Ai.Pursuit.RetrySeconds, v => Ai.Pursuit.RetrySeconds = (float)v),
            new Entry("ai.pursuit.baitLeashMin", "x", () => Ai.Pursuit.BaitLeashMin, v => Ai.Pursuit.BaitLeashMin = (float)v),
            new Entry("ai.pursuit.baitDangerScale", "x", () => Ai.Pursuit.BaitDangerScale, v => Ai.Pursuit.BaitDangerScale = (float)v),
            new Entry("ai.rangeMargin.direct", "share", () => Ai.RangeMargin.Direct, v => Ai.RangeMargin.Direct = (float)v),
            new Entry("ai.rangeMargin.artillery", "share", () => Ai.RangeMargin.Artillery, v => Ai.RangeMargin.Artillery = (float)v),
            new Entry("ai.rangeMargin.atgm", "share", () => Ai.RangeMargin.Atgm, v => Ai.RangeMargin.Atgm = (float)v),
            new Entry("ai.rangeMargin.aaMissile", "share", () => Ai.RangeMargin.AaMissile, v => Ai.RangeMargin.AaMissile = (float)v),
            new Entry("ai.reserveRelease.wonRatio", "x", () => Ai.ReserveRelease.WonRatio, v => Ai.ReserveRelease.WonRatio = (float)v),
            new Entry("ai.reserveRelease.collapseRatio", "x", () => Ai.ReserveRelease.CollapseRatio, v => Ai.ReserveRelease.CollapseRatio = (float)v),
            new Entry("ai.reserveRelease.breakthroughRatio", "x", () => Ai.ReserveRelease.BreakthroughRatio, v => Ai.ReserveRelease.BreakthroughRatio = (float)v),
            new Entry("ai.reserveRelease.exploitConfidence", "share", () => Ai.ReserveRelease.ExploitConfidence, v => Ai.ReserveRelease.ExploitConfidence = (float)v),
            new Entry("ai.objectives.deadlineSlack", "x", () => Ai.Objectives.DeadlineSlack, v => Ai.Objectives.DeadlineSlack = (float)v),
            new Entry("ai.objectives.sunkHalfLifeS", "s", () => Ai.Objectives.SunkHalfLifeS, v => Ai.Objectives.SunkHalfLifeS = (float)v),
            new Entry("ai.objectives.sunkValue", "CP", () => Ai.Objectives.SunkValue, v => Ai.Objectives.SunkValue = (float)v),
            new Entry("ai.objectives.sunkResetS", "s", () => Ai.Objectives.SunkResetS, v => Ai.Objectives.SunkResetS = (float)v),
            new Entry("ai.objectives.depthLines", "count", () => Ai.Objectives.DepthLines, v => Ai.Objectives.DepthLines = (int)Math.Round(v)),
            new Entry("ai.objectives.depthStep", "share", () => Ai.Objectives.DepthStep, v => Ai.Objectives.DepthStep = (float)v),
            new Entry("ai.objectives.depthLostS", "s", () => Ai.Objectives.DepthLostS, v => Ai.Objectives.DepthLostS = (float)v),
            new Entry("ai.objectives.counterLossShare", "share", () => Ai.Objectives.CounterLossShare, v => Ai.Objectives.CounterLossShare = (float)v),
            new Entry("ai.objectives.counterWindowS", "s", () => Ai.Objectives.CounterWindowS, v => Ai.Objectives.CounterWindowS = (float)v),
            new Entry("ai.objectives.counterLookS", "s", () => Ai.Objectives.CounterLookS, v => Ai.Objectives.CounterLookS = (float)v),
            new Entry("ai.objectives.counterRadius", "m", () => Ai.Objectives.CounterRadius, v => Ai.Objectives.CounterRadius = (float)v),
            new Entry("ai.objectives.economyDelayShare", "x", () => Ai.Objectives.EconomyDelayShare, v => Ai.Objectives.EconomyDelayShare = (float)v),
            new Entry("ai.objectives.economyMaxShare", "share", () => Ai.Objectives.EconomyMaxShare, v => Ai.Objectives.EconomyMaxShare = (float)v),
            new Entry("ai.objectives.splitMinMembers", "count", () => Ai.Objectives.SplitMinMembers, v => Ai.Objectives.SplitMinMembers = (int)Math.Round(v)),
            new Entry("ai.coverage.updateS", "s", () => Ai.Coverage.UpdateS, v => Ai.Coverage.UpdateS = (float)v),
            new Entry("ai.coverage.reachShare", "share", () => Ai.Coverage.ReachShare, v => Ai.Coverage.ReachShare = (float)v),
            new Entry("ai.coverage.exposureWeight", "x", () => Ai.Coverage.ExposureWeight, v => Ai.Coverage.ExposureWeight = (float)v),
            new Entry("ai.coverage.congestionWeight", "x", () => Ai.Coverage.CongestionWeight, v => Ai.Coverage.CongestionWeight = (float)v),
            new Entry("ai.coverage.redundantWeight", "x", () => Ai.Coverage.RedundantWeight, v => Ai.Coverage.RedundantWeight = (float)v),
            Entry.FloatArray("ai.coverage.assetWorth", "x", () => Ai.Coverage.AssetWorth, v => Ai.Coverage.AssetWorth = v),
            new Entry("ai.coverage.coverWorth", "x", () => Ai.Coverage.CoverWorth, v => Ai.Coverage.CoverWorth = (float)v),
            new Entry("ai.coverage.offWorth", "x", () => Ai.Coverage.OffWorth, v => Ai.Coverage.OffWorth = (float)v),
            new Entry("ai.stance.returnFireSeconds", "s", () => Ai.Stance.ReturnFireSeconds, v => Ai.Stance.ReturnFireSeconds = (float)v),
            Entry.FloatArray("ai.stance.ambushRange", "share", () => Ai.Stance.AmbushRange, v => Ai.Stance.AmbushRange = v),
            new Entry("ai.stance.ambushSyncRadius", "m", () => Ai.Stance.AmbushSyncRadius, v => Ai.Stance.AmbushSyncRadius = (float)v),
            new Entry("ai.stance.highValueReach", "share", () => Ai.Stance.HighValueReach, v => Ai.Stance.HighValueReach = (float)v),
            new Entry("ai.stance.dispersalHoldS", "s", () => Ai.Stance.DispersalHoldS, v => Ai.Stance.DispersalHoldS = (float)v),
        };
    }
}
