// Generated by Tools/export/mbconst (move), balance pack 2. Each field is a literal that was in the code ("was":
// where); the defaults equal those literals. Edit Resources/Data/tunables.json, not this file.
// AI MASTER P0-C (lane C): the boss brain's values (spec sections 33, 48-66, 202-203) were added here by hand, same rules.
#nullable enable

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Bosses
        {
            /// <summary>AI MASTER P0-C: the boss brain (Sim/Bosses/Brain): mission anchor, hull vs turrets, naval steering, escorts, cadence.</summary>
            public static partial class BossBrain
            {
                /// <summary>bosses.bossBrain.brainTicks (ticks): the brain's slower decisions (broadside, active DPS, anchor) run every this many steps.</summary>
                public static int BrainTicks = 2;
                /// <summary>bosses.bossBrain.lookAheadSeconds (s): spec 54, look-ahead = clamp(speed x this, length x min, length x max).</summary>
                public static float LookAheadSeconds = 6f;
                /// <summary>bosses.bossBrain.lookAheadMinLengths (x): spec 54, the look-ahead's floor in hull lengths.</summary>
                public static float LookAheadMinLengths = 1.5f;
                /// <summary>bosses.bossBrain.lookAheadMaxLengths (x): spec 54, the look-ahead's cap in hull lengths.</summary>
                public static float LookAheadMaxLengths = 4f;
                /// <summary>bosses.bossBrain.planningFactor (x): spec 53, planningRadius = max(collision radius, Rmin x this).</summary>
                public static float PlanningFactor = 1.1f;
                /// <summary>bosses.bossBrain.headingDeadbandDeg (deg): spec 55, a new desired hull offset within this of the held one is ignored.</summary>
                public static float HeadingDeadbandDeg = 5f;
                /// <summary>bosses.bossBrain.broadsideEnterDeg (deg): spec 55, broadside held once the hull is within this of it.</summary>
                public static float BroadsideEnterDeg = 8f;
                /// <summary>bosses.bossBrain.broadsideLeaveDeg (deg): spec 55, a held broadside changes only for an offset this far from it.</summary>
                public static float BroadsideLeaveDeg = 15f;
                /// <summary>bosses.bossBrain.broadsideSmoothing (share): spec 57, desired offset = lerp(previous, best, this) per brain tick.</summary>
                public static float BroadsideSmoothing = 0.15f;
                /// <summary>bosses.bossBrain.broadsideMaxDeg (deg): spec 56, hull offsets sampled from -this to +this.</summary>
                public static float BroadsideMaxDeg = 80f;
                /// <summary>bosses.bossBrain.broadsideStepDeg (deg): spec 56, the sampling step (-80 -60 ... +80).</summary>
                public static float BroadsideStepDeg = 20f;
                /// <summary>bosses.bossBrain.broadsideTurnCost (share): spec 104's turn cost, at the widest offset, in shares of the boss's DPS.</summary>
                public static float BroadsideTurnCost = 0.08f;
                /// <summary>bosses.bossBrain.broadsideRoutePenalty (share): spec 56 "does not break the route": cost of leaving the lane corridor.</summary>
                public static float BroadsideRoutePenalty = 0.25f;
                /// <summary>bosses.bossBrain.activeDpsTarget (share): spec 202, the bearing DPS share the broadside keeps when the route allows (not a lock).</summary>
                public static float ActiveDpsTarget = 0.65f;
                /// <summary>bosses.bossBrain.holdBonus (share): spec 202, the held offset's bonus while it already bears the target share.</summary>
                public static float HoldBonus = 0.05f;
                /// <summary>bosses.bossBrain.cruiseThrottleMin (share): a boss ship steering under way keeps at least this share of its speed (turn radius kept).</summary>
                public static float CruiseThrottleMin = 0.6f;
                /// <summary>bosses.bossBrain.turnaboutThrottle (share): spec 52 "slow down, turn harder": a ship coming about (goal behind) slows to this share.</summary>
                public static float TurnaboutThrottle = 0.25f;
                /// <summary>bosses.bossBrain.cpaHorizonMin (s): spec 60, the closest-approach look-ahead for a short ship.</summary>
                public static float CpaHorizonMin = 6f;
                /// <summary>bosses.bossBrain.cpaHorizonMax (s): spec 60, the closest-approach look-ahead for a long ship.</summary>
                public static float CpaHorizonMax = 10f;
                /// <summary>bosses.bossBrain.cpaLateralClear (m): spec 60, hulls passing closer than their half widths + this across are on a collision course.</summary>
                public static float CpaLateralClear = 2.5f;
                /// <summary>bosses.bossBrain.shipSeparationExtra (m): spec 59, friendly separation max(rA + rB + this, half the longer hull).</summary>
                public static float ShipSeparationExtra = 4f;
                /// <summary>bosses.bossBrain.bossSeparationExtra (m): spec 59, a boss ship's separation is this much more (8-15 m).</summary>
                public static float BossSeparationExtra = 10f;
                /// <summary>bosses.bossBrain.cpaMaxTurnDeg (deg): spec 60, the early turn away at its most.</summary>
                public static float CpaMaxTurnDeg = 25f;
                /// <summary>bosses.bossBrain.cpaMinThrottle (share): spec 60, the slow-down at its most.</summary>
                public static float CpaMinThrottle = 0.35f;
                /// <summary>bosses.bossBrain.corridorMargin (m): spec 33, a boss's corridor half width = half its width + this.</summary>
                public static float CorridorMargin = 2.5f;
                /// <summary>bosses.bossBrain.corridorClearMin (m): spec 33, friends clear its corridor this far ahead at least.</summary>
                public static float CorridorClearMin = 25f;
                /// <summary>bosses.bossBrain.corridorClearMax (m): spec 33, ... and at most this far (25 + 2 s of its speed, capped).</summary>
                public static float CorridorClearMax = 35f;
                /// <summary>bosses.bossBrain.corridorTicks (ticks): friends standing in a boss's corridor are asked to clear it every this many steps.</summary>
                public static int CorridorTicks = 5;
                /// <summary>bosses.bossBrain.escortInnerGap (m): spec 66, no escort station inside the boss's radius + this.</summary>
                public static float EscortInnerGap = 4f;
                /// <summary>bosses.bossBrain.escortScreenMin (m): spec 66, the screen ring from the boss's radius + this ...</summary>
                public static float EscortScreenMin = 10f;
                /// <summary>bosses.bossBrain.escortScreenMax (m): ... to + this.</summary>
                public static float EscortScreenMax = 18f;
                /// <summary>bosses.bossBrain.escortSupportMin (m): spec 66, the support ring from the boss's radius + this ...</summary>
                public static float EscortSupportMin = 18f;
                /// <summary>bosses.bossBrain.escortSupportMax (m): ... to + this.</summary>
                public static float EscortSupportMax = 30f;
                /// <summary>bosses.bossBrain.cadenceGap (s): spec 203, two different heavy weapons of a boss open fire at least this far apart.</summary>
                public static float CadenceGap = 0.35f;
                /// <summary>bosses.bossBrain.cadenceHeavyCooldown (s): spec 203, a weapon this slow (or slower) counts as heavy.</summary>
                public static float CadenceHeavyCooldown = 1f;
                /// <summary>bosses.bossBrain.chaseLeash (m): spec 49, a boss leaves its way for a target only this near it (anchor before target).</summary>
                public static float ChaseLeash = 30f;
                /// <summary>bosses.bossBrain.groundReverseCooldown (s): spec 63, a ground boss designed to reverse backs up at most once in this time.</summary>
                public static float GroundReverseCooldown = 8f;
                /// <summary>bosses.bossBrain.phaseMoveSeconds (s): spec 62, the new route goal of a phase owns the hull this long.</summary>
                public static float PhaseMoveSeconds = 3f;
                /// <summary>bosses.bossBrain.alignFlipSeconds (s): spec 64, a hull alignment more than 120 deg from the last one waits this long.</summary>
                public static float AlignFlipSeconds = 3f;
            }
        }

        private static readonly Entry[] Pack2Bosses =
        {
            new Entry("bosses.bossBrain.brainTicks", "ticks", () => Bosses.BossBrain.BrainTicks, v => Bosses.BossBrain.BrainTicks = (int)System.Math.Round(v)),
            new Entry("bosses.bossBrain.lookAheadSeconds", "s", () => Bosses.BossBrain.LookAheadSeconds, v => Bosses.BossBrain.LookAheadSeconds = (float)v),
            new Entry("bosses.bossBrain.lookAheadMinLengths", "x", () => Bosses.BossBrain.LookAheadMinLengths, v => Bosses.BossBrain.LookAheadMinLengths = (float)v),
            new Entry("bosses.bossBrain.lookAheadMaxLengths", "x", () => Bosses.BossBrain.LookAheadMaxLengths, v => Bosses.BossBrain.LookAheadMaxLengths = (float)v),
            new Entry("bosses.bossBrain.planningFactor", "x", () => Bosses.BossBrain.PlanningFactor, v => Bosses.BossBrain.PlanningFactor = (float)v),
            new Entry("bosses.bossBrain.headingDeadbandDeg", "deg", () => Bosses.BossBrain.HeadingDeadbandDeg, v => Bosses.BossBrain.HeadingDeadbandDeg = (float)v),
            new Entry("bosses.bossBrain.broadsideEnterDeg", "deg", () => Bosses.BossBrain.BroadsideEnterDeg, v => Bosses.BossBrain.BroadsideEnterDeg = (float)v),
            new Entry("bosses.bossBrain.broadsideLeaveDeg", "deg", () => Bosses.BossBrain.BroadsideLeaveDeg, v => Bosses.BossBrain.BroadsideLeaveDeg = (float)v),
            new Entry("bosses.bossBrain.broadsideSmoothing", "share", () => Bosses.BossBrain.BroadsideSmoothing, v => Bosses.BossBrain.BroadsideSmoothing = (float)v),
            new Entry("bosses.bossBrain.broadsideMaxDeg", "deg", () => Bosses.BossBrain.BroadsideMaxDeg, v => Bosses.BossBrain.BroadsideMaxDeg = (float)v),
            new Entry("bosses.bossBrain.broadsideStepDeg", "deg", () => Bosses.BossBrain.BroadsideStepDeg, v => Bosses.BossBrain.BroadsideStepDeg = (float)v),
            new Entry("bosses.bossBrain.broadsideTurnCost", "share", () => Bosses.BossBrain.BroadsideTurnCost, v => Bosses.BossBrain.BroadsideTurnCost = (float)v),
            new Entry("bosses.bossBrain.broadsideRoutePenalty", "share", () => Bosses.BossBrain.BroadsideRoutePenalty, v => Bosses.BossBrain.BroadsideRoutePenalty = (float)v),
            new Entry("bosses.bossBrain.activeDpsTarget", "share", () => Bosses.BossBrain.ActiveDpsTarget, v => Bosses.BossBrain.ActiveDpsTarget = (float)v),
            new Entry("bosses.bossBrain.holdBonus", "share", () => Bosses.BossBrain.HoldBonus, v => Bosses.BossBrain.HoldBonus = (float)v),
            new Entry("bosses.bossBrain.cruiseThrottleMin", "share", () => Bosses.BossBrain.CruiseThrottleMin, v => Bosses.BossBrain.CruiseThrottleMin = (float)v),
            new Entry("bosses.bossBrain.turnaboutThrottle", "share", () => Bosses.BossBrain.TurnaboutThrottle, v => Bosses.BossBrain.TurnaboutThrottle = (float)v),
            new Entry("bosses.bossBrain.cpaHorizonMin", "s", () => Bosses.BossBrain.CpaHorizonMin, v => Bosses.BossBrain.CpaHorizonMin = (float)v),
            new Entry("bosses.bossBrain.cpaHorizonMax", "s", () => Bosses.BossBrain.CpaHorizonMax, v => Bosses.BossBrain.CpaHorizonMax = (float)v),
            new Entry("bosses.bossBrain.cpaLateralClear", "m", () => Bosses.BossBrain.CpaLateralClear, v => Bosses.BossBrain.CpaLateralClear = (float)v),
            new Entry("bosses.bossBrain.shipSeparationExtra", "m", () => Bosses.BossBrain.ShipSeparationExtra, v => Bosses.BossBrain.ShipSeparationExtra = (float)v),
            new Entry("bosses.bossBrain.bossSeparationExtra", "m", () => Bosses.BossBrain.BossSeparationExtra, v => Bosses.BossBrain.BossSeparationExtra = (float)v),
            new Entry("bosses.bossBrain.cpaMaxTurnDeg", "deg", () => Bosses.BossBrain.CpaMaxTurnDeg, v => Bosses.BossBrain.CpaMaxTurnDeg = (float)v),
            new Entry("bosses.bossBrain.cpaMinThrottle", "share", () => Bosses.BossBrain.CpaMinThrottle, v => Bosses.BossBrain.CpaMinThrottle = (float)v),
            new Entry("bosses.bossBrain.corridorMargin", "m", () => Bosses.BossBrain.CorridorMargin, v => Bosses.BossBrain.CorridorMargin = (float)v),
            new Entry("bosses.bossBrain.corridorClearMin", "m", () => Bosses.BossBrain.CorridorClearMin, v => Bosses.BossBrain.CorridorClearMin = (float)v),
            new Entry("bosses.bossBrain.corridorClearMax", "m", () => Bosses.BossBrain.CorridorClearMax, v => Bosses.BossBrain.CorridorClearMax = (float)v),
            new Entry("bosses.bossBrain.corridorTicks", "ticks", () => Bosses.BossBrain.CorridorTicks, v => Bosses.BossBrain.CorridorTicks = (int)System.Math.Round(v)),
            new Entry("bosses.bossBrain.escortInnerGap", "m", () => Bosses.BossBrain.EscortInnerGap, v => Bosses.BossBrain.EscortInnerGap = (float)v),
            new Entry("bosses.bossBrain.escortScreenMin", "m", () => Bosses.BossBrain.EscortScreenMin, v => Bosses.BossBrain.EscortScreenMin = (float)v),
            new Entry("bosses.bossBrain.escortScreenMax", "m", () => Bosses.BossBrain.EscortScreenMax, v => Bosses.BossBrain.EscortScreenMax = (float)v),
            new Entry("bosses.bossBrain.escortSupportMin", "m", () => Bosses.BossBrain.EscortSupportMin, v => Bosses.BossBrain.EscortSupportMin = (float)v),
            new Entry("bosses.bossBrain.escortSupportMax", "m", () => Bosses.BossBrain.EscortSupportMax, v => Bosses.BossBrain.EscortSupportMax = (float)v),
            new Entry("bosses.bossBrain.cadenceGap", "s", () => Bosses.BossBrain.CadenceGap, v => Bosses.BossBrain.CadenceGap = (float)v),
            new Entry("bosses.bossBrain.cadenceHeavyCooldown", "s", () => Bosses.BossBrain.CadenceHeavyCooldown, v => Bosses.BossBrain.CadenceHeavyCooldown = (float)v),
            new Entry("bosses.bossBrain.chaseLeash", "m", () => Bosses.BossBrain.ChaseLeash, v => Bosses.BossBrain.ChaseLeash = (float)v),
            new Entry("bosses.bossBrain.groundReverseCooldown", "s", () => Bosses.BossBrain.GroundReverseCooldown, v => Bosses.BossBrain.GroundReverseCooldown = (float)v),
            new Entry("bosses.bossBrain.phaseMoveSeconds", "s", () => Bosses.BossBrain.PhaseMoveSeconds, v => Bosses.BossBrain.PhaseMoveSeconds = (float)v),
            new Entry("bosses.bossBrain.alignFlipSeconds", "s", () => Bosses.BossBrain.AlignFlipSeconds, v => Bosses.BossBrain.AlignFlipSeconds = (float)v),
        };
    }
}
