// Generated by Tools/export/mbconst (move), balance pack 2. Each field is a literal that was in the code ("was":
// where); the defaults equal those literals. Edit Resources/Data/tunables.json, not this file.
#nullable enable

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Weapons
        {
            public static partial class Armour
            {
                /// <summary>weapons.armour.fragmentPenetration (level; sat_thuong, was Sim/Content/Armour.cs:115). penetration of a blast's fragments against vehicle armour</summary>
                public static int FragmentPenetration = 1;
            }
        }

        private static readonly Entry[] Pack2Weapons =
        {
            new Entry("weapons.armour.fragmentPenetration", "level", () => Weapons.Armour.FragmentPenetration, v => Weapons.Armour.FragmentPenetration = (int)System.Math.Round(v)),
        };
    }
}
