// Generated by Tools/export/mbconst (move), balance pack 2. Each field is a literal that was in the code ("was":
// where); the defaults equal those literals. Edit Resources/Data/tunables.json, not this file.
#nullable enable

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Vehicles
        {
            public static partial class GearSystem
            {
                /// <summary>vehicles.gearSystem.domeRadius (m; ban_kinh, was Sim/Abilities/GearSystem.cs:523). Aegis Dome: allies under fire within this radius count</summary>
                public static float DomeRadius = 10f;
                /// <summary>vehicles.gearSystem.domeUnderFireSeconds (s; thoi_gian, was Sim/Abilities/GearSystem.cs:526). Aegis Dome: an ally hit this recently is under fire</summary>
                public static double DomeUnderFireSeconds = 1.0;
            }
        }

        private static readonly Entry[] Pack2Vehicles =
        {
            new Entry("vehicles.gearSystem.domeRadius", "m", () => Vehicles.GearSystem.DomeRadius, v => Vehicles.GearSystem.DomeRadius = (float)v),
            new Entry("vehicles.gearSystem.domeUnderFireSeconds", "s", () => Vehicles.GearSystem.DomeUnderFireSeconds, v => Vehicles.GearSystem.DomeUnderFireSeconds = v),
        };
    }
}
