// Generated by Tools/export/mbconst (move), balance pack 2. Each field is a literal that was in the code ("was":
// where); the defaults equal those literals. Edit Resources/Data/tunables.json, not this file.
#nullable enable

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Modes
        {
        }

        private static readonly Entry[] Pack2Modes =
        {
        };
    }
}
