// Generated by Tools/export/literal_to_tunable.py (mbconst move), balance pack 2 pass 2 (09/10). Each field is a
// literal that was in the code ("was": where); the defaults equal those literals (a negative literal keeps its sign).
// Edit Resources/Data/tunables.json, not this file.
#nullable enable

namespace MachineBrigade.Sim.Content
{
    public static partial class SimTunables
    {
        public static partial class Campaign
        {
        }

        private static readonly Entry[] Pass2Campaign =
        {
        };
    }
}
