"""MVA W1-B (spec parts Z, AB, BX, CG): model budget audit with an explicit enforcement policy.

Reads every GLB through glb_check.run (static; writes none of glb_check's files) and sorts each budget finding into:

  HARD     over the class hard cap on a metric that is enforced (renderers, moving parts): fails unless waived
  INFO     over the hard cap on triangles / vertices: kept by the owner's rule of 02/10 (budgets are a guide, AGENT_RULES),
           except units seen in numbers (technicals, light vehicles, towers): over 1.5 x the class maximum is HARD
  SOFT     over the soft budget: a warning to review
  WAIVED   a HARD finding with a formal waiver in budget_waivers.json (who, when, why, the follow-up)

    python Tools/assets/budget_audit.py        # writes Docs/models/BUDGET_OUTLIERS.md; exit 1 on an unwaived HARD finding
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
import glb_check  # noqa: E402

WAIVERS = HERE / 'budget_waivers.json'
REPORT = ROOT / 'Docs/models/BUDGET_OUTLIERS.md'
ENFORCED = ('renderers', 'movingParts')
SEEN_IN_NUMBERS = ('technical', 'light', 'tower')   # AGENT_RULES: stay at or under 1.5 x the class maximum
NUMBERS_FACTOR = 1.5
FOCUS = ('attack_jet', 'cp_relay', 'armored_bulldozer')   # spec part CG


def classify(name, rec, waivers):
    out = []
    tiers = glb_check.BUDGETS.get(rec.get('budgetClass') or '', {})
    tier = 'hd' if rec.get('hd') and 'hd' in tiers else 'normal'
    caps = dict(tiers.get(tier, {}))
    exception = glb_check.CAP_EXCEPTIONS.get(name, {})
    caps.update(exception)
    numbers = any(s in name for s in SEEN_IN_NUMBERS) or rec.get('budgetClass') == 'tower'
    for metric, (soft, hard) in caps.items():
        value = rec.get(metric, 0)
        if value <= soft:
            continue
        label = f"{rec.get('budgetClass')} {tier}"
        if value <= hard:
            status = 'SOFT'
        elif metric in ENFORCED or (numbers and value > hard * NUMBERS_FACTOR):
            status = 'HARD'
        else:
            status = 'INFO'
        if metric in exception:
            status = 'EXCEPTION' if status != 'SOFT' else status
        waiver = waivers.get(name, {}).get(metric)
        if status == 'HARD' and waiver:
            status = 'WAIVED'
        out.append({'model': name, 'metric': metric, 'value': value, 'soft': soft, 'hard': hard, 'class': label,
                    'status': status, 'over': value / hard, 'waiver': waiver})
    return out


def main():
    waivers = json.loads(WAIVERS.read_text(encoding='utf-8')).get('waivers', {}) if WAIVERS.exists() else {}
    names = sorted(p.stem for p in glb_check.MODELS.glob('*.glb'))
    records = glb_check.run(names)
    rows = []
    for n in names:
        rec = records[n]
        if 'loadError' in rec:
            rows.append({'model': n, 'metric': 'load', 'value': 0, 'soft': 0, 'hard': 0, 'class': '-', 'status': 'HARD',
                         'over': 0, 'waiver': None})
            continue
        rows += classify(n, rec, waivers)
    order = {'HARD': 0, 'WAIVED': 1, 'EXCEPTION': 2, 'INFO': 3, 'SOFT': 4}
    rows.sort(key=lambda r: (order[r['status']], -r['over'], r['model']))
    count = {s: sum(1 for r in rows if r['status'] == s) for s in order}
    lines = ['# Model budget outliers (MVA W1-B)', '',
             'Generated by `python Tools/assets/budget_audit.py` from glb_check (budgets: Docs/models/BUDGETS.md; waivers: '
             'Tools/assets/budget_waivers.json). Do not edit by hand.', '',
             'Policy (spec part Z): **HARD** = over the hard cap on an enforced metric (renderers, moving parts; triangles / '
             'vertices only for units seen in numbers past 1.5 x): fails unless waived. **WAIVED** = a HARD finding with a '
             'formal waiver (who, when, why, follow-up). **EXCEPTION** = a per-model cap in glb_check.CAP_EXCEPTIONS. '
             '**INFO** = triangles / vertices over the hard cap, kept by the owner\'s rule (02/10: budgets are a guide). '
             '**SOFT** = over the soft budget, review.', '',
             '| status | findings |', '| --- | --- |'] + [f'| {s} | {c} |' for s, c in count.items()] + [
             '', '## Spec part CG models', '', '| model | metric | value | soft / hard | class | status | waiver |',
             '| --- | --- | --- | --- | --- | --- | --- |']
    for r in rows:
        if r['model'].split('_hd')[0] in FOCUS:
            lines.append(f"| {r['model']} | {r['metric']} | {r['value']:,} | {r['soft']:,} / {r['hard']:,} | {r['class']} | "
                         f"{r['status']} | {(r['waiver'] or {}).get('reason', '')} |")
    lines += ['', '## Every finding (worst first)', '', '| model | metric | value | soft / hard | x hard | class | status |',
              '| --- | --- | --- | --- | --- | --- | --- |']
    for r in rows:
        lines.append(f"| {r['model']} | {r['metric']} | {r['value']:,} | {r['soft']:,} / {r['hard']:,} | {r['over']:.2f} | "
                     f"{r['class']} | {r['status']} |")
    REPORT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('BUDGETS: ' + ', '.join(f'{s} {c}' for s, c in count.items()) + f' -> {REPORT.relative_to(ROOT)}')
    for r in rows:
        if r['status'] == 'HARD':
            print(f"  HARD {r['model']} {r['metric']} {r['value']} > {r['hard']} ({r['class']})")
    return 1 if count['HARD'] else 0


if __name__ == '__main__':
    sys.exit(main())
