"""Applies an import manifest (Tools/export export.py import --dry-run) to the game data files by their real key paths.

    python Tools/balance/p29_apply.py --manifest <manifest_import.json> --dry-run         # checks, writes only the log
    python Tools/balance/p29_apply.py --manifest <manifest_import.json> --bundles "XL02-*"   # applies the bundles that pass

The prompt 29 rules, on real key paths instead of the C01 table:
- only a bundle whose Trạng thái is APPLY goes, and in it only the rows whose status is APPLY (DECIDE rows wait; a bundle
  with no APPLY row is SKIPPED);
- depends_on: every listed bundle must be applied first (in this manifest's state file), else BLOCKED;
- each row's precondition against the current file: ALREADY_APPLIED (current == new_value), OK (current ==
  expected_before within tolerance), else CONFLICT; one CONFLICT (or a path that does not resolve, a type change, a file
  outside Assets/) drops the whole bundle and nothing of it is written;
- the row's place is its id_path (vehicles[id=light_tank].cp: list items found by id, so a reordered list still resolves),
  checked against field_path; the value text is swapped in place (jsonc_edit.value_span), so comments, alignment and every
  other byte stay; after each bundle the file is parsed again and must equal the old data with only those leaves changed.
The log and the applied-bundle state sit beside the manifest (<stem>_apply_log.md, <stem>_apply_state.json).
--root points the data files at a copy (the checks in Tools/export/tests use a temp copy; never the real data).
"""
from __future__ import annotations

import copy
import fnmatch
import json
import math
import os
import re

from jsonc_edit import fmt, loads, value_span

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
EDITABLE = "Assets/"
GENERATED = {  # files a generator rewrites: the change also has to go to the generator's input
    "Assets/MachineBrigade/Resources/Data/campaign.json": "generated by Tools/campaign/build_campaign.py: edit act*.py / story.py too",
}
_TOKEN = re.compile(r'\[id=([^\]]+)\]|\["((?:[^"\\]|\\.)*)"\]|\[(\d+)\]|\.?([^.\[\]]+)')


class Bad(Exception):
    pass


def parse_path(text: str) -> list:
    """vehicles[id=light_tank].cp -> ['vehicles', ('id', 'light_tank'), 'cp']; vehicles[1].cp -> ['vehicles', 1, 'cp']."""
    segs, pos = [], 0
    while pos < len(text):
        m = _TOKEN.match(text, pos)
        if not m or m.end() == pos:
            raise Bad(f"bad path {text!r}")
        if m.group(1) is not None:
            segs.append(("id", m.group(1)))
        elif m.group(2) is not None:
            segs.append(m.group(2).replace('\\"', '"'))
        elif m.group(3) is not None:
            segs.append(int(m.group(3)))
        else:
            segs.append(m.group(4))
        pos = m.end()
    return segs


def resolve(data, segs: list) -> tuple:
    """The concrete path (keys and indices) of parsed segments in the data, or Bad."""
    out, node = [], data
    for s in segs:
        if isinstance(s, tuple):
            if not isinstance(node, list):
                raise Bad(f"[id={s[1]}] on a {type(node).__name__}")
            hits = [i for i, x in enumerate(node) if isinstance(x, dict) and x.get("id") == s[1]]
            if len(hits) != 1:
                raise Bad(f"id {s[1]} found {len(hits)} times")
            s = hits[0]
        if isinstance(s, int):
            if not isinstance(node, list) or s >= len(node):
                raise Bad(f"index {s} out of range")
        elif not isinstance(node, dict) or s not in node:
            raise Bad(f"no key {s!r}")
        out.append(s)
        node = node[s]
    if isinstance(node, (dict, list)):
        raise Bad("the path ends on an object or a list, not a value")
    return tuple(out)


def get(data, path):
    for s in path:
        data = data[s]
    return data


def set_in(data, path, value):
    for s in path[:-1]:
        data = data[s]
    data[path[-1]] = value


def kind(v) -> str:
    return "bool" if isinstance(v, bool) else "num" if isinstance(v, (int, float)) else "text" if isinstance(v, str) \
        else "null" if v is None else "other"


def equal(a, b, tol: float) -> bool:
    if kind(a) == kind(b) == "num":
        return math.isclose(float(a), float(b), rel_tol=0, abs_tol=tol + 1e-9)
    return kind(a) == kind(b) and a == b


def value_text(v) -> str:
    """The file's number format (jsonc_edit.fmt) when it reads back exactly, else the full repr."""
    t = fmt(v)
    if isinstance(v, float) and loads(t) != v:
        t = repr(v)
    return t


def deps(b: dict) -> list:
    return [x.strip() for x in str(b.get("depends_on") or "").split(",") if x.strip()]


def run(manifest: str, patterns: list, dry: bool, root: str | None = None) -> dict:
    root = os.path.abspath(root or ROOT)
    with open(manifest, encoding="utf-8") as f:
        man = json.load(f)
    stem = os.path.splitext(manifest)[0]
    log_path, state_path = stem + "_apply_log.md", stem + "_apply_state.json"
    applied = set(json.load(open(state_path, encoding="utf-8"))) if os.path.exists(state_path) else set()
    rows_by: dict[str, list] = {}
    for r in man.get("rows", []):
        rows_by.setdefault(r["bundle_id"], []).append(r)
    texts: dict[str, str] = {}   # data file -> current text (bundles applied so far, in memory)
    datas: dict[str, object] = {}
    touched: set[str] = set()
    outcome: dict[str, str] = {}
    lines = [f"\n## Run {'dry' if dry else 'apply'}: {', '.join(patterns)} (manifest {os.path.basename(manifest)}, "
             f"sha256 {str(man.get('sha256', ''))[:12]})\n", "| bundle | outcome | detail |", "|---|---|---|"]

    def load(sid):
        if sid not in texts:
            if not sid.startswith(EDITABLE) or not sid.endswith(".json") or ".." in sid.split("/"):
                raise Bad(f"{sid}: not a game data JSON file under {EDITABLE}")
            p = os.path.join(root, *sid.split("/"))
            if not os.path.isfile(p):
                raise Bad(f"{sid}: not found")
            with open(p, encoding="utf-8", newline="") as f:
                texts[sid] = f.read()
            datas[sid] = loads(texts[sid])
        return texts[sid], datas[sid]

    def note(bid, out, detail=""):
        outcome[bid] = out
        lines.append(f"| {bid} | {out} | {str(detail).replace('|', '/')} |")

    for b in man.get("bundles", []):
        bid = b["bundle_id"]
        if not any(fnmatch.fnmatch(bid, p.strip()) for p in patterns):
            continue
        if bid in applied:
            note(bid, "APPLIED", "in an earlier run")
            continue
        status = str(b.get("Trạng thái") or "").strip()
        if status != "APPLY":
            note(bid, f"SKIPPED({status or 'empty'})")
            continue
        rows = [r for r in rows_by.get(bid, []) if str(r.get("status") or "").strip() == "APPLY"]
        waiting = len(rows_by.get(bid, [])) - len(rows)
        if not rows:
            note(bid, "SKIPPED(no APPLY row)")
            continue
        missing = [d for d in deps(b) if d not in applied and outcome.get(d) not in ("OK", "ALREADY_APPLIED")]
        if missing:
            note(bid, "BLOCKED", f"waits for {', '.join(missing)}")
            continue
        plan, verdicts, conflict = [], [], None
        for r in rows:
            try:
                sid = str(r.get("data_file") or "")
                text, data = load(sid)
                path = resolve(data, parse_path(str(r.get("id_path") or r.get("field_path") or "")))
                if r.get("field_path") and r.get("id_path"):
                    try:
                        by_index = resolve(data, parse_path(str(r["field_path"])))
                    except Bad:
                        by_index = None
                    if by_index != path:
                        lines.append(f"| {bid} | note | {r['field_path']} moved: applied at {r['id_path']} |")
                cur, new, exp = get(data, path), r.get("new_value"), r.get("expected_before")
                tol = float(r.get("tolerance") or 0)
                if kind(new) != kind(cur):
                    raise Bad(f"type: data {kind(cur)}, new_value {kind(new)}")
                if equal(cur, new, tol):
                    verdicts.append("ALREADY_APPLIED")
                elif equal(cur, exp, tol):
                    verdicts.append("OK")
                    plan.append((sid, path, new))
                else:
                    raise Bad(f"{r.get('id_path') or r.get('field_path')}: current {cur!r}, expected {exp!r}, new {new!r}")
            except Bad as e:
                conflict = str(e)
                break
        if conflict:
            note(bid, "CONFLICT", conflict)
            continue
        if not plan:
            note(bid, "ALREADY_APPLIED")
            continue
        # The swap, per file, then the proof: the file parses and equals the old data with only these leaves changed.
        new_texts = {}
        try:
            for sid in sorted({p[0] for p in plan}):
                t = texts[sid]
                for _, path, new in sorted((p for p in plan if p[0] == sid), key=lambda p: -value_span(t, p[1])[0]):
                    s, e = value_span(t, path)
                    t = t[:s] + value_text(new) + t[e:]
                want = copy.deepcopy(datas[sid])
                for _, path, new in (p for p in plan if p[0] == sid):
                    set_in(want, path, new)
                if loads(t) != want:
                    raise Bad(f"{sid}: the swapped text does not read back as the planned change")
                new_texts[sid] = (t, want)
        except (Bad, ValueError, KeyError) as e:
            note(bid, "CONFLICT", f"swap failed: {e}")
            continue
        for sid, (t, want) in new_texts.items():
            texts[sid], datas[sid] = t, want
            touched.add(sid)
        gen = sorted({GENERATED[s] for s in new_texts if s in GENERATED})
        extra = (" (with ALREADY_APPLIED rows)" if "ALREADY_APPLIED" in verdicts else "") + \
                (f"; {waiting} rows not APPLY left" if waiting else "") + (f"; {'; '.join(gen)}" if gen else "")
        note(bid, "OK", f"{len(plan)} rows{' (dry)' if dry else ''}{extra}")

    if not dry:
        for sid in sorted(touched):
            p = os.path.join(root, *sid.split("/"))
            with open(p, "w", encoding="utf-8", newline="") as f:
                f.write(texts[sid])
        applied |= {b for b, v in outcome.items() if v in ("OK", "ALREADY_APPLIED")}
        with open(state_path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(sorted(applied), f, indent=1)
            f.write("\n")
    new_log = not os.path.exists(log_path)
    with open(log_path, "a", encoding="utf-8", newline="\n") as f:
        if new_log:
            f.write("# Import manifest apply log (Tools/balance/p29_apply.py --manifest)\n")
        f.write("\n".join(lines) + "\n")
    counts: dict[str, int] = {}
    for v in outcome.values():
        counts[v.split("(")[0]] = counts.get(v.split("(")[0], 0) + 1
    print(counts)
    return outcome
