"""Balance pass after prompt 18: before/after tables for every vehicle and tower, from the measurement files.

python Tools/balance/p18_tables.py [before_tag] [after_tag]   (defaults p18_before, p18_after)

Reads Docs/balance/combat_value_<tag>_summary.tsv, theoretical_dps_<tag>.tsv and tower_value_<tag>.tsv and
writes Docs/balance/tables_p18.md (Markdown tables: vehicles' combat value per CP and real DPS, every
vehicle's and tower's theoretical DPS against light / heavy / air / structure, the towers' duel worth in CP).
"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'Docs', 'balance')


def tsv(name):
    path = os.path.join(ROOT, name)
    if not os.path.exists(path):
        return []
    lines = [l for l in open(path, encoding='utf-8').read().splitlines() if l.strip()]
    head = lines[0].split('\t')
    return [dict(zip(head, l.split('\t'))) for l in lines[1:] if not l.startswith('reference') and not l.startswith('vehicles')]


def num(x, fmt='{:.0f}'):
    try:
        return fmt.format(float(x))
    except (TypeError, ValueError):
        return ''


def arrow(a, b, fmt='{:.0f}'):
    na, nb = num(a, fmt), num(b, fmt)
    if na == nb:
        return nb
    return f'{na} → {nb}' if na else nb


def main():
    before = sys.argv[1] if len(sys.argv) > 1 else 'p18_before'
    after = sys.argv[2] if len(sys.argv) > 2 else 'p18_after'
    out = [f'# Balance pass after prompt 18: before and after ({before} → {after})', '',
           'Generated by `Tools/balance/p18_tables.py` from the measurement files in this folder. Decisions: DECISIONS.md 19B.', '']

    cv0 = {r['id']: r for r in tsv(f'combat_value_{before}_summary.tsv')}
    cv1 = {r['id']: r for r in tsv(f'combat_value_{after}_summary.tsv')}
    out += ['## 1. Vehicles: combat value per CP (CombatValueMeasure, seeds 13-15)', '',
            'Ground = mean of the six ground groups; air = against the air group; "+AA / no AA" = the ground groups with an anti-air vehicle '
            'against those without (prompt 18 B.3); arty = artillery standing (the artillery hunters\' fight, not in the ground mean). Real DPS: '
            'what one vehicle really delivered a second while alive, against light / tanks / fort / air.', '',
            '| Vehicle | Class | CP | Ground | Air | +AA / no AA | Arty | Real DPS light / tanks / fort / air |', '|---|---|---|---|---|---|---|---|']
    for i, r in cv1.items():
        r0 = cv0.get(i, {})

        def ratio(row):
            try:
                aa = (float(row['light+AA']) + float(row['tanks+AA']) + float(row['fort+AA'])) / 3
                na = float(row['noAA'])
                return f'{aa / na:.2f}' if na > 0 else ''
            except (KeyError, ValueError):
                return ''
        rr0, rr1 = ratio(r0), ratio(r)
        rat = rr1 if rr0 == rr1 or not rr0 else f'{rr0} → {rr1}'
        dps = ' / '.join(arrow(r0.get(k), r.get(k)) for k in ('dpsLight', 'dpsHeavy', 'dpsFort', 'dpsAir'))
        out.append(f"| {i} | {r['class']} | {arrow(r0.get('cp'), r['cp'])} | {arrow(r0.get('ground'), r['ground'])} | {arrow(r0.get('air'), r['air'])} | "
                   f"{rat} | {arrow(r0.get('arty'), r.get('arty'))} | {dps} |")
    out.append('')

    t0 = {r['id']: r for r in tsv(f'theoretical_dps_{before}.tsv')}
    t1 = {r['id']: r for r in tsv(f'theoretical_dps_{after}.tsv')}
    out += ['## 2. Theoretical damage a second, every vehicle and tower', '',
            '`FirePower.Sustained` over a whole load with the damage table, penetration against each class\'s reference armour and plain armour bonuses '
            '(the design document\'s DPS table).', '',
            '| Unit | Class | CP | Light | Heavy | Air | Structure |', '|---|---|---|---|---|---|---|']
    for i, r in t1.items():
        if all(num(r.get(k)) in ('', '0') for k in ('light', 'heavy', 'air', 'structure')):
            continue
        r0 = t0.get(i, {})
        out.append(f"| {i} | {r['class']} | {arrow(r0.get('cp'), r['cp'])} | " + ' | '.join(arrow(r0.get(k), r[k]) for k in ('light', 'heavy', 'air', 'structure')) + ' |')
    out.append('')

    w0 = {r['id']: r for r in tsv(f'tower_value_{before}.tsv')}
    w1 = {r['id']: r for r in tsv(f'tower_value_{after}.tsv')}
    if w1:
        out += ['## 3. Towers: worth in vehicle CP (TowerValueMeasure, seeds 13-15)', '',
                'A tower alone against a ladder of attackers of rising CP (light vehicles, tanks, aircraft); its worth is the CP it holds against evenly, '
                'turned into the CP of a vehicle doing the same (the median vehicle\'s worth per CP). Prompt 18 A.1\'s bands in the main role: '
                'small 4-5, medium 7-8, large 11-12.', '',
                '| Tower | Size | Light | Tanks | Air |', '|---|---|---|---|---|']
        for i, r in w1.items():
            r0 = w0.get(i, {})
            out.append(f"| {i} | {r.get('size', '')} | " + ' | '.join(arrow(r0.get(k), r.get(k), '{:.1f}') for k in ('light_cp', 'tanks_cp', 'air_cp')) + ' |')
        out.append('')
    path = os.path.join(ROOT, 'tables_p18.md')
    open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('wrote', path)


if __name__ == '__main__':
    main()
