"""Prompt 32 L9: the base system's static audits (no simulation, no profiling).

    python Tools/balance/p32_base_audit.py    # writes Docs/checks/base_overlap.md and Docs/checks/base_perf.md

base_overlap.md: the pairs the prompt names (radar module / neutral radar; repair bay / neutral workshop / shield tower;
C-RAM / laser / shield) with what each does, where and at what price, and every pair of roster towers and branches that
still does the same job at the same reach for the same price (same targets, same damage type, reach within 10 %, same
rebuildCp). base_perf.md: the long-lived entities a side can have in Showdown at HQ 5 (HQ, towers, modules, wall
segments, the vehicle caps), the largest sources of short-lived ones, what is confirmed in the code, and NEED PROFILE.
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from p32_tower_prices import Model, layers  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OVERLAP = os.path.join(ROOT, "Docs", "checks", "base_overlap.md")
PERF = os.path.join(ROOT, "Docs", "checks", "base_perf.md")


def weapon_of(m, v):
    w = v.get("weapon")
    return m.W.get(w) if w and w != "none" else None


def job(m, v):
    """(targets, damage type, reach) of a tower's main weapon; None for an unarmed one."""
    w = weapon_of(m, v)
    if not w:
        return None
    air, ground = layers(w)
    targets = "all" if air and ground else "air" if air else "ground"
    return targets, w.get("damageType", "Kinetic"), float(w.get("range", 0) or 0)


def overlap(m):
    d = m.d
    V = m.V
    b = d["base"]
    n = d["neutrals"]["numbers"]
    lines = ["# Base system overlaps (prompt 32 L9, static)", "",
             "Generated by `Tools/balance/p32_base_audit.py` from balance.json. Nothing was changed here; the verdicts are the",
             "prompt's (keep apart) unless a pair below does the same job at the same reach for the same price.", "",
             "## The pairs the prompt names", "",
             "| pair | what, where | verdict |", "|---|---|---|"]
    radar = V.get("radar_station", {})
    lines.append(f"| Radar module (`radar_station`) / neutral radar site | the module reveals its own base (`utility.revealBase`: inside the base "
                 f"only), a utility slot; the neutral site reveals {n.get('radar.radius', 45)} m round its spot on the map for the side holding "
                 f"it (captured, no slot, no CP) | KEEP APART: one is the base's, the other a map area |")
    lines.append(f"| Repair bay (`repair_bay`) / neutral workshop / shield tower | the bay mends vehicles round the HQ "
                 f"({V.get('repair_bay', {}).get('utility', {}).get('repair', 0) * 100:.1f} % a second, a utility slot); the workshop mends vehicles at its "
                 f"map spot ({n.get('workshop.radius', 14)} m, {float(n.get('workshop.repair', 0)) * 100:.1f} % a second, captured); the shield tower "
                 f"guards towers and vehicles under its dome (radius {V.get('shield_tower', {}).get('dome', {}).get('radius', '-')} m, "
                 f"{V.get('shield_tower', {}).get('dome', {}).get('hp', '-')} hp, a large tower, {V.get('shield_tower', {}).get('rebuildCp', '-')} CP) "
                 f"| KEEP APART by object and place (repairs vehicles at home / on the map; absorbs damage) |")
    cram, laser = V.get("c_ram", {}), V.get("laser_ad_station", {})
    lines.append(f"| C-RAM / laser AD / shield tower | C-RAM: point defence radius {cram.get('aps', {}).get('radius')} m, "
                 f"{cram.get('aps', {}).get('charges')} interceptors, shells {cram.get('aps', {}).get('shells')}, {cram.get('rebuildCp')} CP; laser: "
                 f"radius {laser.get('aps', {}).get('radius')} m, {laser.get('aps', {}).get('charges')} interceptor, no shells, {laser.get('rebuildCp')} CP; "
                 f"shield: a dome | KEEP, under the point-defence stacking rule (one system per round, the nearest; L4) |")
    lines += ["", "## Same job, same reach, same price", "",
              "Every pair of roster cards and branches (the 22 cards and their branches) with the same targets, the same damage type,",
              "reaches within 10 % and the same rebuildCp:", ""]
    defs = []
    for card in b["roster"]:
        defs.append(card)
        defs += V.get(card, {}).get("branches", [])
    found = []
    for i, a in enumerate(defs):
        ja = job(m, V.get(a, {}))
        if not ja:
            continue
        for c in defs[i + 1:]:
            jc = job(m, V.get(c, {}))
            if not jc or ja[0] != jc[0] or ja[1] != jc[1]:
                continue
            if max(ja[2], jc[2]) <= 0 or abs(ja[2] - jc[2]) > 0.1 * max(ja[2], jc[2]):
                continue
            if V[a].get("rebuildCp") != V[c].get("rebuildCp"):
                continue
            same_card = a.split(".")[0] == c.split(".")[0]
            found.append((a, c, ja, V[a].get("rebuildCp"), V[a].get("towerRole", "-"), V[c].get("towerRole", "-"), same_card))
    if found:
        lines += ["| a | b | targets, damage, reach | CP | roles | note |", "|---|---|---|---|---|---|"]
        for a, c, j, cp, ra, rc, same in found:
            note = "a card and its own branch (the branch adds its role's mechanism)" if same else "REPORT: two cards"
            lines.append(f"| {a} | {c} | {j[0]}, {j[1]}, {j[2]:.0f} / {job(m, V[c])[2]:.0f} m | {cp} | {ra} / {rc} | {note} |")
    else:
        lines.append("None.")
    lines += ["", "Pairs of a card and its own branch inherit the card's gun by design (the branch differs by its role's mechanism:",
              "its `towerRole`, unique, checked by TowerRosterP32Tests); the ones marked REPORT are for the owner.", ""]
    return lines, found


def perf(m):
    d = m.d
    b = d["base"]
    lv = b["levels"][4]
    walls = d["base"]["walls"]
    cap_vehicles = 32
    cap_air = 6
    towers = lv["small"] + lv["medium"] + lv["large"]
    segs = walls.get("campLines", 2) * 5
    per_side = 1 + towers + lv["utility"] + segs + cap_vehicles + cap_air
    hangar = m.V.get("drone_hangar", {})
    mines = m.V.get("minefield", {}).get("mines", {})
    lines = ["# Base system performance (prompt 32 L9, static)", "",
             "Generated by `Tools/balance/p32_base_audit.py`. Counted from the data and read from the code; nothing was profiled.", "",
             "## Long-lived entities a side can have in Showdown at HQ 5", "",
             "| what | how many | from |", "|---|---|---|",
             "| HQ | 1 | the base |",
             f"| towers | {towers} | base.levels[5]: {lv['small']} small, {lv['medium']} medium, {lv['large']} large (a gun wall's tower is one of the small) |",
             f"| utility modules | {lv['utility']} | base.levels[5] |",
             f"| wall segments | up to {segs} | {walls.get('campLines', 2)} lines x 5 segments (the T-wall's extra counted) |",
             f"| ground vehicles | up to {cap_vehicles} | the vehicle cap (the opening squad and a Garrison HQ's squads inside it) |",
             f"| aircraft | up to {cap_air} | the air cap |",
             f"| **per side** | **about {per_side}** | the prompt expected about 75 |",
             f"| **the match** | **about {per_side * 2}** plus 0-2 neutral sites | the prompt expected about 150 |",
             "", "No outposts in Showdown (no capture points). Wrecks are views only (no entity).", "",
             "## The largest sources of short-lived entities", "",
             "| source | what | bound |", "|---|---|---|",
             "| every gun | `Projectile` objects (CombatSystem.Fire, `new Projectile` a shot); views from ProjectilePool / TracerPool | the rate of fire of up to 38 vehicles and 16 towers a side |",
             f"| drone hangar (`drone_hangar`, weapon `{hangar.get('weapon', '-')}`) and FPV carriers | drones flown as projectiles | their weapons' salvo and cooldown |",
             f"| minefield | its mines ({mines.get('max', '-')} at most, one every {mines.get('interval', '-')} s) | the card's max |",
             "| HQ barrage, supports, artillery | strikes and blasts (pending explosions) | the skill's cooldown, the supports' |",
             "| debris, decals, smoke | views only, DebrisPool / DecalPool | pooled |",
             "", "## Confirmed in the code", "",
             "- Walls run no per-tick logic: a segment switches only from `DamageSystem.OnVehicleDestroyed` (`WallSystem.OnDestroyed`,",
             "  one NavGrid switch at the next tick); the rubble slow runs in the 0.5 s slow-aura pass only while rubble exists; the",
             "  Showdown breach check looks every 0.5 s and is cached by the NavGrid version.",
             "- The Garrison's squads are held by the vehicle cap and the alive cap (L4: `baseCP` of the squads alive, the army cap).",
             "- Views of projectiles, tracers, debris and decals are pooled (Game/Effects/*Pool.cs). The Sim's `Projectile` is not",
             "  pooled: one allocation a shot.",
             "", "## NEED PROFILE", "",
             "- The Sim's `Projectile` allocations a second at the peak of a Showdown (GC on mobile).",
             "- NavGrid region relabelling when several wall segments fall in one tick (one relabel per grid version).",
             "- The slow-aura pass with many rubble areas (every ground vehicle against every area, every 0.5 s).",
             "- Draw calls of up to 20 wall segments and 32 towers on screen (two bases in view at the start of a Showdown).",
             "- AI: `SquadLayer.BreachChoice` per attacking squad per look (lines x segments x members; small, unmeasured).",
             ""]
    return lines


def main():
    m = Model()
    lines, found = overlap(m)
    with open(OVERLAP, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    with open(PERF, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(perf(m)) + "\n")
    print(f"{len(found)} same-job pairs ({sum(1 for x in found if not x[-1])} between two cards) -> {OVERLAP}; {PERF}")


if __name__ == "__main__":
    main()
