"""Combat final 04/10 (Docs/prompts/combat_rebalance_vi.md section 11): which penetration breakpoints each tier of the
tungsten_penetrator (vehicles) and sabot_rounds (towers) equipment crosses on the final direct and top attack tables.

Reads the tables from balance.json "damageTable" (penetration, topAttack) and the equipment values from
Game/Match/GearCatalog.cs / GearCatalog.Tower.cs (V(...) by rarity, the top-level values; a lower level has a share of
them, 40 % at level 1). The equipment adds a part level of penetration (Sim/Abilities/GearSystem.cs PenetrationUp); a part
level lies between the two neighbouring steps of the table (DamageTable.Read), so a tier under +1.0 never jumps a whole
step: it moves the round a share of the way to the next one. No game value is changed.

    python Tools/balance/tungsten_breakpoints.py [out.md]     # default Docs/checks/tungsten_breakpoints.md
"""
from __future__ import annotations

import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "Tools" / "export"))
from core import jsonc  # noqa: E402

RARITY = ["Common", "Uncommon", "Rare", "Epic", "Legendary"]
LABEL = ["+2", "+1", "0", "-1", "-2", "-3", "<=-4"]


def gear_values(path: Path, gid: str) -> list[float]:
    m = re.search(r'"%s"[^;]*?StatId\.Penetration,\s*V\(([^)]*)\)' % re.escape(gid), path.read_text(encoding="utf-8"))
    return [float(x.strip().rstrip("f")) for x in m.group(1).split(",")] if m else []


def read(row: list[float], diff: float, overmatch: bool = True) -> float:
    last = len(row) - 1
    step = 2.0 - diff
    if not overmatch:
        step = max(1.0, step)
    if step <= 0:
        return row[0]
    if step >= last:
        return row[last]
    lo = int(math.floor(step))
    t = step - lo
    return row[lo] + (row[min(last, lo + 1)] - row[lo]) * t


def step_of(diff: float) -> str:
    """The whole step a part level has reached (it reads between it and the next better one)."""
    k = math.floor(diff + 1e-9)
    return "+2" if k >= 2 else "<=-4" if k <= -4 else f"{k:+d}" if k else "0"


def main(out: Path) -> None:
    d = jsonc.loads((ROOT / "Assets/MachineBrigade/Resources/Data/balance.json").read_text(encoding="utf-8"))
    dt = d["damageTable"]
    direct, top = dt["penetration"], dt["topAttack"]
    hud = ROOT / "Assets/MachineBrigade/Scripts/Game/Match"
    tungsten = gear_values(hud / "GearCatalog.cs", "tungsten_penetrator")
    sabot = gear_values(hud / "GearCatalog.Tower.cs", "sabot_rounds")
    L = ["# tungsten_penetrator / sabot_rounds: breakpoints on the final tables (combat final 04/10)", "",
         "Generated by `python Tools/balance/tungsten_breakpoints.py`; no game value changed. Tables from balance.json "
         "`damageTable`: direct " + " / ".join(f"{v:g}" for v in direct) + "; top attack " + " / ".join(f"{v:g}" for v in top) + ".", "",
         "Equipment (top level, by rarity " + ", ".join(RARITY) + "): tungsten_penetrator +" + " / +".join(f"{v:g}" for v in tungsten)
         + " penetration levels; sabot_rounds (towers) +" + " / +".join(f"{v:g}" for v in sabot) + ". A lower item level has a share "
         "(40 % at level 1). A part level reads between two steps, so every tier under +1.0 moves the round that share of the way "
         "to the next better step; only Legendary (+1.0) lands exactly on it. No tier skips a step; the <= -4 bucket (0.08 direct, "
         "0.12 top) is reached only at pen - armour <= -4, and from -4 any tier lifts the round towards -3.", ""]
    for name, row, over in (("Direct fire (side-on faces, overmatch allowed)", direct, True),
                            ("Direct fire on a roof / aircraft (no overmatch: +1 at most)", direct, False),
                            ("Top attack (topAttack weapons against the roof)", top, True)):
        L += [f"## {name}", "", "| pen - armour | base | " + " | ".join(f"{r} +{v:g}" for r, v in zip(RARITY, tungsten)) + " |",
              "|---|---:|" + "---:|" * len(tungsten)]
        for base in (2, 1, 0, -1, -2, -3, -4, -5):
            cells = [f"{read(row, base, over):.3f}"]
            for v in tungsten:
                m = read(row, base + v, over)
                cells.append(f"{m:.3f} ({step_of(base + v)}{'' if abs(v - round(v)) < 1e-9 else ' toward ' + step_of(base + v + 1)})"
                             if read(row, base, over) != m else f"{m:.3f} (=)")
            L.append(f"| {LABEL[min(6, max(0, 2 - base))] if base > -5 else '-5'} | " + " | ".join(cells) + " |")
        L.append("")
    # Which weapons: the card vehicles' main weapons by penetration, and what each tier does against armour 0-5.
    W = {w["id"]: w for w in d["weapons"]}

    def resolved(wid, seen=()):
        w = dict(W.get(wid, {}))
        p = w.get("inherits")
        if p and p in W and p not in seen:
            base = resolved(p, seen + (wid,))
            base.update({k: v for k, v in w.items() if k != "inherits"})
            return base
        return w

    by_pen: dict[float, list[str]] = {}
    vehicles = []

    def walk(o):
        if isinstance(o, dict):
            if "id" in o and "weapon" in o and "hp" in o:
                vehicles.append(o)
            for x in o.values():
                walk(x)
        elif isinstance(o, list):
            for x in o:
                walk(x)
    walk(d["vehicles"])
    for v in vehicles:
        if float(v.get("cp", 0) or 0) <= 0 or v.get("boss") or v.get("static"):
            continue
        w = resolved(v["weapon"])
        if not w or float(w.get("damage", 0) or 0) <= 0 or "pen" not in w:
            continue
        by_pen.setdefault(float(w["pen"]), []).append(f"{v['id']} ({w['id']}{', top attack' if w.get('topAttack') else ''})")
    L += ["## Card vehicles' main weapons by penetration, and the step each tier reaches against armour 0-5", "",
          "Cell: the whole step the round reaches with the tier (direct / top attack read their own table; a part tier reads "
          "between that step and the next better one). Armour 5 is a boss's plate.", "",
          "| pen | armour | base step | " + " | ".join(f"{r} +{v:g}" for r, v in zip(RARITY, tungsten)) + " | weapons |",
          "|---:|---:|---|" + "---|" * len(tungsten) + "---|"]
    for pen in sorted(by_pen):
        names = ", ".join(sorted(by_pen[pen]))
        for a in range(0, 6):
            diff = pen - a
            def cell(v):
                if abs(read(direct, diff + v) - read(direct, diff)) < 1e-9:
                    return "= (no change)"
                return step_of(diff + v) + ("" if v >= 1 - 1e-9 else "→" + step_of(diff + v + 1))
            L.append(f"| {pen:g} | {a} | {step_of(diff)} | " + " | ".join(cell(v) for v in tungsten) + f" | {names if a == 0 else ''} |")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", out.relative_to(ROOT) if out.is_relative_to(ROOT) else out)


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "Docs" / "checks" / "tungsten_breakpoints.md")
